### PR TITLE
Support compressed position report

### PR DESCRIPTION
**Pull request by janm012012**
# Description
This PR changes the POSITION_REPORT_REGEX Issues & Solutions suggests by allowing any number of whitespaces between axes.

# Justification
If controllers send compressed position reports without whitespaces between the axes, the default regex does not match. With this modified version compressed reports are matched as well.

# Implementation Details
1. How did you test the change? Be descriptive. Untested code will not be accepted. **using my physical machine**
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? **yes**
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing. **no**
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted. **yes**

### CODE REVIEW

**Comment by markmaker** [comment]
Hi @janm012012, 

please undo the `Acceleration` space change. The space inside the curly brackets is wanted like that, it must only be added if the `Acceleration` variable is actually substituted, otherwise you get an unnecessary space before the command.

Regarding the `POSITION_REPORT_REGEX`. How sure are you, that just removing the space will not generate wrong matches? Have you looked at all the standard responses by all the controllers out there (at least the usual suspects)? 

I did that when I made this, so I'm reluctant to merge this, especially as it is not a standard response and will hardly ever become one. 

Just for the sake if sanity: how much time do you intend to invest into this? Shouldn't you follow Micaels lead, implement 4 Mbits/s and be done with it? I mean that's a factor of 40, your 5.5ms would become ~140μs i.e. "nothing" for the few coordinations OpenPnP needs.

_Mark

**Comment by markmaker** [comment]
I just saw that I seem to use another regex _without looking for spaces_ in `GcodeDriver.detectFirmwareSequence()`. So it seems to be okay to change that. Sorry about the back and forth. :sweat_smile: 

There are some I&S axis letter enumerations attached to `GcodeDriver.reportedAxes` so I kindly ask you to test any code that is using this (indirectly) too. Thanks!

_Mark

**Comment by janm012012** [comment]
I've reverted the Acceleration changed.

Without this PR I get "The driver does not report axes in the expected pattern". Is that what you asked me to test?

Else I find 

```
2024-11-19 15:00:47.706 GcodeDriver TRACE: Position report: okC:X:126.19Y:54.47Z:-6.60A:-112.5B:0.0C:0.0D:0.0
2024-11-19 15:00:47.706 GcodeDriver TRACE: Send-on-change logic for Feed Rate, Acceleration and Jerk reset
2024-11-19 15:00:47.707 GcodeDriver TRACE: GcodeDriver got response matching ".*[XYZABCDEUVW]:-?\d+\.\d+.*" after 8ms
2024-11-19 15:00:47.707 GcodeDriver DEBUG: === End detecting firmware and position reporting.
```
in the logs. Seems ok, at least no error... The suggested MOVE_TO_COMMAND and POSITION_REPORT_REGEX are reasonable too. Anything else you wont me to watch out for?

Jan

**Comment by markmaker** [comment]
No.

Test: delete the axis letters of all your axes. Press **Find I&S**. Check if it offers the right choice of axis letters in the drop down.

_Mark

**Comment by markmaker** [comment]
> "C:\s*" added

I think this has to be stricter. If I'm not mistaken, it will also match any position report with a C axis, i.e. including your M92, right? 

I.e. you have to _negatively_ test it against a position report which does _not_ have that pattern, and _negatively_ against M92.

The best thing would be to ask users on the group for their position reports from various controller makes (available on the driver GUI).

_Mark

**Comment by janm012012** [comment]
Hi @markmaker!

I just added a small enhancement: if the position report contains "C:" before the first axis letter (as Smoothie and Duet do and TinyG not - according to their respective documentation on the web) add it to the position report regex. This fixes the home-after-enable problem I've suffered from automatically.

I've done the test you suggested: removed axis letters on all axes, the position report in Driver Settings -> Detect firmware reads "okC:X:126.19Y:54.47Z:-6.60A:-112.5B:0.0C:0.0D:0.0" and I get a series of "Axis letter is missing. Assign the letter to continue." issues. The drop-down contains the 7 axes present in the report [XYZABCD]. For X, Y and Z, the solution has the correct axis letter selected. For my two nozzle axes and the peeler, the drop-down contains the remaining axis letters (ABCD) plus space, which is selected. So I have to select the correct driver letter myself. That looks all as I'd expect it.

Jan

**Comment by janm012012** [comment]
> > "C:\s*" added
> 
> I think this has to be stricter. If I'm not mistaken, it will also match any position report with a C axis, i.e. including your M92, right?

Your commend made the unsure, but https://regexr.com helped me to understand, that my pattern shall be ok: the "C:\s*[<axis letter<]" excludes all other occurrences of "C:" because they are all followed by digits before the next axis letter. My M92 response reads like "X:31.930000 Y:31.969999 Z:4.444400 A:4.444400 B:4.444400 C:69.264198 D:69.264198" so there are again digits between "C:" and the next axis letter.

Jan

**Comment by markmaker** [comment]
You're right, of course, the next character being a digit makes sure of that.

Just to be sure, have you tested the I&S axis letter detection, as I proposed [here](https://github.com/openpnp/openpnp/pull/1705#issuecomment-2487891914)?

_Mark

**Comment by markmaker** [comment]
Oh, silly me, I just saw that you already answered that, sorry.

> I've done the test you suggested: removed axis letters on all axes, the position report in Driver Settings -> Detect firmware reads "okC:X:126.19Y:54.47Z:-6.60A:-112.5B:0.0C:0.0D:0.0" and I get a series of "Axis letter is missing. Assign the letter to continue." issues. The drop-down contains the 7 axes present in the report [XYZABCD]. For X, Y and Z, the solution has the correct axis letter selected. For my two nozzle axes and the peeler, the drop-down contains the remaining axis letters (ABCD) plus space, which is selected. So I have to select the correct driver letter myself. That looks all as I'd expect it.

Is this ready to merge, then?

_Mark

**Comment by janm012012** [comment]
From my perspective it's fine.

Jan

**Comment by markmaker** [comment]
Thanks, @janm012012 :100:

**Pull request merged**
