### PR TITLE
Feature/fix rotated tray feeder

### PR DESCRIPTION
**Pull request by tonyluken**
# Description
This change fixes the issue documented below.
- [x] #1451

Other deficiencies corrected and other changes:
- Trays only worked within +/-90 degrees of the machine's X-axis.  They now work correctly at any arbitrary angle.
- Trays only worked if points A, B and C went clockwise around the tray. They now work correctly if the points go counter-clockwise around the tray as well.
- Trays can now be defined with a single row and single column.
- GUI fields now update automatically during feed operations.
- Additional/better error checking and validation was added.
- All GUI strings were externalized.
 
# Justification
Corrects a known bug and makes the Rotated Tray Feeder work as expected.

# Instructions for Use
One of the fields in the GUI has changed from _Component Rotation_ to _Component Rotation in Tray_. Prior to this change, the angle shown in this field was the actual pick angle for the component. Now this field displays the rotation of the component relative to the tray (which will almost always be one of 0, +/-90, or 180). The pick angle is now computed from the _Component Rotation in Tray_ plus the _Tray Rotation_. Note - existing Rotated Tray Feeders will automatically update the _Component Rotation in Tray_ field so that the pick angle remains the same as it was prior to this change.

Note that when the feed count is 0 or 1, the current pick location is the first component in the tray - this is now consistent with the behavior of other feeders.

# Implementation Details
1. How did you test the change? **Setup various different trays at various different angles on the machine and observed feed and pick operations.**
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? **Yes.**
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing. **No changes were made to those packages.**
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted. **All Maven tests were run and passed.**

### CODE REVIEW

**Comment by markmaker** [comment]
Thanks, @tonyluken,

This looks mostly good, just some remarks/questions:

- Nice upgrade handler. :+1: 
- Github shows inconsistent indentation in the diff, I guess there are tabs dragged in from earlier versions, please replace with all-spaces in changed sections, as per [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style).
-  Could be an old bug: `calculatePickLocation()` uses Millimeters without conversion, but I see you use system units when determining the `location` in `calculateOffsetsAndRotation()`. Needless to say, this would better use `Location.rotateXy()` and other `Location` arithmetic instead of messing with `sin()` and `cos()` and unit conversions itself.
- I wonder if you could move the "divide and modulo" thing into `calculatePickLocation()` to avoid code duplication. Instead of `partX`, `partY`, just pass the feed count.
- I see you rightfully wrinkle your nose where the rows/columns are swapped depending on which is shorter. I wonder if you could remove that and instead _convert_ the stored feed count in the upgrade handler. Now that the rotation of the tray has become meaningful, and `componentRotationInTray` must be understood by the user, similar to "rotation in tape", i.e., in relation to a clear "up" direction (which I guess is looking at a rows/columns in "reading order"), this would IMHO be the right thing to do. See also [here](https://github.com/openpnp/openpnp/wiki/ReferenceStripFeeder#rotation-in-tape).

_Mark

**Comment by markmaker** [comment]
Oh, I was too quick to send this. :sweat_smile: 

The upgrade handler cannot just convert the feed count, as parts were already picked from the tray in the wrong pattern, of course. Even rotating `offsets`  in the upgrade handler does not work, as the swapped order is left-handed. It's not that easy. 

Perhaps a legacy mode boolean?

_Mark

**Comment by tonyluken** [comment]
Ok, I think I addressed all of your concerns. Note that Component Rotation in Tray is relative to the A->B axis of the tray and there is a tool tip that states that. Hopefully that's clear enough.

**Comment by markmaker** [comment]
Very neat, thanks! :100:

**Pull request merged**
