### PR TITLE
Actuator Signaler Class

### PR DESCRIPTION
**Pull request by pfried**
As earlier promised i created an Actuator Signaler
Uses a machine actuator to signal machine or job states like error or run

As is do not have a machine yet i was not able to test it.

Also for some Machine Actuators (like a horn) a Timeout would be nice, but i wonder how to implement that.

Thoughts on this?

### CODE REVIEW

**Comment by pfried** [comment]
Related #244

**Comment by vonnieda** [comment]
Looks good! Thanks for the nice feature @pfried!

For the timer, check out http://docs.oracle.com/javase/7/docs/api/java/util/Timer.html. You can just set a timer for N seconds when the actuator fires and when the timer expires you can turn it back off. I'd suggest making the timer value configurable in the signaler XML.

**Comment by pfried** [comment]
Thanks, i just noticed that i should not have set default values. Is it possible to set null values in the xml? Otherwise i should remove the default values as this leads to the situation where the actuator always reacts to machine and job errors even if i do want it only for one of them.

**Comment by vonnieda** [comment]
Null values would not be appropriate here. I will remove the defaults and add the new configuration information to the wiki so that people can easily find it.

**Comment by vonnieda** [comment]
Wiki updated and default signalers removed
https://github.com/openpnp/openpnp/wiki/Signalers

**Pull request merged**
