### PR TITLE
Fix/Panelization Settings window height

### PR DESCRIPTION
**Pull request by lags**
# Description
Fixes Panelization Settings window height reported in #1325

### CODE REVIEW

**Comment by markmaker** [comment]
I'm not a Java GUI expert, but can this not be made dynamic, to shrink-wrap the controls?

_Mark

**Comment by lags** [comment]
Me too not expert but `pack();` should be better than raise height value.

image

As you can see, pack not shrink control for parent frame but resize window for the best view referred setSize function.

image

Have sense?

**Comment by markmaker** [comment]
I'm not sure I understand. Do you think this is better or not?

For me `pack()` sounds exactly right. Can you  add it and push again?

_Mark

**Comment by lags** [comment]
Yes Mark. I think that with `pack()` function is better than raise height size. I make new PR.

**Comment by lags** [comment]
I think not need make new PR because when commit with `--amend` this PR will be updated

**Comment by markmaker** [comment]
> I think not need make new PR because when commit with `--amend` this PR will be updated

No need. You could just change the code, commit and push again.

I'll merge this now, thanks, @lags 

_Mark

**Pull request merged**
