### PR TITLE
Nozzle Tip: Dwell Time

### PR DESCRIPTION
**Pull request by sp-apertus**
# Description
The Dwell Pick and Dwell Place times have been added to Nozzle Tip class and the Nozzle Tip Wizard GUI.
I also added a note that the total dwell time is the sum of both nozzle dwell time and nozzle tip dwell time.

I have found no reference of where/how getPlaceDwellMilliseconds() is actually used (in job planner or machine driver?) so I need some guidance before I can finish this feature.

### CODE REVIEW

**Comment by vonnieda** [comment]
They are used in ReferenceDriver.pick and .place. Easy way to find this
kind of stuff (in Eclipse) is to right click the property and choose
References -> In Project. In this case, it uses the variable directly
(which is a little sloppy on my part) rather than the getter, so you have
to search for both the getter and the variable.

Jason

**Comment by sp-apertus** [comment]
Thanks!

All done and tested with nulldriver simulation.

**Comment by vonnieda** [comment]
Great work as usual @sp-apertus, thank you for making this easy to merge :)

**Comment by sp-apertus** [comment]
as always: my pleasure :)

**Pull request merged**
