### PR TITLE
Demo Board v2

### PR DESCRIPTION
**Pull request by anthonywebb**
Added coverage for all major IC pitch types.  1mm keepout around all fiducials. Bottom layer tests. Logical placement and labeling for top and bottom layers.  Tricky/tall/heavy components (capacitors, inductors).

### CODE REVIEW

**Comment by anthonywebb** [comment]
Sorry I had to break up the pull request into 3 parts, was doing it through the github web ui and it didnt allow me to group them

**Comment by vonnieda** [comment]
Looks really, really great! Can I suggest adding silk names to the fids to
make it easier for the user to know which ones they are selecting?

Jason

**Comment by anthonywebb** [comment]
You bet, coming right up

**Comment by vonnieda** [comment]
A couple more notes:

It's important that the silk match the part names, since this is how the
user identifies the parts in OpenPnP. I noticed that the TQFP silk doesn't
match and C2 is labeled C1. There may be others, but I didn't check them
all.

A really common use case for this demo board is to look at the board, see a
part name and then look in OpenPnP and match that to a placement so you can
see if your machine accurately moves to it, so it's important that these
all match up.

Jason

**Comment by anthonywebb** [comment]
Thanks for the heads up, we will review them all and get an update

**Comment by vonnieda** [comment]
Thanks Anthony. Can't wait to get some of these made. They look great!

**Comment by anthonywebb** [comment]
OK, updated the board, added a calibration ruler, and 10mm calibration square on the bottom layer, things I wish we had had when we were calibrating our camera.  If there is anything else missing feel free to ask.  If all looks good I am planning on getting a batch of 100 coming and putting them up on tindie or similar so people dont need to pay/wait for an entire batch when they may only need one.

Note that we created gerbers as well so everything shows up the way it was intended.
screenshot 2016-01-27 12 58 54
screenshot 2016-01-27 12 59 24

**Comment by vonnieda** [comment]
Looks really great @anthonywebb, thanks for putting this together!

**Comment by aep** [comment]
nice!   can you do me a favor and put a 2x2mm 14pin LGA ( i had issues with this) on this as well as some WLP/BGA for completeness?   Also the ruler on that thing is metric i hope? Mighty useful for tuning the steppers. But would be nice if you joined the two 0 markers, so we can line them up with the openpnp crosshair.

**Comment by anthonywebb** [comment]
Great requests, let me update

On Wed, Jan 27, 2016 at 1:39 PM, Arvid E. Picciani <notifications@github.com

**Comment by anthonywebb** [comment]
@aep do you have a part number for that 2x2mm 14pin LGA ?  Having a hard time finding anything in eagle for that one.  Also, yes, the ruler is metric, 1mm per tick

**Comment by anthonywebb** [comment]
@aep also will need to know which WLP/BGA you would like to see, other than that and the 14pin LGA we are ready, I made the appropriate modification to the ruler.

**Pull request merged**
