### PR TITLE
Update GcodeDriver.java

### PR DESCRIPTION
**Pull request by bilsef**
Add MOVE_TO_COMPLETE_COMMAND to separate the move command from the wait for completion command.  Allows simultaneous moves across multiple drivers.

-----------------------------------------------------------------------

# Description
Separates the "wait for completion" part of the MOVE_TO_COMMAND to a MOVE_TO_COMPLETION_COMMAND.

# Justification
This allows moves to be sent to multiple controllers simultaneously and can then wait for them to complete individually.

# Instructions for Use
To use the feature, remove M400 from the MOVE_TO_COMMAND and add M400 to the MOVE_TO_COMPLETE_COMMAND.  Use of this feature is optional.  If there is nothing in the MOVE_TO_COMPLETE_COMMAND it will be ignored.

This is documentation for a user, not for a developer.

# Implementation Details
1. Tested on a machine with two controllers.  The main controller has Z, C1, and C2.  The sub controller has X, Y.  Sending the instruction "moveTo((163.280000, 209.530000, 0.000000, -180.000000 mm), 1.0)" sends the following to the controllers:
GcodeDriver TRACE: [serial://COM4] >> T0
GcodeDriver TRACE: [serial://COM4] << echo:Active Extruder: 0
GcodeDriver TRACE: [serial://COM4] << ok
GcodeDriver TRACE: [serial://COM4] >> G0  E-180.0000 F50000 ; Send standard Gcode move
GcodeDriver TRACE: [serial://COM4] << ok
GcodeDriver TRACE: [serial://COM5] >> G1 X177.2349 Y259.1500 F30000
GcodeDriver TRACE: [serial://COM5] << ok
GcodeDriver TRACE: [serial://COM5] >> G1 X177.7349 Y259.6500   F3000
GcodeDriver TRACE: [serial://COM5] << ok
GcodeDriver TRACE: [serial://COM5] >> M400; wait for completion (sub)
GcodeDriver TRACE: [serial://COM5] << ok
GcodeDriver TRACE: [serial://COM4] >> M400 ; Wait for completion (main)
GcodeDriver TRACE: [serial://COM4] << ok

2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)?  Yes
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing.  N/A
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted.  No failures.

### CODE REVIEW

**Comment by markmaker** [comment]
Hi  @bilsef 

very nice IMHO. Of course @vonnieda should still have a look. 

In the meantime you could perhaps also add a quick description to the [CHANGES.md](https://github.com/openpnp/openpnp/blob/develop/CHANGES.md) file. 

After this is merged, the Wiki should be updated as well. 
https://github.com/openpnp/openpnp/wiki/GcodeDriver:-Command-Reference#move_to_command

Personally I would love to see a little movie of your machine :-)

_Mark

**Comment by vonnieda** [comment]
Looks good to me!

**Comment by netzmark** [comment]
So with this change it's possible to initiate Z motion and start XY until being sure the Z final position is achieved? Is this not a good way to destroy the nozzle tip that is not raised up enough yet?
But it's great looking on C.

**Comment by vonnieda** [comment]
@netzmark I don't think so. OpenPnP always starts with moveToSafeZ(), and that will not return until the MOVE_TO_COMPLETE_COMMAND is sent and confirmed.

**Comment by bilsef** [comment]
Updated Wiki and CHANGES.md

**Pull request merged**
