### PR TITLE
Permanent fix for MacOS builds

### PR DESCRIPTION
**Pull request by prusk**
# Description
Currently the MacOS builds are broken due to the notarization process not being implemented.
Install4J does support notarization and this change takes advantage of it.

This change requires additional input from @vonnieda  for 2 parameters, a secret app-password configured with the same apple-id that generated the signing certificate and the said Apple ID (also a secret if possible).

# Justification
MacOS builds are broken as described here: https://github.com/openpnp/openpnp/pull/1628#issuecomment-2142761793

# Instructions for Use
Nothing changes for the user

# Implementation Details
1. How did you test the change? Be descriptive. Untested code will not be accepted.
* Couldn't test without Jason's credentials. I tested using mine and it worked.
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)?
* Yes
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing.
* No change
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted.
* Yes

Additional notes for @vonnieda :
* I used this document from Install4J: https://www.ej-technologies.com/resources/install4j/v/10.0/help/doc/concepts/codeSigning.html?light
* Please take a look at the section "Notarizing media files on macOS" - pretty short
* This PR can be followed up quickly by your own that changes the placeholders I used for the AppleID and the app password secret
* I am not sure if the AppleID can also be a secret so it's worth trying that way first
* The only way that Install4J would do the notarization and its multiple steps is if the build process runs on "macos-latest"
* I did build on a Mac machine and the process did correctly create the installers for MacOS, Linux & Windows
    * However, I do not have a Windows machine available to test the exe file since I threw them all away about 10 years ago :)
    * Also, I don't own any Linux desktop machine...

### CODE REVIEW

**Comment by vonnieda** [comment]
Thank you @prusk! I'll get the required info setup and get this merged this week.

**Comment by prusk** [comment]
Hi Jason @vonnieda,

Any chance we can get this fixed soon?

Thanks.

**Comment by vonnieda** [comment]
Okay, I've merged this and patched up a few little issues. It seems to build, and the notarization looks good:

```
> spctl --assess --type execute --verbose=4 /Volumes/openpnp/OpenPnP.app
/Volumes/openpnp/OpenPnP.app: accepted
source=Notarized Developer ID
```

Can you grab the latest from test and see if it works for you?

https://s3-us-west-2.amazonaws.com/openpnp/OpenPnP-macos-test.dmg

Also, thank you for all your work on resolving this!

Thanks,
Jason

**Comment by prusk** [comment]
Works without any issues for me.
Thank you Jason @vonnieda !

**Pull request merged**
