### PR TITLE
Feature/new panelization

### PR DESCRIPTION
**Pull request by tonyluken**
# Description
This change revamps how Panels are defined and used in OpenPnP from both the operator and code perspectives. It corrects many of the deficiencies inherent in the legacy method of creating Panels, some of which are documented in the following issues:
- [ ] #1470
- [ ] #1464
- [ ] #1444 
- [ ] #1326 
- [ ] #949 
- [ ] #881 
- [ ] #823 
- [ ] #813 
- [ ] #501

## Operator's Perspective ##
From the operator's perspective, the main change is the addition of two new tabs to the GUI: _Boards_ and _Panels_. 
newTabs

### Standard Workflow ###
In the past, Boards and Panels were created and edited directly on the _Job_ tab. While there is still some support for doing so, the recommended standard workflow is:

1. Create and edit Boards on the [_Boards_ tab](#boards_tab_anchor).
2. Optionally create and edit Panels on the [_Panels_ tab](#panels_tab_anchor) populating them with the Board(s) created in step  1.
3. Create and edit the Job on the [_Job_ tab](#job_tab_anchor) using the Boards and/or Panels created in steps 1 and 2.

<a id="boards_tab_anchor">

### Boards Tab ###
The _Boards_ tab is the main area for defining and editing Board definitions such as setting the Board's width and length, importing Placements, etc. Note that the legacy method of editing Boards directly in the _Job_ tab is still supported but only if there is a single instance of the Board in the Job and it is at the top level of the Job, that is, it is not part of a Panel that is part of the Job.
</a>boardsTab

<a id="panels_tab_anchor">

### Panels Tab ###
The _Panels_ tab is the main area for defining and editing Panel definitions such as setting the Panel's width and length, adding children (Boards and/or (sub)Panels), creating arrays of children, and adding Panel alignment fiducials.
panelsTab

<a id="job_tab_anchor">

### Job Tab ###
The _Job_ tab is now mainly for defining and running Jobs.  The Job table has a new column on the left that displays an icon and an ID for each Board and/or Panel in the Job. The icon indicates at a glance if the row holds a Board or a Panel. The icons are indented to show the nesting level of the Boards and/or Panels within other Panels.  The legacy Panelization tools have been removed from the _Job_ tab since equivalent or better functionality is available on the _Panels_ tab. A tool for visualizing a graphical layout of the Job has been added.
jobTabChanges

The *.job.xml file format changes with this PR. When a legacy *.job.xml file is loaded into OpenPnP, an unmodified copy of it is stored with the name *.legacy.job.xml and then the original is updated to the new format. For legacy panelized jobs, not only is the *.job.xml copied and modified as above, a new *.panel.xml file is created with the same name as the job and is stored in the directory with the job. Note that legacy panels may look a bit odd in the Job and Panel Viewers because the legacy panel included no information on the true dimensions of the Panel. Nevertheless, the job should still work as it has previously.

## Code Perspective ##
The code has been refactored to abstract out the common elements in Board, Panel, BoardLocation, and Placement types.
Below is a simplified Class Diagram showing how the various classes now relate.  A new interface called Definable is used to allow deep copies of objects to remain one-way linked with the original copy.  This permits changes to the defining object to propagate to the copies yet allows the individual copies to be changed without affecting one another or the defining object.
classDiagram
The Job type has also been restructured to change it from holding a flat list of Boards to a tree-like structure where the root node is a Panel. All Boards and Panels are now held as children of the root node. A mentioned above, this does affect the format of the *.job.xml files. When legacy format *.job.xml files are encountered, they are first copied to *.legacy.job.xml for backup and are then converted to the new format.
# Justification
Besides correcting the above-mentioned deficiencies, there are many new and improved features over what was available with the legacy panelization:

| Feature | Legacy Panelization | New Panelization |
| :--- | :--- | :--- |
| Panels stand alone? | No - only exist within a Job | Yes - each panel definition is saved in its own *.panel.xml file similar to the way boards have always been handled |
| Number of Board Types | 1 | Unlimited |
| Use of subpanels | No | Yes - Panels can be used as subpanels in another's definition |
| Layout | Rectangular Arrays Only | Arbitrary |
| Mix of Top/Bottom on same panel? | No - all boards must face the same way | Yes - boards/subpanels can be flipped either way |
| Auto Generation Tool | Rectangular Arrays Only | Rectangular, Rectangular with Offset Rows, Circular Arrays |
| Manual Generation | No - only can be auto-generated | Yes - boards/subpanels can be manually added, deleted, moved, rotated, and flipped |
| Panel fiducials | 2 maximum - limited to one side only | Unlimited - each side has own fiducials |
| Panel fiducial Part types | 1 | Each fiducial can have a unique Part type |
| Alignment includes compensation for scaling and shearing errors | No - only the panel's location and rotation are corrected | Yes - all Board, subpanel, and Placement locations are corrected for translation, rotation, scaling, and shearing errors | 
| Panel alignment using board fiducials? | No | Yes |
| Panel alignment using board placements? | No | Yes |

In addition to the above improvements, a couple of other features/enhancements are provided:

- Table column widths are now remembered on the Job, Boards, and Panels tabs. This feature should be easy to add to tables on other tabs but is out of scope for this PR.
- Table columns on the Job, Boards, and Panels tabs with numerical contents are now aligned on the decimal point. This feature should also be easy to add to tables on other tabs but is out of scope for this PR.
- A viewer dialog is available for the operator to see a graphical representation of the current job (and of Boards and Panels as well).

# Instructions for Use
Wiki updates are in progress.

# Implementation Details
1. How did you test the change? Be descriptive. Untested code will not be accepted. **A facsimile of a panelized design for test purposes was created in a CAD program with deliberate scaling and shearing distortions as shown below.  The panel's top and bottom images were printed on paper and then attached back-to-back with a stiff piece of cardboard sandwiched between to create a test article that could be positioned on the machine table.**

**CAD drawing of the Top and Bottom sides of the test article:**
testPanel

**Photos of the actual test article:**
<p align="center" width="100%">
    testPanelPhotoTop 
    testPanelPhotoBottom 
</p>

**In OpenPnP, a new board called test1.board.xml was created on the _Boards_ tab describing the location of the Placements and fiducials in its undistorted state (see the [_Boards_ tab](#boards_tab_anchor) image above). A subpanel called test1.panel.xml was created containing three copies of test1.board.xml. A Panel called test2.panel.xml was created containing four copies of the subpanel (see the [_Panels_ tab](#panels_tab_anchor) image above). The test article was placed on the machine table and a Job created with test2.panel.xml plus two other Boards (see the [_Job_ tab](#job_tab_anchor) image above). Fiducial checks were conducted at the board, subpanel, and Panel levels and the locations of the Panel, subpanels, boards, and Placements were observed to be correct. The tests were repeated after flipping the Panel over to observe the correctness of locations on the opposite side of the Panel as well.**

2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? **Yes**
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing. **Yes - changes were required in these packages due to the refactoring of the code.** 
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted. **All Maven tests have been run and passed.**

### CODE REVIEW

**Comment by vonnieda** [comment]
Looks great @tonyluken - I'm very much in support of the UI changes. I think it makes setting up boards and jobs much easier.

**Comment by vonnieda** [comment]
Side note: @tonyluken you should be able to edit the wiki directly now.

**Comment by markmaker** [comment]
Hi @tonyluken,

just playing around with it and it looks very good. :+1: :+1: 

Very cool how the boards turn blue when nailed by fiducial checks. 

The [video](https://youtu.be/JW3Wu1-PoBE) is also nice!

Feedback:

As you know, I'm not a native English speaker, so take this with a grain of salt: is there no better term to describe the nature of `Definable`? In other contexts, similar concept are termed as "prototype" or "template". Conversely, the term "definition" has other meaning for me, perhaps from its [common use in "declaration" and "definition"](https://stackoverflow.com/questions/1410563/what-is-the-difference-between-a-definition-and-a-declaration), you could even say that the relationship is _reversed_. But again, that's just the Swiss guy double-checking 😅.

A few minor hiccups I encountered: 

- The `ExistingBoardOrPanelDialog` (and perhaps other similar dialogs) should be parented to the `MainFrame`. Otherwise they appear as a separate app in the task list and are positioned _anywhere_ on the monitor, including hidden behind the main OpenPnP window.  

- I opened the included (legacy) sample `pnp-test.job.xml`, then on the **Jobs** tab clicked on any board line on the **Board/Panel Id** column cell (clicking on any other cell works):

```Java
2022-12-31 15:36:25.877 Configuration INFO: A legacy job file has been detected, it is being updated to the new format.
2022-12-31 15:36:25.877 Configuration INFO: A backup of the legacy job file has been copied here: /home/markus/git/openpnp/samples/pnp-test/pnp-test.legacy.job.xml
2022-12-31 15:36:25.878 Configuration TRACE: Dump of the jobRootPanelLocation
2022-12-31 15:36:25.878 PanelLocation TRACE:  (null) PanelLocation:@053f4b7e defined by @053f4b7e child of @00000000, null, location=(0.000000, 0.000000, 0.000000, 0.000000 mm) , globalLocation=(0.000000, 0.000000, 0.000000, 0.000000 mm) side=Top (Panel @5cad10f3 defined by @5cad10f3: file /home/markus/git/openpnp/samples/pnp-test/pnp-test.job.xml, dims: 0.000mmx0.000mm, fiducial count: 0, children: 8)
2022-12-31 15:36:25.879 BoardLocation TRACE:   +-- (Brd1) BoardLocation:@5a54d4c9 defined by @5a54d4c9 child of @053f4b7e, /home/markus/git/openpnp/samples/pnp-test/pnp-test.board.xml, location=(3.994595, 4.413185, 0.000000, 0.007895 mm) globalLocation=(3.994595, 4.413185, 0.000000, 0.007895 mm), side=Top (Board @5c995910 defined by @23829d46: file /home/markus/git/openpnp/samples/pnp-test/pnp-test.board.xml, dims: 37.000mmx0.000mm, placements: 30 @26f0a92a (@51caf885))
2022-12-31 15:36:25.879 BoardLocation TRACE:   +-- (Brd2) BoardLocation:@21510f48 defined by @21510f48 child of @053f4b7e, /home/markus/git/openpnp/samples/pnp-test/pnp-test.board.xml, location=(5.138645, 62.743655, 0.000000, -19.947362 mm) globalLocation=(5.138645, 62.743655, 0.000000, -19.947362 mm), side=Top (Board @1fed143f defined by @23829d46: file /home/markus/git/openpnp/samples/pnp-test/pnp-test.board.xml, dims: 37.000mmx0.000mm, placements: 30 @b99f01b8 (@51caf885))
2022-12-31 15:36:25.879 BoardLocation TRACE:   +-- (Brd3) BoardLocation:@13ba84be defined by @13ba84be child of @053f4b7e, /home/markus/git/openpnp/samples/pnp-test/pnp-test.board.xml, location=(64.489808, 7.248273, 0.000000, 0.604803 mm) globalLocation=(64.489808, 7.248273, 0.000000, 0.604803 mm), side=Bottom (Board @7886fc89 defined by @23829d46: file /home/markus/git/openpnp/samples/pnp-test/pnp-test.board.xml, dims: 37.000mmx0.000mm, placements: 30 @f20414a1 (@51caf885))
2022-12-31 15:36:25.880 BoardLocation TRACE:   +-- (Brd4) BoardLocation:@005ee6ad defined by @005ee6ad child of @053f4b7e, /home/markus/git/openpnp/samples/pnp-test/pnp-test.board.xml, location=(84.336372, 46.650270, 0.000000, 36.608756 mm) globalLocation=(84.336372, 46.650270, 0.000000, 36.608756 mm), side=Bottom (Board @69e00478 defined by @23829d46: file /home/markus/git/openpnp/samples/pnp-test/pnp-test.board.xml, dims: 37.000mmx0.000mm, placements: 30 @d73af8e7 (@51caf885))
2022-12-31 15:36:25.880 BoardLocation TRACE:   +-- (Brd5) BoardLocation:@117300e8 defined by @117300e8 child of @053f4b7e, /home/markus/git/openpnp/samples/pnp-test/pnp-test.board.xml, location=(59.177394, 120.838635, 0.000000, -28.179275 mm) globalLocation=(59.177394, 120.838635, 0.000000, -28.179275 mm), side=Bottom (Board @7c19e57d defined by @23829d46: file /home/markus/git/openpnp/samples/pnp-test/pnp-test.board.xml, dims: 37.000mmx0.000mm, placements: 30 @8e6e0170 (@51caf885))
2022-12-31 15:36:25.880 BoardLocation TRACE:   +-- (Brd6) BoardLocation:@49bcb64c defined by @49bcb64c child of @053f4b7e, /home/markus/git/openpnp/samples/pnp-test/pnp-test.board.xml, location=(155.017595, 151.331550, 0.000000, 157.092969 mm) globalLocation=(155.017595, 151.331550, 0.000000, 157.092969 mm), side=Top (Board @68f43f77 defined by @23829d46: file /home/markus/git/openpnp/samples/pnp-test/pnp-test.board.xml, dims: 37.000mmx0.000mm, placements: 30 @4dac4fbf (@51caf885))
2022-12-31 15:36:25.880 BoardLocation TRACE:   +-- (Brd7) BoardLocation:@012d3e4c defined by @012d3e4c child of @053f4b7e, /home/markus/git/openpnp/samples/pnp-test/pnp-test.board.xml, location=(183.954660, 146.597000, 0.000000, -140.606916 mm) globalLocation=(183.954660, 146.597000, 0.000000, -140.606916 mm), side=Bottom (Board @31df5fbe defined by @23829d46: file /home/markus/git/openpnp/samples/pnp-test/pnp-test.board.xml, dims: 37.000mmx0.000mm, placements: 30 @c1d9a6e9 (@51caf885))
2022-12-31 15:36:25.880 BoardLocation TRACE:   +-- (Brd8) BoardLocation:@31bb22d6 defined by @31bb22d6 child of @053f4b7e, /home/markus/git/openpnp/samples/pnp-test/pnp-test.board.xml, location=(38.020443, 100.912063, 0.000000, 76.646032 mm) globalLocation=(38.020443, 100.912063, 0.000000, 76.646032 mm), side=Top (Board @13f52baf defined by @23829d46: file /home/markus/git/openpnp/samples/pnp-test/pnp-test.board.xml, dims: 37.000mmx0.000mm, placements: 30 @0bbfa6c5 (@51caf885))
2022-12-31 15:36:28.796 SystemLogger ERROR: Exception in thread "AWT-EventQueue-1" java.lang.NullPointerException
2022-12-31 15:36:28.797 SystemLogger ERROR: 	at org.openpnp.gui.support.CustomPlacementsHolderRenderer.getTableCellRendererComponent(CustomPlacementsHolderRenderer.java:83)
2022-12-31 15:36:28.797 SystemLogger ERROR: 	at org.openpnp.gui.support.CustomAlignmentRenderer.getTableCellRendererComponent(CustomAlignmentRenderer.java:52)
2022-12-31 15:36:28.797 SystemLogger ERROR: 	at javax.swing.JTable$AccessibleJTable.getAccessibleChild(JTable.java:7037)
2022-12-31 15:36:28.797 SystemLogger ERROR: 	at javax.swing.JTable$AccessibleJTable.getAccessibleAt(JTable.java:7424)
2022-12-31 15:36:28.797 SystemLogger ERROR: 	at javax.swing.JTable$AccessibleJTable.valueChanged(JTable.java:6939)
2022-12-31 15:36:28.797 SystemLogger ERROR: 	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:184)
2022-12-31 15:36:28.797 SystemLogger ERROR: 	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:164)
2022-12-31 15:36:28.797 SystemLogger ERROR: 	at javax.swing.DefaultListSelectionModel.fireValueChanged(DefaultListSelectionModel.java:211)
2022-12-31 15:36:28.797 SystemLogger ERROR: 	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:405)
2022-12-31 15:36:28.797 SystemLogger ERROR: 	at javax.swing.DefaultListSelectionModel.changeSelection(DefaultListSelectionModel.java:415)
2022-12-31 15:36:28.800 SystemLogger ERROR: 	at javax.swing.DefaultListSelectionModel.setSelectionInterval(DefaultListSelectionModel.java:459)
2022-12-31 15:36:28.800 SystemLogger ERROR: 	at javax.swing.JTable.changeSelectionModel(JTable.java:2392)
2022-12-31 15:36:28.800 SystemLogger ERROR: 	at javax.swing.JTable.changeSelection(JTable.java:2461)
2022-12-31 15:36:28.800 SystemLogger ERROR: 	at javax.swing.plaf.basic.BasicTableUI$Handler.adjustSelection(BasicTableUI.java:1115)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at javax.swing.plaf.basic.BasicTableUI$Handler.mousePressed(BasicTableUI.java:1038)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:280)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.Component.processMouseEvent(Component.java:6536)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.Component.processEvent(Component.java:6304)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.Container.processEvent(Container.java:2239)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.Component.dispatchEventImpl(Component.java:4889)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.Container.dispatchEventImpl(Container.java:2297)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.Component.dispatchEvent(Component.java:4711)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4532)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.Container.dispatchEventImpl(Container.java:2283)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.Component.dispatchEvent(Component.java:4711)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.EventQueue.access$500(EventQueue.java:97)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.EventQueue$3.run(EventQueue.java:709)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.EventQueue$3.run(EventQueue.java:703)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.security.AccessController.doPrivileged(Native Method)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.EventQueue$4.run(EventQueue.java:733)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.EventQueue$4.run(EventQueue.java:731)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.security.AccessController.doPrivileged(Native Method)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at org.openpnp.gui.MainFrame$22.dispatchEvent(MainFrame.java:556)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
2022-12-31 15:36:28.801 SystemLogger ERROR: 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
...
```

Will play around more and report glitches if there are any. Gotta go now.

This feature is a great start into a ...

# ... Happy New Year! 🥳🥳🥳🥳

_Mark

**Comment by tonyluken** [comment]
Hi @markmaker,

I struggled to come up with a good name and I'm not particularly happy with Definable but I also haven't been able to come up with anything better. The classes that implement Definable are used to instantiate both 
objects that are definitions (in my terminology, the defining object) and to instantiate objects that are defined by those definitions (in my terminology, the defined object). The terms Prototype or Template don't really seem fit either - they would apply to what I call the defining object but not really to the defined objects. If you or anybody else has a better suggestion, I'm certainly willing to change it.

I fixed several of the dialogs so that they are now children of the mainframe. I left the PlacementsHolderLocationViewerDialog as an independent frame though because I think it is more useful that way (can be hidden, minimized, etc. when not in use). Clicking on the viewer icon just re-opens the window if it already exists.

I wasn't able to duplicate the exception you saw by clicking in the Board/Panel Id column cell. Although I did discover and fix a null pointer exception that occurred when clicking on any of the placement rows (was due to not having parts assigned to the placements). Let me know if you can still reproduce the original problem.

Happy New Year,
Tony

**Comment by markmaker** [comment]
Hi @tonyluken,

the "Definable" I leave to you English speaking guys. 🇨🇭 🇬🇧 🇺🇸

The exception still persists. This change fixes it:

```java
@@ -79,7 +79,7 @@ public class CustomPlacementsHolderRenderer extends JLabel implements TableCellR
             right.setBackground(row%2==0 ? table.getBackground() : alternateRowColor);
         }
 
-        String uniqueId = (String) value;
+        String uniqueId = (value == null ? "" : (String)value);
         String id = uniqueId.substring(uniqueId.lastIndexOf(PlacementsHolderLocation.ID_DELIMITTER)+1);
         int depth = 0;
         int idx = -1;
```
but I don't understand why `value` is null, and whether _that_ is OK.

To reproduce, just start with a fresh OpenPnP installation, then open the included (legacy) sample `pnp-test.job.xml`, then on the **Jobs** tab clicked on any board line, into the **Board/Panel Id** cell.

The dialogs are now properly parented, but they still appear anywhere on the monitor, i.e., not centered on the main window. Needle in the hay stack on my 43 inch 5k monitor 🥹. 

This seems to do the trick:

```java
@@ -157,6 +157,7 @@ public class ExistingBoardOrPanelDialog extends JDialog {
                 buttonPane.add(cancelButton);
             }
         }
+        setLocationRelativeTo(MainFrame.get());
     }
 
     public File getFile() {
```

_Mark

**Comment by tonyluken** [comment]
Hi @markmaker,

Ok, I never was able to duplicate your issue with the NPE in the CustomPlacementsHolderRenderer, but I checked its API and it does state that null is a valid input value so I added checks for that as you suggested.

The new dialogs should all now be properly centered in the MainFrame the first time they are opened.  And their size and position are remembered after that.

I also added a test of the new panelization to the test suite.

Tony

**Comment by markmaker** [comment]
Hi @tonyluken,

Am I right to assume this is ready?

I just wanted to air "something" that occurred to me, to make this change even much better. ☺ It may sound like a big change, but seeing that _conceptually_, you basically prepared everything for it, it might be easier to realize than it sounds. 

Hope you keep an open mind through reading this (and don't mistake it for criticism). 

I've seen you've perfectly made Panels and Boards polymorphic with the `PlacementHolder` base class. This is also nicely materialized in the Jobs view, where they appear polymorphically in the upper list, including the polymorphic `+` button sub-menu. 

I just wondered if the same could be done on the `Definable` side of things. Say you merge the upper lists of the Panel and Board tabs into one polymorphic list. And again make the `+` button sub-menu polymorphic. The new clean-up button would clean up both panels and boards in one sweep, which I assume is mostly what users want anyway (makes it simply Job related). 

Then also merge the two lower lists of the Panels and Boards tabs. As you've also made the `PlacementsHolderLocation` nicely polymorphic too, this should be doable, right? Just restrict/hardwire the placement type to `Fiducial` on panels.

Then keep the middle Children list as is (it is notably already polymorphic), but disable it when a board is selected in the upper list. 

As a result we just get _one_ tab for Panels _and_ Boards (that I would simply call "Panels"), which IMHO is easier to grasp and more convenient to use (no switching back and forth). By extending the polymorphism to the UX, it becomes clear that this is essentially a parent-child hierarchy editor (a bit like folders and files), and actions like adding or deleting are semantically the same whether it is a board or a panel. The UX naturally also becomes more similar to the fully polymorphic Machine Setup tab.

Merging the tabs also addresses some concerns that the UI would become too cluttered, especially for those that never use panels. 

Finally, you already wrote:

> Note that the legacy method of editing Boards directly in the Job tab is still supported but only if there is a single instance of the Board in the Job and it is at the top level of the Job,

Which is very cool! It basically allows existing users, and users who never want to use panels, to work very much as before, which obviously is also the most efficient way. I guess you realized that single board usage should not be made harder by the sheer presence of the panelizing feature. 

But there is still the ambiguity, affecting all existing and new OpenPnP users, namely that they don't understand, why suddenly the same board view appears twice, once in the Jobs and once in the Boards tab. I guess practically everybody will come back for support, asking _"Why is it duplicated? Where do I need to edit it? What's the difference?"_

Having the second board view under the "Panels" tab (and quite clearly a part of that parent-child relationship), makes this much clearer IMHO. Users that never use panels, i.e., just want to assemble single boards (as before), can simply ignore the new Panels tab altogether, which in itself has quite some merit, IMHO.

What do you think?

_Mark

**Comment by tonyluken** [comment]
Hi @markmaker,

>Am I right to assume this is ready?

Yes AFAIK.

Re: Merging the Boards Tab and the Panels Tab.  How do you propose it to work if there is more than one instance of a Board in a Job (that are not part of a Panel)? If the operator wants to edit the Board, they have to go to the Panels tab to do it? That doesn't make much sense to me.

Being able to edit a single Board on the Job tab is merely an antiquated way of doing things that we are supporting for convenience. In my mind, it's the support for that convenience, that causes the potential for confusion as to why a Board appears on the Job tab and on the Boards tab as well.  If we were to remove the ability to edit boards on the Job tab entirely, that would remove all potential for confusion - all editing of Boards would take place on the Boards tab. I've actually considered adding a switch to turn-off the ability to edit Boards on the Job tab as some have complained that it's too easy to accidentally make changes to a Board while working on the Job tab.

I think the important point to make to everybody is that a Job is a task, and the Job tab should be where that task is defined and executed (and not the primary place to edit Boards). On the other hand, Panels, Boards, Parts, and Packages are all physical things and their respective tabs are where they are defined and edited. Nobody seems to have any confusion as to why we have single copy of a Part on the Parts tab and yet can have one or more copies of that part on a single Board.

So, for now, I suggest we keep the separate Panels tab and Boards tab. We can always revisit this if it really generates a large swirl of confusion.  Besides, I think need to spend some time updating the Wiki rather than rewriting the code again.

Tony

**Comment by markmaker** [comment]
> Being able to edit a single Board on the Job tab is merely an antiquated way of doing things that we are supporting for convenience. In my mind, it's the support for that convenience, that causes the potential for confusion as to why a Board appears on the Job tab and on the Boards tab as well. If we were to remove the ability to edit boards on the Job tab entirely, that would remove all potential for confusion - all editing of Boards would take place on the Boards tab. ... **some have complained that it's too easy to accidentally make changes to a Board while working on the Job tab.**

Glad we talked about it. If you put it that way, I agree. But then I would argue to remove the editing capability on the Jobs tab immediately. Only then does the separate Boards tab make sense to those that don't ever assemble panels or multiple boards. 

I really believe the removal of that very obvious confusion is worth the remaining effort.

_Mark

**Comment by ian-arkver** [comment]
Mark, what's your schedule for pulling this into testing? I might try a merge in my local tree and test it, since it fixes the part-placed panel bug I've hit.

**Comment by ian-arkver** [comment]
Tried it, looks nice so far. I can confirm that changing placed status works per-board in the Job tab.

Re: editing boards in a panel - I can see a use-case where some editing in the Job tab might be needed, eg. where certain boards in a panel have different options (component value change, zero-ohm link options enabled/disabled).

Maybe this isn't a common use-case though, but let's say you're making a panel of I2C GPIO expander boards and you want some to be at one address, some at another, etc. The address may be set using placements of jumpers or pullup/down resistors. Or a panel of buck regulators where you want some with different output voltages - a component value change. You need to be able to change the assignments on the Job tab I think.

**Comment by markmaker** [comment]
>

**Comment by markmaker** [comment]
Sorry, wrong button pressed.

**Comment by ian-arkver** [comment]
Tony suggested "adding a switch to turn-off the ability to edit Boards on the Job tab" which would be a good compromise I think - enable editing to set per-instance tweaks if needed, then lock it down for the run.

**Comment by ian-arkver** [comment]
Actually, what I describe was never supported and falls into the realms of new feature request which probably has limited appeal.

"Note that the legacy method of editing Boards directly in the Job tab is still supported but only if there is a single instance of the Board in the Job and it is at the top level of the Job"

This doesn't cover per-instance customisation within a panel.

**Comment by markmaker** [comment]
> Editing this to add: Which tab will have the ability to modify the placed status for an individual board in a panel? Let's not delete that capability please.

As far as I understand, the placement Enabled, Placed, Status and Error Handling etc. are now always properly managed in the placement _instance_ (some copied from the _definition_, some solely in the _instance_).

I first thought, that position data (X, Y, Rot) should not at all be editable in the Jobs tab anymore. But then it occurred to me that there may still be users out there that don't use E-CAD import and _capture_ placement positions one by one, manually:

Capture placement positions

As the board _definition_ does not have a reference position/orientation itself, capturing isn't possible in the Boards tab. So it follows that the current dual behavior is still valid, useful and required. The system also nicely disables the capture buttons, along with the interaction in table cells, as soon as more than one board instance is in the Job. 

So I finally agree wholly with Tony that this is the best solution. Took some thinking ... 🐌

@ian-arkver, I doubt it is really useful to change the Part in a single _instance_ of a placement. The first scenario that you mentioned (zero ohm jumpers), can be done by simply enabling/disabling the jumper in the placement _instance_. Setting the Enabled different from the _definition_ works flawlessly. And btw. setting Enabled on the _definition_ nicely resets all _instances_ (may need to toggle twice to reset back to the original state).

@tonyluken, one minor inconsistency (can be fixed later): the context menu **Set Enabled** and **Set Error Handling** in the Boards tab do not propagate to _instances_ where the _definition_ is already in the wanted state. The easiest fix would likely be to toggle twice. Fixing would be useful for multi-selection with mixed prior states.

However, I believe this is ready for merge into `test` now, fixes can be applied later, along with an entry to the `CHANGES.md`, please. 

@tonyluken, thanks for a great feature ... and for being patient with my thought process so slowly catching up. 🐌🐌🐌

_Mark

**Comment by ian-arkver** [comment]
Different component values per instance can be achieved by duplicating the placement in the board then enabling only one of them in the instance. A "Copy placement" option in the board editor might be handy for this, but as you say it's a very unlikely scenario and there's currently no user demand for it afaik.

Thanks for all the hard work on this improved panelization.

**Comment by tonyluken** [comment]
If someone wants different component values on different Boards, to me, those **are** different Boards.  They can easily create copies of a Board (naming them differently) on the Boards tab and modify the component values there and then define a Panel on the Panels tab that uses those different Boards. I think that is much clearer because it is then obvious that the boards really are different.

**Comment by noeldum** [comment]
Brilliant job here Tony! You kept it simple and implemented exactly all we need. Superb.

Thank you for the 'use children fiducial' button in the panel definition tab. I had this in mind but never dared reporting it considering the bad state it was in I though I'd rather just report what's essential first.
I seriously had a big 'yes this is it!' moment when seeing the feature was in here.

In my opinion all this should be moved to the standard package. There is more risk in keeping the old panelisation version than pushing this one forward. The old version is really one of the worst hair pulling and head banging interface I came across.

**Comment by markmaker** [comment]
Hi @tonyluken 

can we tick off all the items in the Description?

Does this automatically close the linked Issues? 

(I don't know Github that well).

_Mark

**Comment by tonyluken** [comment]
Hi @markmaker,

>can we tick off all the items in the Description?

I think so but you may want to ping the OP of each item to see if they concur.

>Does this automatically close the linked Issues?

I don't know either. It may just a comment or something to the issue. I guess it's worth giving it a try.

Tony

**Comment by atanisoft** [comment]
> Does this automatically close the linked Issues?

normally that will only be done if the description of the PR or a commit references the issue as "fixes: XXXX" or similar.

**Pull request merged**
