### PR TITLE
Default bottom vision pipeline inaccuracy due to contour thickness

### PR DESCRIPTION
**Pull request by tobydickenson**
# Description

The default bottom vision pipeline operates by
* using thresholds to find  some interesting shapes
* finding contours for those shapes
* eliminating some contours where the area is too small to be interesting
* drawing the outline of those contours to recreate the shapes

The current pipeline redraws the contours using a line thickness of 2 pixels, which artificially inflates the shapes. This leads to a (small) inaccuracy in component size and position.

It is better to redraw the contours with a line thickness of 1 pixel, to accurately reproduce the original shapes and eliminate this unexpected inaccuracy.

Note this affects the line thickness used during the vision pipeline processing. A different line thickness is used for user feedback.

# Justification
Openpnp aims for sub-pixel accuracy elsewhere.

# Implementation Details
1. How did you test the change? - Tested on the machine today.
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? - yes
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted. - tests pass

### CODE REVIEW

**Comment by tobydickenson** [comment]
This is ready for merge

**Comment by markmaker** [comment]
Thanks, @tobydickenson,

could you please check the other pipelines? 

https://github.com/openpnp/openpnp/tree/cc0b51432c834c6c91c5cfb2ddddab2c6a89ba77/src/main/resources/org/openpnp/machine/reference/vision

At least the "Body" pipeline also has the same stage.

_Mark

**Comment by tobydickenson** [comment]
Yes, "Body" was the only other one

**Comment by markmaker** [comment]
:+1:

**Comment by tobydickenson** [comment]
Thank you

**Pull request merged**
