### PR TITLE
Improvements for BottomVision Calibration (issue #235)

### PR DESCRIPTION
**Pull request by ldpgh**
# Description
- Improvement/Fix for BottomVision Calibration (issue #235)
   - Enable BottomVision Calibration
   - Add parameteres (machine.xml) for hardcoded numbers (eg. rotation limits)
   - new  Parameters (machine.xml):
      - angleAverage ... 1 ... means no averaging.
      - angleStart ... 0.0
      - angleStop ... 360.0
      - angleIncrement ... 15.0
   - All new parameters are initialized by the previous hardcoded values. 
   - Show 0degree  measurement in new fields next to the calibrate button
   - add findCircleAveraged(int avg) around findCircle() in case of difficult light conditions
- Implement issue #784 

# Justification
At least in my setup it seems to be working and brings my DebugNozzle-tip (1.5mm runout) back to an error of 0.1mm after changing the nozzle-tip with the tool-changer.

# Instructions for Use
Shall work as designed before pluse some parameters in machine.xml.

# Implementation Details
0. Detailed change list is the commit comment 6ed5881 ... sorted by line numbers
1. How did you test the change? Be descriptive. Untested code will not be accepted.
   - MyTestProcedure-1:
      - Set Reticle/Fiducial and Reticle/Options/size=nozzleTip outer diameter
      - Run the Calibration
      - Go to BottomCamera and jog C for (angleStart->angleStop by angleIncrement) ... nozzle-tip should be within/close to the Fiducial
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)?
Tried my best. Be aware of a space/tab respective line-ending issue affecting the entire file.
3.  `org.openpnp.spi` or `org.openpnp.model` packages no touched
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted.
   - run 13/13 ... 0 errors ... 0 failures

### CODE REVIEW

**Comment by mgrl** [comment]
Have you tested how well the nozzle tip is aligned over the camera if you rotate the nozzle? In the test procedure you applied you mentioned that the nozzle tip is within an reticle after calibration - but whats with rotation? will it remain within there?

**Comment by ldpgh** [comment]
> Have you tested how well the nozzle tip is aligned over the camera if you rotate the nozzle? In the test procedure you applied you mentioned that the nozzle tip is within an reticle after calibration - but whats with rotation? 
... within the fiducial and size of the fiducial is set to the nozzle tip diameter (d_tip_outer=1.27mm)

... rotation ... This is meant by "Go to BottomCamera and jog C for (angleStart->angleStop by angleIncrement) ... should be within/close to the Fiducial".

Running an assembly job is pending.

> will it remain within there?
My machine is a pretty wiggle one. Error is about 0.1mm as mentioned [above](https://github.com/openpnp/openpnp/pull/803#issue-244305349)

**Comment by ldpgh** [comment]
[changes](https://github.com/openpnp/openpnp/pull/803#commits-pushed-f7dac6b) fix the issue with "file-diff" and renames variables to pass Travis-CI.

Still untested on the machine ... do NOT accept the PR for now.

**Comment by netzmark** [comment]
Hi Michael,

I have loaded your code, I still have lightning problem and need change it manually, but final effect looks good:-).
I have found something strange, maybe bug.
Do you use Visial homing? I guess that not.
Strange effect is only after the openpnp is started. After mechanical homing the system goes to callibrate the nozzles first and after this performs visual homing. Should be rather mechanical+visual+nozzles_calib, isn't it?

Sure, theoreticaly it's possible that I have screwed something up integrating your code to my one, but I rather don't think so. Pls check it if you can.

regards/Marek

**Comment by netzmark** [comment]
Sorry @ldpgh, I should write it in #804 but I hope Michael read it too.

**Comment by mgrl** [comment]
Yes I use visual homing. Calibration happens automatically at the first 
move after visual homing.

We didn't change any code that modifies the behaviour when a calibration 
is needed (I guess we will need to look into that later).

do you some repositioning to the visual home-place via scripts or 
something? if you exclusively move the camera no calibration should 
happen - if you move a tool it happens.

**Comment by mgrl** [comment]
I tried to integrate both algorithms but the way I do it with my limited java capabilities makes it quite messy.

Why has your machine only +-90° nozzles? That's the only case, that my algorithm can't handle since the kasa fit works better for full circles...

**Comment by mgrl** [comment]
@ldpgh please see #804 for the new implementation. I have made both algorithms coexist. The only function I left out until now is averaging. Did you have success with your pipeline to get it stable? For me averaging was not needed any more then. 
Apart from that, let me know whether you can live with #804 or you miss something?

**Comment by vonnieda** [comment]
Hi @ldpgh and @mgrl: Does #804 now completely replace this one? Can we close this, or are you wanting both to be merged?

**Comment by mgrl** [comment]
From my point of view #804 has all features of this PR included and can be perfectly used by @ldpgh, too. What didn't work we elaborated on last week to fix

**Pull request closed without merging**
