### PR TITLE
Update DlgAutoPanelize.java

### PR DESCRIPTION
**Pull request by cri-s**
drop down fix.

# Read This First
To submit a Pull Request for OpenPnP you must use this template or it will not be accepted. 

Be sure to review the [Developers Guide](https://github.com/openpnp/openpnp/wiki/Developers-Guide)
and the [Contributing Guidelines](https://github.com/openpnp/openpnp/blob/develop/CONTRIBUTING.md).

Make your Pull Request as small as possible. Only include one bug or feature.
Large pull requests that change dozens of files or add multiple features are unlikely to be accepted.

Fill out all the details below. All sections below are required. If they are not included your Pull Request
will not be accepted.

-----------------------------------------------------------------------

# Description
Describe the change in detail. Explain how it works. The better you describe the change the more likely it is to be accepted.

# Justification
Why should this change be included in OpenPnP? Does it benefit a majority of users or is it specific to one type of user or machine? Machine specific or highly individual code will not be accepted.

# Instructions for Use
How does someone use the feature? Be descriptive. Include step by step instructions. If this is a new feature then these instructions will become the Wiki documentation for the feature, so explain here the same way you would explain to someone who had never used the feature.

This is documentation for a user, not for a developer.

# Implementation Details
1. How did you test the change? Be descriptive. Untested code will not be accepted.
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)?
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing.
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted.

### CODE REVIEW

**Comment by vonnieda** [comment]
Thanks @cri-s! I've incorporated the primary changes in https://github.com/openpnp/openpnp/commit/92465bf4e4df7c61201fd299a6b1d1c55699eafd and we'll see if this fixes the problem. I have not tested on Windows yet. I did not include some of the other code that was less important since it changes the storage model of the dialog.

**Comment by vonnieda** [comment]
@BendRocks Looks like we may have a fix here. It's been pushed and will wait for feedback.

**Comment by BendRocks** [comment]
@vonnieda , confirmed this fixes on windows. 

For future reference:

There are 3 lines in the commit, but the 'setlightweightpopupenabled' line does the magic.. 

Most curious is there are jcombobox throughout the code and they all work on windows. This is the only place the setlightweightpopupenabled is needed.

I wonder why that is?

In any case, @cri-s, I'm glad you were able to fix this. I'd not have hit on the fix in hours and hours of trying.

**Comment by vonnieda** [comment]
I commented as the reason in #601. In general, it's not a good idea to use the heavy weight components in a Swing app since it can cause graphics issues, but this is a good solution for now. If it turns out to cause problems later we'll face that when it happens. Thanks again @cri-s!

**Comment by vonnieda** [comment]
@cri-s To your comment in the code regarding 1000 parts: Of course, I don't want there to be 1000+ parts in the dropdown, but adding in a hardcoded filter that no one knows about is not the answer, either. We have no guarantee that every user uses "fid" in their fiducials, and this changes the behavior of the fid dropdown in one place but nowhere else, which makes the code inconsistent.

A good solution to this, and to part selection in general, would be to make the part selection dropdown a searchable combobox instead. Then the user can easily start to type "FID" and get just the parts containing that name. This would improve part selection throughout the system.

I appreciate your help, but please stop with the rudeness and acting like I'm out to get you. I have been completely respectful to you in our interactions over the years, and I would appreciate the same from you.

**Pull request closed without merging**
