### PR TITLE
Feature/improve nozzle tip calibration

### PR DESCRIPTION
**Pull request by tonyluken**
# Description
Fixed a bug in nozzle tip calibration that could, in some cases, cause the runout error to double rather than being canceled.  Also added a new technique for nozzle tip calibration based on affine transforms which should be more robust to measurement outliers.

A couple of small changes were also made to the calibration process:

1. When the pipeline returns more than one result for a single measurement, instead of just picking the first result, which may be erroneous (and logging a message that the user would only see if he knows to examine the logs), it now rejects all the results for that measurement and counts it as a misdetection (which will cause an error to be thrown if too many misdetects occur).
2.  Instead of waiting until all measurements are taken before checking for too many misdetects, it now checks after each measurement and throws the error as soon as the misdetect threshold is crossed.

# Justification
Improves placement accuracy

# Instructions for Use
No special instructions for the bug fix.  To use the new nozzle tip calibration technique, edit machine.xml and replace all occurrances of:
       runout-compensation-algorithm="ModelCameraOffset"
with:
       runout-compensation-algorithm="ModelCameraOffsetAffine"

# Implementation Details
**1. How did you test the change?** Tested the bug fix by duplicating the conditions under which it would occur (phase shifts near 180 degrees) and verified that it now handles the condition correctly.  The new technique was tested in simulation as well as run it on a real machine  to verify comparable or better results than with the original technique.
**2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)?**  Yes.
**3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing.**  No changes were made to these packages
**4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted.**  Maven tests were run and passed.

### CODE REVIEW

**Comment by markmaker** [comment]
Hi Tony

Questions/Suggestions (these are more of the "icing on the top of an already excellent cake" variety): 

1. Why not make it a new `ReferenceNozzleTipCalibration.RunoutCompensation` (sub-) class like the others?
2. You could then also override the `toString()` to provide extra "affine" info to the user, and/or the `estimateModelError`, you implemented. If I'm not mistaken, this should more or less be an indicator for the quality of one's pipeline, as there is hardly any real physical error to be expected (on a magnitude that is detectable), right? Would be valuable. 
3. And while you're at it, adding the phase shift (to KASA too) would be useful, so testers (aka myself) can compare the two without digging in the log. :-)
4. Finally, why not use the class in the camera calibration (instead of more or less duplicating the code)?

_Mark

**Comment by tonyluken** [comment]
Mark,  thanks for the comments...

1. I didn't make a new sub-class because this is exactly the same model - it only provides a different way to initialize the model and so it seemed (at least to me) more appropriate to just provide another constructor for the already existing class and subclasses.
2. The affine transform would have to be made a persistent part of the model and there is really no need for that once the model's parameters are initialized (other than if one wants to access it in the toString method).  I agree that it makes sense for the estimated peak and rms errors to be part of the model and I'll add getter methods for them.
3.  Agreed, the toString methods should also show the phase shift (and estimated errors).
4.  As I stated in the forum discussion, I see no need to provide camera calibration for every nozzle tip. I'd like to pull the camera calibration part out of nozzle tip calibration and put it with the camera setup stuff where it belongs.  I believe this is a small step along that path. 

Tony

**Comment by vonnieda** [comment]
I'm going to defer to @markmaker on this one, as he has the most familiarity with the nozzle calibration code. @markmaker - do you have any further concerns here?

**Comment by markmaker** [comment]
Hi
I'll test this, as soon as possible. Would be easier for me _after_ #995 is merged (as planned). 
_Mark

**Comment by vonnieda** [comment]
Hi @markmaker - can you test this out when you have a chance? I'd like to get it merged soon if possible.

**Comment by markmaker** [comment]
Hi @tonyluken
Hi @vonnieda 

I've tested this on my machine, still with the old 0.2mm runout nozzle tip holder. Three different tips. Each with both methods. Just basic observations, no scientific trial. I was looking at the consistency between calibrations and also (as a sanity check) between the methods: 

1. Affine performs about the same with few measurements (I had 5 set for good speed). Similar results between the methods, similar consistency between multiple calibrations. 
2. For runout compensation alone, the choice seems not to matter, even with a slightly higher number of measurements like 6 or 7. 
3. For Camera calibration it was a bit strange: With only 5 measurements I had good streaks and bad streaks with both methods. First I thought Affine was much better, then it suddenly started having bad results too (correcting camera angle back and forth relatively strongly ~0.4°). I guess 5 measurements is not enough for this and the rest is good and bad luck.
4. If you increase the number of measurements for Camera calibration, Affine outperforms KASA in repeatability, while KASA somehow seems not to profit so much (I also still remember this from back when I last worked on it, I don't understand why that can be). Even ridiculously large numbers (30) seem to get better and better with Affine (though I haven't tested these large numbers with KASA). 
5. For higher measurement counts (12) in Camera Calibration, Affine can then achieve very low offsets in subsequent runout calibrations i.e. the Camera Calibration seems more precise and/or consistent with runout calibration. KASA never quite gets there. But these differences are mostly academic, we're talking maybe ~8µm vs. ~15µm (and I'm sure my machine will not keep this up elsewhere).  
6. For some reason Affine seems to consistently estimate my camera angle lower than KASA (~0.55° instead of ~0.85°). I want to believe Affine ;-)

Btw. I put the new Camera Settle to good use. Camera Calibration is running in a circle and the nozzle vibrates quite strongly _tangentially_. I found that reducing the settle threshold lowers the calibrated camera angle, i.e. the calibration was previously affected! Ideally we should probably move the nozzle via the center i.e. go _radially_ to the measurement locations, to cancel out any such effects. Or do the run twice, once clockwise, once counter-clockwise. But the adaptive Camera Settle worked flawlessly: it took ages to settle the strong Camera Calibration moves, but swiftly captured the normal (still) runout calibration. 

@tonyluken if @vonnieda agrees, I propose setting `ModelCameraOffsetAffine` as the new standard method and to add a @Commit handler to change existing configs. People can always go back through `machine.xml` if there was a hiccup. Otherwise, this fine feature will be left unused/untested. 

Furthermore, I think it is time to remove the "EXPERIMENTAL" tag in the Wizard. This is getting a bit old 
;-)

_Mark

**Comment by tonyluken** [comment]
Hi @markmaker,
Your results sound consistent with what I saw.  WRT camera calibration: I too noticed that the camera angle was consistently different between the two methods.  Another thing I noticed is that the camera angle (and offset) would be different for different size circles (excenterRatios).  I suspect camera projective errors to be the culprit but have no definitive proof of that.  On thing I want to do is mechanically readjust my camera alignment to make its focal plane parallel to my machine's bed.  I had originaly aligned it using the mirror trick to center the camera lens with the reticle but that left the camera tilted noticablely wrt the rest of the machine.  I believe that is causing a scaling error that changes with pixel location.  Sometime down the road, as part of camera calibration, it may be possible to compute a best fit projective transformation and apply its inverse to the images to correct for not only the position and rotation but also scaling and projection errors as well.

@vonnieda, Per Mark's recommendations I'll change the default setting to ModelCameraOffsetAffine, add the @Commit handler to change the existing configs, and remove the "EXPERIMENTAL" tag.

Tony

**Comment by tonyluken** [comment]
Ok, should be good to go.

**Comment by vonnieda** [comment]
Nice work @tonyluken - and thank you @markmaker for testing!

**Comment by markmaker** [comment]
Hi @tonyluken 

Just had a run-in with the new method. Tried to run it on the NullDriver. I guess the results can be **too good**.  First thought it's problem with my new code but I reproduced with `develop:`

Steps to reproduce:

1. Exit OpenPnP, move `machine.xml` aside.
2. Restart OpenPnP to get the Null Driver simulation.
3. Go to the Nozzle Tip/Calibration, Enable it, Apply.
4. Press the Nozzle icon button. 
5. Edit pipeline, fix the Hough Circle diameters max=90, min=70, test with refresh Button, close.
6. Run Calibration. So far OK,
7. Run Bottom Camera Calibration. 
8. Run Calibration again.

Nozzle vanishes. NaN rules. :-)

KASA seems less intimidated.

_Mark

```
2020-05-12 19:29:30.257 ReferenceNozzleTipCalibration TRACE: [nozzleTipCalibration]measured offset: (-0.013438, 0.006719, 0.000000, 120.000000 mm)
2020-05-12 19:29:30.257 Scripting TRACE: Scripting.on NozzleCalibration.Finished
2020-05-12 19:29:30.258 ReferenceNozzleTipCalibration$ModelBasedRunoutCompensation TRACE: [nozzleTipCalibration]nozzle tip affine transform = scale (0.000000, -0.000000) shear (8165619676597685.000000, 0.0) rotation (180.000000 deg) translation (-0.008958 mm, 0.006719 mm)
2020-05-12 19:29:30.258 ReferenceNozzleTipCalibration$ModelBasedRunoutCompensation TRACE: [nozzleTipCalibration]compare measured = (0.000000, 0.006719, 0.000000, -180.000000 mm), modeled = (NaN, NaN, 0.000000, 0.000000 mm)
2020-05-12 19:29:30.258 ReferenceNozzleTipCalibration$ModelBasedRunoutCompensation TRACE: [nozzleTipCalibration]compare measured = (-0.013438, 0.006719, 0.000000, -120.000000 mm), modeled = (NaN, NaN, 0.000000, 0.000000 mm)
2020-05-12 19:29:30.258 ReferenceNozzleTipCalibration$ModelBasedRunoutCompensation TRACE: [nozzleTipCalibration]compare measured = (-0.013438, 0.006719, 0.000000, -60.000000 mm), modeled = (NaN, NaN, 0.000000, 0.000000 mm)
2020-05-12 19:29:30.258 ReferenceNozzleTipCalibration$ModelBasedRunoutCompensation TRACE: [nozzleTipCalibration]compare measured = (0.000000, 0.006719, 0.000000, 0.000000 mm), modeled = (NaN, NaN, 0.000000, 0.000000 mm)
2020-05-12 19:29:30.258 ReferenceNozzleTipCalibration$ModelBasedRunoutCompensation TRACE: [nozzleTipCalibration]compare measured = (-0.013438, 0.006719, 0.000000, 60.000000 mm), modeled = (NaN, NaN, 0.000000, 0.000000 mm)
2020-05-12 19:29:30.258 ReferenceNozzleTipCalibration$ModelBasedRunoutCompensation TRACE: [nozzleTipCalibration]compare measured = (-0.013438, 0.006719, 0.000000, 120.000000 mm), modeled = (NaN, NaN, 0.000000, 0.000000 mm)
2020-05-12 19:29:30.258 ReferenceNozzleTipCalibration$ModelBasedRunoutCompensation TRACE: [nozzleTipCalibration]peak error location = (0.000000, 0.000000, 0.000000, 0.000000 mm), error = 0.0
2020-05-12 19:29:30.258 ReferenceNozzleTipCalibration$ModelBasedRunoutCompensation DEBUG: [nozzleTipCalibration]calculated nozzleEccentricity: Camera position offset -0.009, 0.007, Runout NaN, Phase -180.000, Peak err 0.000, RMS err NaN mm
2020-05-12 19:29:30.258 ReferenceNozzleTipCalibration$ModelBasedRunoutCameraOffsetCompensation DEBUG: [nozzleTipCalibration] getCameraOffset() returns: -0.008958333333333332, 0.00671875
2020-05-12 19:29:30.258 ReferenceNozzle DEBUG: N1.moveTo((NaN, NaN, 0.000000, -180.000000 mm), 1.0) (runout compensation: (NaN, NaN, 0.000000, 0.000000 mm))
2020-05-12 19:29:30.258 NullDriver DEBUG: moveTo(N1 N1, (NaN, NaN, 0.000000, -180.000000 mm), 1.0)
2020-05-12 19:29:30.359 ReferenceNozzle DEBUG: N1.moveToSafeZ(1.0)
2020-05-12 19:29:30.359 NullDriver DEBUG: moveTo(N1 N1, (NaN, NaN, 0.000000, NaN mm), 1.0)
```

**Comment by tonyluken** [comment]
Hey @markmaker,

When I first looked at your results I thought I knew where the problem was but strangely when I run your exact same scenario I get different results.  I suspect it may be due to the particular hardware plaform on which it is run but I'm not sure.
Anyway, my first thought was that the problem was due to you getting a slightly positive x scale and a slightly negitive y scale as evidenced here: **nozzle tip affine transform = scale (0.000000, -0.000000)**.  The runout radius is computed from the geometric mean of those and since one is negative, the result is a NaN and that would explain all the rest of the NaNs.  Normally these are both positive so I was going to fix this by just taking the absolute value before taking the square root.  On my machine I get exactly 0 for both scale factors (and NaN for shear instead of a very large number) so I get a runout radius of exactly 0 whereas you get a NaN.
I was ready to chalk this up to numerical precision differences on different hardware platforms but then I noticed that your measured values also looked strange.  When I run this, all my measured values are the same regardless of the angle: **compare measured = (-0.013438, 0.006719, ...** but you get different values at -180 and 0 degrees.  That I don't understand.
If you have the time, could you change line 190 of NozzleTipCalibration.java from:
`            this.radius = new Length( Math.sqrt(ai.xScale * ai.yScale),
`
to:
`            this.radius = new Length( Math.sqrt(Math.abs(ai.xScale * ai.yScale)),
`
to see what happens?

Tony

**Comment by tonyluken** [comment]
@markmaker,

I'll go ahead as submit a PR for this although I'm still puzzled by the results you got where your measured loctions are not all the same.  I assume with the NullDriver and everything simulated, the nozzle tip really has zero runout so why are your measurements at -180 and 0 degrees different than your measurements at the other angles?  Those measurements shouldn't have anything to do with KASA or affine transforms.  When I run this, all my measurements are the same and match yours other than at -180 and 0 degrees.

Tony

**Comment by markmaker** [comment]
@tonyluken 

First: it is clear that the drawn/simulated nozzle has an offset. Do you see the same? That may come from an asymmetric `int` color rounding of my graphics driver's anti-aliasing or from `int` pixel coordinate rounding or whatever. So this is a potential source of "noise".

Then we are applying the `excenter `here: 
```
                // rotate nozzle to measurement angle
                Location measureLocation = measureBaseLocation
                        .derive(null, null, null, measureAngle)
                        .add(excenter.rotateXy(measureAngle));
```

The `excenter `should be zero in theory, but in IEEE this might be a -0, tipping over some of the above-mentioned `int` rounding perhaps. 

Below is the full log and you see everything is in order for the moves (to the decimal output rounding) but the measured offsets come back different anyway. 

**Whatever**: I guess you agree the method must be able to cope with **anything** thrown at it. ;-)

_Mark

```
2020-05-12 19:29:27.591 Scripting TRACE: Scripting.on NozzleCalibration.Starting
2020-05-12 19:29:27.592 ReferenceHead DEBUG: H1.moveToSafeZ(1.0)
2020-05-12 19:29:27.592 ReferenceNozzle DEBUG: N1.moveToSafeZ(1.0)
2020-05-12 19:29:27.592 NullDriver DEBUG: moveTo(N1 N1, (NaN, NaN, 0.000000, NaN mm), 1.0)
2020-05-12 19:29:27.592 ReferenceCamera DEBUG: Top.moveToSafeZ(1.0)
2020-05-12 19:29:27.592 NullDriver DEBUG: moveTo(Top, (NaN, NaN, 0.000000, NaN mm), 1.0)
2020-05-12 19:29:27.592 ReferenceActuator DEBUG: A1.moveToSafeZ(1.0)
2020-05-12 19:29:27.592 NullDriver DEBUG: moveTo(A1, (NaN, NaN, 0.000000, NaN mm), 1.0)
2020-05-12 19:29:27.592 ReferenceNozzle DEBUG: N1.moveTo((118.805719, 7.110278, 0.000000, -180.000000 mm), 1.0)
2020-05-12 19:29:27.592 NullDriver DEBUG: moveTo(N1 N1, (118.805719, 7.110278, 0.000000, -180.000000 mm), 1.0)
2020-05-12 19:29:27.692 ReferenceNozzle DEBUG: N1.moveTo((118.805719, 7.110278, 0.000000, -180.000000 mm), 1.0)
2020-05-12 19:29:27.692 NullDriver DEBUG: moveTo(N1 N1, (118.805719, 7.110278, 0.000000, -180.000000 mm), 1.0)
2020-05-12 19:29:27.692 ReferenceNozzleTipCalibration DEBUG: [nozzleTipCalibration]starting measurement; angleStart: -180.0, angleStop: 180.0, angleIncrement: 60.0, angleSubdivisions: 5
2020-05-12 19:29:27.692 ReferenceNozzleTipCalibration DEBUG: [nozzleTipCalibration]i: 0, measureAngle: -180.0
2020-05-12 19:29:27.692 ReferenceNozzle DEBUG: N1.moveTo((118.805719, 7.110278, 0.000000, -180.000000 mm), 1.0)
2020-05-12 19:29:27.692 NullDriver DEBUG: moveTo(N1 N1, (118.805719, 7.110278, 0.000000, -180.000000 mm), 1.0)
2020-05-12 19:29:27.696 Scripting TRACE: Scripting.on Camera.BeforeSettle
2020-05-12 19:29:27.946 Scripting TRACE: Scripting.on Camera.BeforeCapture
2020-05-12 19:29:27.954 Scripting TRACE: Scripting.on Camera.AfterCapture
2020-05-12 19:29:27.955 Scripting TRACE: Scripting.on Camera.AfterSettle
2020-05-12 19:29:28.026 ReferenceNozzleTipCalibration TRACE: [nozzleTipCalibration]measured offset: (0.000000, 0.006719, 0.000000, -180.000000 mm)
2020-05-12 19:29:28.026 ReferenceNozzleTipCalibration DEBUG: [nozzleTipCalibration]i: 1, measureAngle: -120.0
2020-05-12 19:29:28.026 ReferenceNozzle DEBUG: N1.moveTo((118.805719, 7.110278, 0.000000, -120.000000 mm), 1.0)
2020-05-12 19:29:28.026 NullDriver DEBUG: moveTo(N1 N1, (118.805719, 7.110278, 0.000000, -120.000000 mm), 1.0)
2020-05-12 19:29:28.126 Scripting TRACE: Scripting.on Camera.BeforeSettle
2020-05-12 19:29:28.377 Scripting TRACE: Scripting.on Camera.BeforeCapture
2020-05-12 19:29:28.385 Scripting TRACE: Scripting.on Camera.AfterCapture
2020-05-12 19:29:28.386 Scripting TRACE: Scripting.on Camera.AfterSettle
2020-05-12 19:29:28.472 ReferenceNozzleTipCalibration TRACE: [nozzleTipCalibration]measured offset: (-0.013438, 0.006719, 0.000000, -120.000000 mm)
2020-05-12 19:29:28.472 ReferenceNozzleTipCalibration DEBUG: [nozzleTipCalibration]i: 2, measureAngle: -60.0
2020-05-12 19:29:28.472 ReferenceNozzle DEBUG: N1.moveTo((118.805719, 7.110278, 0.000000, -60.000000 mm), 1.0)
2020-05-12 19:29:28.472 NullDriver DEBUG: moveTo(N1 N1, (118.805719, 7.110278, 0.000000, -60.000000 mm), 1.0)
2020-05-12 19:29:28.574 Scripting TRACE: Scripting.on Camera.BeforeSettle
2020-05-12 19:29:28.825 Scripting TRACE: Scripting.on Camera.BeforeCapture
2020-05-12 19:29:28.833 Scripting TRACE: Scripting.on Camera.AfterCapture
2020-05-12 19:29:28.834 Scripting TRACE: Scripting.on Camera.AfterSettle
2020-05-12 19:29:28.925 ReferenceNozzleTipCalibration TRACE: [nozzleTipCalibration]measured offset: (-0.013438, 0.006719, 0.000000, -60.000000 mm)
2020-05-12 19:29:28.925 ReferenceNozzleTipCalibration DEBUG: [nozzleTipCalibration]i: 3, measureAngle: 0.0
2020-05-12 19:29:28.925 ReferenceNozzle DEBUG: N1.moveTo((118.805719, 7.110278, 0.000000, 0.000000 mm), 1.0)
2020-05-12 19:29:28.925 NullDriver DEBUG: moveTo(N1 N1, (118.805719, 7.110278, 0.000000, 0.000000 mm), 1.0)
2020-05-12 19:29:29.026 Scripting TRACE: Scripting.on Camera.BeforeSettle
2020-05-12 19:29:29.277 Scripting TRACE: Scripting.on Camera.BeforeCapture
2020-05-12 19:29:29.288 Scripting TRACE: Scripting.on Camera.AfterCapture
2020-05-12 19:29:29.289 Scripting TRACE: Scripting.on Camera.AfterSettle
2020-05-12 19:29:29.376 ReferenceNozzleTipCalibration TRACE: [nozzleTipCalibration]measured offset: (0.000000, 0.006719, 0.000000, 0.000000 mm)
2020-05-12 19:29:29.376 ReferenceNozzleTipCalibration DEBUG: [nozzleTipCalibration]i: 4, measureAngle: 60.0
2020-05-12 19:29:29.376 ReferenceNozzle DEBUG: N1.moveTo((118.805719, 7.110278, 0.000000, 60.000000 mm), 1.0)
2020-05-12 19:29:29.376 NullDriver DEBUG: moveTo(N1 N1, (118.805719, 7.110278, 0.000000, 60.000000 mm), 1.0)
2020-05-12 19:29:29.477 Scripting TRACE: Scripting.on Camera.BeforeSettle
2020-05-12 19:29:29.729 Scripting TRACE: Scripting.on Camera.BeforeCapture
2020-05-12 19:29:29.737 Scripting TRACE: Scripting.on Camera.AfterCapture
2020-05-12 19:29:29.738 Scripting TRACE: Scripting.on Camera.AfterSettle
2020-05-12 19:29:29.825 ReferenceNozzleTipCalibration TRACE: [nozzleTipCalibration]measured offset: (-0.013438, 0.006719, 0.000000, 60.000000 mm)
2020-05-12 19:29:29.826 ReferenceNozzleTipCalibration DEBUG: [nozzleTipCalibration]i: 5, measureAngle: 120.0
2020-05-12 19:29:29.826 ReferenceNozzle DEBUG: N1.moveTo((118.805719, 7.110278, 0.000000, 120.000000 mm), 1.0)
2020-05-12 19:29:29.826 NullDriver DEBUG: moveTo(N1 N1, (118.805719, 7.110278, 0.000000, 120.000000 mm), 1.0)
2020-05-12 19:29:29.927 Scripting TRACE: Scripting.on Camera.BeforeSettle
2020-05-12 19:29:30.177 Scripting TRACE: Scripting.on Camera.BeforeCapture
2020-05-12 19:29:30.185 Scripting TRACE: Scripting.on Camera.AfterCapture
2020-05-12 19:29:30.185 Scripting TRACE: Scripting.on Camera.AfterSettle
2020-05-12 19:29:30.257 ReferenceNozzleTipCalibration TRACE: [nozzleTipCalibration]measured offset: (-0.013438, 0.006719, 0.000000, 120.000000 mm)
2020-05-12 19:29:30.257 Scripting TRACE: Scripting.on NozzleCalibration.Finished
2020-05-12 19:29:30.258 ReferenceNozzleTipCalibration$ModelBasedRunoutCompensation TRACE: [nozzleTipCalibration]nozzle tip affine transform = scale (0.000000, -0.000000) shear (8165619676597685.000000, 0.0) rotation (180.000000 deg) translation (-0.008958 mm, 0.006719 mm)
2020-05-12 19:29:30.258 ReferenceNozzleTipCalibration$ModelBasedRunoutCompensation TRACE: [nozzleTipCalibration]compare measured = (0.000000, 0.006719, 0.000000, -180.000000 mm), modeled = (NaN, NaN, 0.000000, 0.000000 mm)
2020-05-12 19:29:30.258 ReferenceNozzleTipCalibration$ModelBasedRunoutCompensation TRACE: [nozzleTipCalibration]compare measured = (-0.013438, 0.006719, 0.000000, -120.000000 mm), modeled = (NaN, NaN, 0.000000, 0.000000 mm)
2020-05-12 19:29:30.258 ReferenceNozzleTipCalibration$ModelBasedRunoutCompensation TRACE: [nozzleTipCalibration]compare measured = (-0.013438, 0.006719, 0.000000, -60.000000 mm), modeled = (NaN, NaN, 0.000000, 0.000000 mm)
2020-05-12 19:29:30.258 ReferenceNozzleTipCalibration$ModelBasedRunoutCompensation TRACE: [nozzleTipCalibration]compare measured = (0.000000, 0.006719, 0.000000, 0.000000 mm), modeled = (NaN, NaN, 0.000000, 0.000000 mm)
2020-05-12 19:29:30.258 ReferenceNozzleTipCalibration$ModelBasedRunoutCompensation TRACE: [nozzleTipCalibration]compare measured = (-0.013438, 0.006719, 0.000000, 60.000000 mm), modeled = (NaN, NaN, 0.000000, 0.000000 mm)
2020-05-12 19:29:30.258 ReferenceNozzleTipCalibration$ModelBasedRunoutCompensation TRACE: [nozzleTipCalibration]compare measured = (-0.013438, 0.006719, 0.000000, 120.000000 mm), modeled = (NaN, NaN, 0.000000, 0.000000 mm)
2020-05-12 19:29:30.258 ReferenceNozzleTipCalibration$ModelBasedRunoutCompensation TRACE: [nozzleTipCalibration]peak error location = (0.000000, 0.000000, 0.000000, 0.000000 mm), error = 0.0
2020-05-12 19:29:30.258 ReferenceNozzleTipCalibration$ModelBasedRunoutCompensation DEBUG: [nozzleTipCalibration]calculated nozzleEccentricity: Camera position offset -0.009, 0.007, Runout NaN, Phase -180.000, Peak err 0.000, RMS err NaN mm
2020-05-12 19:29:30.258 ReferenceNozzleTipCalibration$ModelBasedRunoutCameraOffsetCompensation DEBUG: [nozzleTipCalibration] getCameraOffset() returns: -0.008958333333333332, 0.00671875
2020-05-12 19:29:30.258 ReferenceNozzle DEBUG: N1.moveTo((NaN, NaN, 0.000000, -180.000000 mm), 1.0) (runout compensation: (NaN, NaN, 0.000000, 0.000000 mm))
2020-05-12 19:29:30.258 NullDriver DEBUG: moveTo(N1 N1, (NaN, NaN, 0.000000, -180.000000 mm), 1.0)
2020-05-12 19:29:30.359 ReferenceNozzle DEBUG: N1.moveToSafeZ(1.0)
2020-05-12 19:29:30.359 NullDriver DEBUG: moveTo(N1 N1, (NaN, NaN, 0.000000, NaN mm), 1.0)
```

_Mark

**Comment by tonyluken** [comment]
@markmaker 

Yes, I agree there is an offset - on my machine it appears to be a constant (-0.013438, 0.006719) but on yours it is not constant.  I find it hard to believe that differences in IEEE math on our two different machines could result in an x difference of 0.013438 millimeters but no (visible) y difference (and only for two of your measurments).  I'm worried that there is something wrong somewhere other than in the algorithm.  Why are your measurments so very much different than mine?

At -180 degrees you get (**0.000000**, 0.006719)  while I get (-0.013438, 0.006719)
At -120 degrees you get (-0.013438, 0.006719)  while I get (-0.013438, 0.006719)
At -60 degrees you get (-0.013438, 0.006719)  while I get (-0.013438, 0.006719)
At 0 degrees you get (**0.000000**, 0.006719)  while I get (-0.013438, 0.006719)
At 60 degrees you get (-0.013438, 0.006719)  while I get (-0.013438, 0.006719)
At 120 degrees you get (-0.013438, 0.006719)  while I get (-0.013438, 0.006719)

The measurements are taken **before** the affine or KASA algorithms are invoked so differences in the algorithm can't explain it.

Agreed that the algorithm should handle whatever is thrown at it and I'll fix that but I still think there may be another problem lurking somewhere.

Tony

**Comment by markmaker** [comment]
@tonyluken, have you read my possible explanation about different graphics drivers? Impossible?

The differences between our machines could also come from how many times you have calibrated the camera position. I have done it several times. But realize that with the NullDriver it doesn't actually work. The SimulatedUpCamera takes that same offset to generate its image, so rounding errors aside, any calibration is canceled out.  

But it still changes minimally due to rounding to `int`s when setting up the transform in the Graphics2D context (which goes into `int` based pixel coordinates). 

https://github.com/openpnp/openpnp/blob/37bfcb921aea0284fec571e41118fd6ee8c2aac2/src/main/java/org/openpnp/machine/reference/camera/SimulatedUpCamera.java#L130-L147

The resolution of the SimulatedUpCamera is rather coarse, so these tiny differences don't surprise me.

_Mark

**Comment by tonyluken** [comment]
@markmaker ,

Ok, I hadn't check the simulated camera resolution and now I see that it is only 0.0134375 so your measurements are jumping by only one pixel.  I was fooled because y seems to have better resolution than that (half pixel?) but I guess that is just some artifact of the graphics driver.  Anyway, I'll submit a PR to keep NaNs from being generated if this (or a similar) condition occurs.

Tony

**Pull request merged**
