### PR TITLE
UI translation improvements (continuation of the PR #1498 )

### PR DESCRIPTION
**Pull request by VSSavin**
This PR is a continuation of the PR #1496 and #1498. Branches were merged incorrectly in the previous PR. I fixed this.

# Description
* The 'Translations' class has been changed. Added and used `static class UTF8Control extends ResourceBundle.Control` to use UTF8 encoding directly in editors for .properties files.
* Everywhere if necessary was used the method 'Translations.getString' in the code for UI translations. For example, the code `new JLabel("Search");` has been changed to `new JLabel(Translations.getStringt("FeedersPanel.SearchLabel.text"));`
* Also, after using the 'UTF8Control' class we can't use https://github.com/jcbvm/i18n-editor to read/write translation files properly because it  doesn't support UTF-8 directly. To solve this problem I forked sources to https://github.com/VSSavin/i18n-editor and made some fixes (you can now choose the encoding in the 'Settings' menu). Now we have to use it. 

# Justification
This change improves UI translations.

# Instructions for Use
No change.

# Implementation Details
1. Manual UI testing.
2. Did follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)
3. There are some changes in `org.openpnp.spi` and `org.openpnp.model` packages. All changes  affect only 'name' and 'short description' of Actions (like 'deleteAction', 'permutateUpAction' etc.). For example `putValue(SHORT_DESCRIPTION, Translations.getString("AbstractAxis.Action.Delete.Description"));`
4. Successful mvn test before submitting the Pull Request.

### CODE REVIEW

**Comment by markmaker** [comment]
Hi @VSSavin,

again thanks for the huge work. 👍 

I found some missing tooltips, just in case you missed these. Note, I'm _not_ complaining, your coverage is already superb! 

Just to make sure: Have you also **tested** in Eclipse with "Externalize Strings" and "Window Builder" as discussed [here](https://github.com/openpnp/openpnp/pull/1496#issuecomment-1326542566) and [here](https://github.com/openpnp/openpnp/pull/1496#issuecomment-1325561555)?

_Mark

**Comment by ian-arkver** [comment]
Commit chain looks clean now and on the right branch. Good work!

**Comment by markmaker** [comment]
Hi @VSSavin,

I'm trying it and found this tab title missing:

image

Also, while the translations are nicely mapped now (good work!), UTF-8 does not seem to work in the Eclipse editor:

Eclipse

Also in WindowBuilder:

Window Builder

But it _does_ seem to recognize the class as the source:

image

I know this is a bit cheeky to ask at this stage, but do we really need UTF-8 after all? I mean the editor support in Eclipse seems nice GUI wise, and it will write the Strings back for us so it does not really matter if they are stored in UTF-8 or not. Plus I'm sure we could machine-convert the existing _valuable (!!)_ translation files into the normal `\uXXXX` form.

_Mark

**Comment by vonnieda** [comment]
I will step in here and say yes, we need UTF-8. 

If the editor you are using does not support UTF-8, you should endeavor to make sure it does. In Eclipse this is hard, because foolishly they respect the default Java platform setting or something. I went down the route of making Eclipse UTF-8 aware years and years ago, but I don't remember what the answer was and I don't use Eclipse any more. If you are interested, look in the git history for when I changed the encoding in the pom.xml.

Not being able to read the translation files without a tool really sucks. It makes diffs miserable and means anyone interested in contributing needs to use the tools to even see what they are working on. If we switch to UTF-8 someone could just edit these in place on Github with a few clicks.

When I introduced the i18 editor it was a workaround for the complexity of the key naming and to give people the ability to use Unicode characters where we couldn't support it directly. Now we can support it directly, and we should.

As I mentioned in a previous comment, I think part of this PR should be converting the old files to UTF-8. This should be possible with a couple line Java program.

Jason

**Comment by markmaker** [comment]
> Not being able to read the translation files without a tool really sucks. It makes diffs miserable and means anyone interested in contributing needs to use the tools to even see what they are working on. If we switch to UTF-8 someone could just edit these in place on Github with a few clicks.

OK, I understand.

But I doubt it is actually specific to Eclipse (or it to blame). An online search seems to confirm it is simply the Java 8 standard way.

### Possible Solution

By abandoning Java 8, I guess there is a way:

- https://docs.oracle.com/javase/9/intl/internationalization-enhancements-jdk-9.htm#JSINT-GUID-5ED91AA9-B2E3-4E05-8E99-6A009D2B36AF
- https://docs.oracle.com/javase/7/docs/technotes/tools/solaris/native2ascii.html

### Eclipse
- https://stackoverflow.com/questions/9180981/how-to-support-utf-8-encoding-in-eclipse
- https://stijndewitt.com/2010/05/05/unicode-utf-8-in-eclipse-java/

> #### Change your project settings
> When this is done, check your project settings.
> Select your project and open the Project Properties:
> <main menu> -> Project -> Properties
>
> If you will be sharing your project with others, you run the risk of them having forgotten to set their workspace settings correct and introducing wrongly encoded files into your project when they create new files. So to be safe, it might be smart to set your project settings to “Other: UTF-8” instead of “Inherited fromc ontainer”, because these project settings will be shared along with the project and the workspace settings are not.
>
> Screenshot of the Resource section of the Project Properties dialog in Eclipse IDE
>
> _Project Properties -> Resource_

### See also
- https://stackoverflow.com/questions/4659929/how-to-use-utf-8-in-resource-properties-with-resourcebundle
- https://stackoverflow.com/questions/53412992/using-utf-8-in-jtwig-with-translation-property-files
- https://brodowsky.it-sky.net/2018/02/02/java-properties-files-and-utf-8/

_Mark

**Comment by vonnieda** [comment]
The reason it is specific to Eclipse, or at least *was* many years ago, is that Eclipse would only (again, at the time) edit in the system encoding, and the only way to change it was to change the startup command line parameters in the Eclipse.ini, or something. Again, it's been many years and honestly it's not worth digging in to. Now we have modern editors, modern Unicode support in nearly everything, and UTF-8 supported universally across operating systems and computers. 

Given what I am seeing in the screenshot, I'd guess it's just not loading the escaped characters properly? Won't this be fixed if we convert all the files to UTF-8?

**Comment by markmaker** [comment]
One step further...

When I set `UTF-8` in Eclipse here, the `ru` file actually works!

UTF-8 setting

WindowBuilder:

WindowBuilder

Externalize strings:

All strings

Source text:

image

So I guess it is solvable.

The project _Resource_ settings are already set to `UTF-8`, but this seems to be ignored by Eclipse:

image

So we need to add this step (see first screen shot at the top) in the Wiki here:

https://github.com/openpnp/openpnp/wiki/Getting-Started-with-Eclipse

> ... honestly it's not worth digging in to. Now we have modern editors, modern Unicode support in nearly everything, and UTF-8 supported universally across operating systems and computers.

What I'm perhaps missing here, is how we could continue _without_ Eclipse, or more specifically _without_ WindowBuilder. Are there other IDEs supporting Swing in that form, as it was generated by WindowBuilder? One thing I can say for sure: this code is not maintainable without such a graphical tool. The "form" layout especially, uses such cryptic code, it is hardly human readable, and impossible to hand edit. I'm afraid, this is _not_ modern HTML+CSS 😉!

> Given what I am seeing in the screenshot, I'd guess it's just not loading the escaped characters properly? Won't this be fixed if we convert all the files to UTF-8?

As you see in the "Externalize strings" dialog (screen shot above), the `(default)`, `de`, `it`, `ru`, and `zh_CN` property files _seem already_ converted into UTF-8, but `es`, `fr` seem not. 

 @VSSavin, please convert these using the [native2ascii](https://docs.oracle.com/javase/7/docs/technotes/tools/solaris/native2ascii.html) Java tool.

_Mark

**Comment by VSSavin** [comment]
> Hi @VSSavin,
> 
> I'm trying it and found this tab title missing:
> 

@markmaker, Fixed missing translation keys

@markmaker, @vonnieda 
Translation files have been converted

**Comment by markmaker** [comment]
Hi @VSSavin, @vonnieda,

As far as I can tell, this is now fully functional. I tested WindowBuilder, added some new translations in German etc. and it all worked as it should. 

Again, in Eclipse one must absolutely set Windows / Preferences / General / Content Type / Text / Java Properties File / Default encoding = `UTF-8`:

UTF-8 setting

I've already added this to the Wiki:

https://github.com/openpnp/openpnp/wiki/Getting-Started-with-Eclipse#java-properties-encoding-in-utf-8

I think we can merge this. Great work, @VSSavin! Propose to "Squash and merge" so it is fused into one single commit. 

@vonnieda, do you agree?

_Mark

**Comment by vonnieda** [comment]
Looks great to me! Thanks @VSSavin for taking on such a huge task, and everyone else for helping get this merged. Nice work!

**Comment by markmaker** [comment]
@VSSavin,

could you make a small announcement on the discussion list, so everybody would be informed of the new `ru` translation, and be alerted to the underlying changes, so any anomalies could be reported?

Thanks again!

_Mark

**Comment by VSSavin** [comment]
Should I do this here https://groups.google.com/g/openpnp ?

**Comment by markmaker** [comment]
Yes, please 💯

**Comment by markmaker** [comment]
Hi @vonnieda,

I just found another setting that Eclipse needs for translation. Maven automatically adds a "**" exclusion pattern for building on the resource path. But apparently Eclipse needs that removed, so it can "see" the translations bundle:

image

See this [Eclipse/m2e bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=369296), and [follow-up here](https://github.com/eclipse-m2e/m2e-core/issues/139).

I removed the exclusion pattern and now it works fine, see the Wiki I wrote:

https://github.com/openpnp/openpnp/wiki/Getting-Started-with-Eclipse#translations-in-eclipse

But strangely that removal creates no change in `git`, although it is a _project_ setting, apparently.

Questions:

1. Do you understand why it does not show as a change? 
2. Does this mean that each user must do that themselves, as a separate Eclipse setup step? 
   (that's not so bad, [there are already many](https://github.com/openpnp/openpnp/wiki/Getting-Started-with-Eclipse#step-by-step)...)
4. Is this because we only do the "Configure -> Convert to Maven Project" step after the git checkout, [as explained here](https://github.com/openpnp/openpnp/wiki/Getting-Started-with-Eclipse#step-by-step)? 
5. And if yes, can't this be changed, i.e. the project checked in with maven conversion (and changes to its settings) already applied?

Sorry I'm still lightyears away from understanding how this all works together, i.e. how far the Java standard reaches, where maven comes in, how m2e figures in all this, and where Eclipse actually still manages project stuff, if at all. I don't expect to get an explanation, this is just me whining ;-)

Btw. you hinted at Eclipse being "obsolete", so if you know a better/more modern way to actually edit the OpenPnP project, _including designing the UI Wizards_, I'm open for suggestions ;-) 

_Mark

**Comment by ian-arkver** [comment]
Re 1)

.settings and .project are in the .gitignore so changes there are indeed ignored. This is usually because there are per-user customisations in there, eg. paths, which shouldn't be tracked in git.

If you can reliably separate those out so that only project-wide Eclipse settings are stored there then perhaps they could be removed from .gitignore and tracked.

Re editor wars... I think a lot of people have switched to VSCode for general code editing. This doesn't include a UI editor/builder though, afaik. Happy to be proven wrong here.

**Comment by vonnieda** [comment]
I use VSCode for nearly everything now. I haven't done any GUI work in OpenPnP for quite some time, of course, but if I were going to I'd probably try to use the standalone WindowBuilder first, and then fall back to an Eclipse install if needed. 

(I just checked and it looks like maybe the standalone WindowBuilder is gone now)

There is no simple answer. Swing has been on life support for about 15 years at this point but we're stuck with it unless someone wants to start rewriting the UI. Being a toolkit that nearly no one cares about, the tooling is bad, the support is bad, and the ecosystem is bad. 

We can certainly check in the project files, but as @ian-arkver mentioned, these are often user customized or just randomly changed by Eclipse itself, which means as soon as you open the project you now have a dirty file to decide if you are going to revert, commit, or leave dirty. That's why they are set to ignore.

FWIW, if someone is really interested in the UI side, they might want to see what would be involved with starting to integrate JavaFX. It's a lot more modern and can be much more easily composed directly in code without a builder app.

Additionally, I'll note that the constraints that WindowBuilder (really FormLayout) uses look complicated, but they are documented and stable. You *can* write them by hand after a little study. And finally, you can also just not use FormLayout. There's lots of other layouts and it's not uncommon at all to write these by hand.

**Comment by markmaker** [comment]
Hi @vonnieda 

>a toolkit that nearly no one cares about, the tooling is bad, the support is bad, and the ecosystem is bad.

Ouch, _so_ bad?_!_
 
Somehow, the alternative does not truly look better... just my opinion. 

Regarding JavaFX as an alternative, I had to smirk, because I still remember your [earlier words](https://groups.google.com/g/openpnp/c/OYgFprz1FNg/m/MafU3Dm1CgAJ): 

> "JavaFX is dead" is just my opinion. I see very little interest from the developer community, and now that Oracle is peeling it off it's up to the community (and Gluon) to keep it alive. Since there was very little interest to begin with, I see this failing.

And also _famously_ (at the time it quite thoroughly changed my views): 

> Electron is, not to put too fine a point on it, a complete abomination. I have to use Slack for a variety of reasons and it's one of the worst pieces of software I've ever used.
> [...]
> I'm a professional software developer. It's how I've made my living for over 20 years. Most of that time has been spent developing web applications in HTML and JavaScript. I've seen the JavaScript ecosystem become more and more fractured on nearly a daily basis.
>
> If you create an app today using any of the popular frameworks there is a very, very good chance it will not build next year. I maintain a pile of production web apps and this is a constant battle. Build systems change constantly, packages disappear or their APIs completely change, package managers disappear, common packages suddenly are injected with malware, etc.

Like I said, this was very influential for me, helped change strategy in my firm.

Regarding VSCode. Erm... isn't that an Electron Web App? 😜 IMHO, it really shows at the seams. Even for the most basic tasks, you need countless plugins, all written in runtime-faulty JavaScript, and there are a million to chose from, three quarters abandoned, half of them broken. I tried to find a decent version control plugin that could not only "look" but also "act" and "edit", it was hopeless. 

Personally, I find it hard to find _real_ advantages in VSCode, many things are so quirky with that "command palette" fixation. Nothing is self-explanatory, it takes half a doctorate of studying tutorials to know how to initialize and build a damn C++ project. And if you revisit the same tutorial a moth later, _everything_ has changed. I'm all for file based, human readable and version control friendly storage of settings etc., but configuring your _proprietary_ IDE and plugin options in a naked JSON file? Seriously? 

I'm too old for that shit, give me a toolbar, context menu and configuration dialog, please, it has been proven to work! Or then stick to the darn command-line, so it can be used outside the proprietary IDE. 

I know, I know ... 🙄

_Mark

**Comment by vonnieda** [comment]
> Hi @vonnieda
> 
> > a toolkit that nearly no one cares about, the tooling is bad, the support is bad, and the ecosystem is bad.
> 
> Ouch, _so_ bad?_!_
> 
> Somehow, the alternative does not truly look better... just my opinion.
> 
> Regarding JavaFX as an alternative, I had to smirk, because I still remember your [earlier words](https://groups.google.com/g/openpnp/c/OYgFprz1FNg/m/MafU3Dm1CgAJ):
> 
> > "JavaFX is dead" is just my opinion. I see very little interest from the developer community, and now that Oracle is peeling it off it's up to the community (and Gluon) to keep it alive. Since there was very little interest to begin with, I see this failing.
> 

Yep, that was 2018. Sadly, it's not much better now, but it is a little better. 

JavaFX is, in fact, for all intents and purposes dead. Just like Java **on the Desktop** (bolded so no one tries to tell me that Java is alive and well - I know!), and just like Swing. These technologies have been left behind. Very few people are using them. Maybe dead is too strong a word - "life support" might work better. But the fact is that Java based UI, like OpenPnP, and other programs based on Swing and indeed JavaFX just aren't getting much interest these days. I only mentioned JavaFX it because it's the only real alternative to Swing for Java, and it is in fact better than Swing. (Better support for High DPI displays and font rendering, better support for hardware acceleration, modern scene graph, modern data binding, etc.)

> And also _famously_ (at the time it quite thoroughly changed my views):
> 
> > Electron is, not to put too fine a point on it, a complete abomination. I have to use Slack for a variety of reasons and it's one of the worst pieces of software I've ever used.
> > [...]
> > I'm a professional software developer. It's how I've made my living for over 20 years. Most of that time has been spent developing web applications in HTML and JavaScript. I've seen the JavaScript ecosystem become more and more fractured on nearly a daily basis.
> > If you create an app today using any of the popular frameworks there is a very, very good chance it will not build next year. I maintain a pile of production web apps and this is a constant battle. Build systems change constantly, packages disappear or their APIs completely change, package managers disappear, common packages suddenly are injected with malware, etc.
> 
> Like I said, this was very influential for me, helped change strategy in my firm.
> 
> Regarding VSCode. Erm... isn't that an Electron Web App? 😜 IMHO, it really shows at the seams. Even for the most basic tasks, you need countless plugins, all written in runtime-faulty JavaScript, and there are a million to chose from, three quarters abandoned, half of them broken. I tried to find a decent version control plugin that could not only "look" but also "act" and "edit", it was hopeless.
> 

I still feel the same way about Electron, but I don't let it get in the way of being useful. I use Slack, VSCode, Obsidian, Spotify, and probably a few others I don't even realize are Electron based. Sadly, lots of developer hours have been put into making Electron better and very few have been put into making Swing and JavaFX better. Electron is better today than it was in 2018, but I still wouldn't personally use it for a project. An, in fact, I've been actively looking for ways not to use it in a few new projects I'd like to work on.

> Personally, I find it hard to find _real_ advantages in VSCode, many things are so quirky with that "command palette" fixation. Nothing is self-explanatory, it takes half a doctorate of studying tutorials to know how to initialize and build a damn C++ project. And if you revisit the same tutorial a moth later, _everything_ has changed. I'm all for file based, human readable and version control friendly storage of settings etc., but configuring your _proprietary_ IDE and plugin options in a naked JSON file? Seriously?
> 
> I'm too old for that shit, give me a toolbar, context menu and configuration dialog, please, it has been proven to work! Or then stick to the darn command-line, so it can be used outside the proprietary IDE.

The funny thing is that it was C that drove me from Eclipse to VSCode. I used Eclipse CDT for years and years but for every single one of those years it could NEVER get the indexing and code introspection correct. In VSCode, I can get "Intellisense" working with four lines in a JSON file which I can easily check in Github and never worry about again. 

Most of my daily work is in embedded C for a wide variety of difference devices. On any given day I'm compiling C for ESP32, macOS, MSP430, CC1310 (ARM), 8 bit AVR, etc. This has all been so much smoother since switching to VSCode for me. I do admit though that a big part of the success there has been working to make sure my projects use simple and understandable build systems. 

Personally, I love the Command Palette! I never have to remember which menu something is buried in again! (Is the window splitting under View or Edit? How do I format this selection is that under Edit -> Tools or Tools -> Editor? Etc, etc, etc.) Now it's one shortcut to remember - Cmd P, and I can type a few characters of what I remember and go.

I've switched to using the Command Palette for many of my tools and I really think it's a game changer. With one shortcut I can quickly find any command in any part of the program, including plugins, or open a file, jump to a symbol, jump to a line number, etc. Amazing.

So, with all that said... anyone want to rewrite OpenPnP in Rust with EGUI? 😉

**Comment by markmaker** [comment]
> Personally, I love the Command Palette! I never have to remember which menu something is buried in again!

Agree, that can be useful, but I would still prefer it to work both ways. 

Menus, and especifically well-made _context_ menus, are great for exploring _yet unknown_ stuff, and the context menu is _object oriented_, which I think the command palette is not (not entirely sure). 

Anyway, I plan to use Visual Code too, more and more, mostly for lack of alternatives. While I found Eclipse is quite powerful and rock solid for Java, I too found it lacking for C++. 

I have to admit that VSCode has become slightly better over the years now, there are more and more buttons and menus creeping in, even found that some status bar elements are unexpectedly _active_. 

_Mark

**Comment by ian-arkver** [comment]
> The funny thing is that it was C that drove me from Eclipse to VSCode. I used Eclipse CDT for years and years but for every single one of those years it could NEVER get the indexing and code introspection correct. In VSCode, I can get "Intellisense" working with four lines in a JSON file which I can easily check in Github and never worry about again.

Same here. Eclipse CDT indexing stopped working for two main things for me - the Linux kernel and C++ projects using for example Standalone ASIO and NLohmann's JSON. Maybe it's fixed now, but I haven't gone back to check.

VSCode doesn't do those perfectly either, but it's better.

Re extensions - CMake Tools works seamlessly with any cmake project I've tried, and Gitlens is good for poking around git, though the built-in git support is pretty good too. VSCode generally recommends suitable extensions where needed.

Re egui - dunno whether this was serious or not, but I think a switch to an immediate mode GUI would be quite the paradigm shift for something like OpenPnP. Also egui is light on dependencies, so doesn't include any i18n support for UI strings, so you'd need something like gettext-rs as well. There's [some discussion here](https://github.com/emilk/egui/issues/136) which seemed to end up with all the fixed strings being removed from egui.

Re Rust - it might be even harder to get Rust contributors than Java ones.

**Comment by Alan-0131** [comment]
Hello, I am from China, I saw your recent changes to the translation section, and now multilingual Chinese can be displayed, thank you for your efforts, this is really great, I also want to join in to maintain the multilingual Chinese section ,Can you tell me what to do? Is it referring to https://github.com/openpnp/openpnp/blob/develop/TRANSLATIONS.md here? Or has something changed?

**Comment by Shaische** [comment]
@Alan-0131 Someone brought this to Jason's attention. I think you should first address this before asking Jason or other developers for help: https://github.com/openpnp/openpnp/issues/1495

**Comment by Alan-0131** [comment]
thank you for your reply. I have sent emails and messages to JASON to explain this matter, and I am willing to transfer the trademark to JASON for free. In China, I have to do this because even if I don't apply, someone else will definitely apply. There are many such cases now. I am not suing anyone or company, nor am I using this trademark myself. I just want to protect openpnp from being involved in commercial competition. I have tried to get in touch with Jason several times but so far he has not responded to me

**Comment by markmaker** [comment]
I agree with @Shaische the trademark issue must be resolved first.

To translate, be sure to switch to the `test` branch, so _this_ is the right description: 

https://github.com/openpnp/openpnp/blob/test/TRANSLATIONS.md 

You also must _base_ and _target_ the translations on/from `test`.

_Mark

**Comment by ian-arkver** [comment]
@Alan-0131 perhaps you should write up your intentions on #1495 that Shai linked to.

**Comment by Alan-0131** [comment]
> @Alan-0131也许你应该在 Shai 链接到的#1495上写下你的意图。

Thanks for the reminder, I'll do it right away

**Comment by Alan-0131** [comment]
@ian-arkver @markmaker @vonnieda Thank you for your reminders, maybe I should have done this a long time ago, but I really didn't think about it. I have already issued a statement, do you think this is okay?

**Pull request merged**
