### PR TITLE
ReferenceLoosePartFeeder - Human Vision Fallback

### PR DESCRIPTION
**Pull request by surabibio**
# Description
In ReferenceLoosePartFeeder when computer vision fails, the user get stuck and has to tweak CV settings which is often hindering especially in the middle of a job. An option to manually jog to the parts pick location could be time saving.

# Instructions for Use
When CV fails, the "Instructions Panel" shows up. The current job is paused. The user has to manually jog to the parts pick location and click "Accept" The job resumes.

# Implementation Details
1. How did you test the change? Tested in simulation.

### CODE REVIEW

**Comment by markmaker** [comment]
Hi @surabibio 

you need to properly handle the OpenPnP threading architecture. GUI stuff and machine task stuff must not be mixed.

1. You must leave the machine task (which may or may not be a job) by (re-) throwing the exception, there is no other proper way. This will automatically pause the job. In fact it is more complicated, we would need some sort of unconditional exception, so that the retry loops are broken.
2. To resume you must first check if there is a paused job, it might have been a simple GUI button feed. 

I was thinking about user intervention inside a task before (auto-template image learning in bottom vision) and it is not easy at all. 

_Mark

**Comment by surabibio** [comment]
Hi,

Nowhere am I interfering with the threading like wait() or Sleep() or notify().

 

This approach is like the user clicking the pause button right after feed(). Will it not pause the job? So does this approach.

Only thing is, it eats the exception and the machine thinks feed() has succeeded for good, which is OK for us.

 

Regarding #2 I think that is already taken care of. i.e pressing GUI button feed will not inadvertently start the job!!

 

Any other critical review of this approach is welcome.

**Comment by markmaker** [comment]
> Nowhere am I interfering with the threading like wait() or Sleep() or notify().

You are calling GUI stuff from `feed()`, which is always running in a machine task thread. You cannot do that. Use `SwingUtilities.invokeLater()` or similar. 

> Only thing is, it eats the exception and the machine thinks feed() has succeeded for good, which is OK for us.

Before claiming such things, take the time to see where the `feed()` call originates from in the `JobProcessor` and in the GUI action and what happens when _no_ exception is thrown. For the  `JobProcessor`, check what further actions take place, before the processor next checks for `State.Paused`. Frankly, you should have done that before even _thinking_ about intercepting `feed()` like that. 

> Regarding [#2](https://github.com/openpnp/openpnp/issues/2) I think that is already taken care of. i.e pressing GUI button feed will not inadvertently start the job!!

When I said "resume" I meant the `ResumeJob()` call in your `doProceed()`. The `feed()` could have been called from a job or from the GUI action. The  `ResumeJob()` must only be called in the former case.

I've spent a lot of time on your last PR, explaining things again and again. You should have learnt to second-guess your approach properly, before claiming things, notably _directly_ against my advice. Show some readiness to actually check out what I try to explain, or ask back if it is not clear what I mean ... oh and it doesn't hurt to do it nicely. :-)

_Mark

**Comment by markmaker** [comment]
Please read more carefully, what I actually wrote. Investigate what I pointed out. 

_Mark

**Comment by surabibio** [comment]
Here is the [last occured discussion](https://groups.google.com/g/openpnp/c/OyZd4SEXhmA/m/f0GQGBTvAwAJ) on this feature. Even thought the PR could not be consumed, wish this idea lives on and hope one day it may find takers....

**Pull request closed without merging**
