### PR TITLE
Create SimpleBlob.java

### PR DESCRIPTION
**Pull request by cri-s**
as request from @dazach working simpleblobs

# Description
SimpleBlob feature detector
It's same as SimpleBlobDetector, just with configurable parameters.

# Justification
Request from @dazach sharing this.

# Instructions for Use
https://www.learnopencv.com/blob-detection-using-opencv-python-c/

This is documentation for a user, not for a developer.

# Implementation Details
1. How did you test the change?
in use
2. Did you add automated tests?
no
3. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)?
no
4. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing.
no

### CODE REVIEW

**Comment by dzach** [comment]
Thank you @cri-s ! I'll try it and see what I can get out of it. In the meanwhile I'm creating an issue where we and others can discuss OpenCV pipelines and gather some useful ideas/code.

**Comment by cri-s** [comment]
seems to be a conflict because i have not merged the two files at same time.

**Comment by dzach** [comment]
No problem with me, I'll make the changes locally

**Comment by vonnieda** [comment]
Closing as this was just for reference, not for merging.

**Comment by cri-s** [comment]
@jason, if you want merge it, it is SimpleBlobDetector where
parameters can be changed,
you'r decision.

2017-05-09 1:03 GMT+02:00, Jason von Nieda <notifications@github.com>:

**Comment by vonnieda** [comment]
@cri-s Can you add the parameters to the existing one? There's no reason to have two that do the same thing.

**Comment by cri-s** [comment]
Example from xml      <cv-stage
class="org.openpnp.vision.pipeline.stages.SimpleBlob" name="1"
enabled="true" threshold-step="10.0" threshold-min="50.0"
threshold-max="220.0" repeatability="2" dist-between-blobs="10.0"
color="true" color-value="0.0" area="true" area-min="25.0"
area-max="5000.0" circularity="false"
circularity-min="0.800000011920929"
circularity-max="3.4028234663852886E38" inertia="true"
inertia-ratio-min="0.10000000149011612"
inertia-ratio-max="3.4028234663852886E38" convexity="true"
convexity-min="0.949999988079071"
convexity-max="3.4028234663852886E38"/>


2017-05-09 1:09 GMT+02:00, Cri S <phone.cri@gmail.com>:

**Comment by vonnieda** [comment]
@cri-s I'll be happy to have it, but I'd like for it to be in the existing class (SimpleBlobDetector) and it needs to compile, pass tests and should not create the temporary file. The PR you submitted does not compile - there is a code error where createParams() tries to access blobDetector which is defined only in process().

**Comment by cri-s** [comment]
Then phase out the old one that is setup to find black round holes
without possibility to configure it. As i remember it was used for
nozzle calibration. I don't know if it's already in use in field and
if it's wise to change parameters as the configuration refuse to load
in that case.
Surf/Orb/... need the same workaround.

2017-05-09 1:12 GMT+02:00, Cri S <phone.cri@gmail.com>:

**Comment by cri-s** [comment]
sorry, because of missing java interface to opencv creating the
temporary file is the only possibility to set parameters.

2017-05-09 1:12 GMT+02:00, Cri S <phone.cri@gmail.com>:

**Comment by vonnieda** [comment]
Ah, yes, that's right. I had forgotten that the interface was missing.

Okay, this seems acceptable then and I think it's okay to just replace the existing SimpleBlobDetector since it doesn't actually work :) It put it in as an experiment and I don't think anyone uses it. Even if they do, they can just use the new one and set the parameters.

Are you willing to fix the code problems and resubmit? Currently it does not compile, and the variable names are all capitalized incorrectly. You can see the errors by running `mvn test`.

**Comment by cri-s** [comment]
Resubmitted as #546

2017-05-09 1:44 GMT+02:00, Jason von Nieda <notifications@github.com>:

**Pull request closed without merging**
