### PR TITLE
 Remove serial port read timeout. Close port before reader thread join. (resubmit)

### PR DESCRIPTION
**Pull request by ian-arkver**
# Description
Avoid loss of characters due to serial port read timeouts causing a partially read line to be discarded.

# Justification
As discussed in #1235 and rebased onto test branch as mentioned in #1377.

# Instructions for Use
N/A

# Implementation Details
1. How did you test the change? Be descriptive. Untested code will not be accepted.
Only tested with maven built in tests. I've no serial comms to check this.

2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)?
Yes
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing.
N/A
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted.
Tests passed.

### CODE REVIEW

**Comment by markmaker** [comment]
Hi @ian-arkver,

I tested this locally, using three serially connected controllers, a Smoothieware,  Duet and TinyG. It works, but obviously, the exceptions just shifts from the thread to the connection:

```
2022-02-03 13:41:56.488 GcodeDriver$ReaderThread TRACE: Read error while disconnecting: java.io.IOException: Read error.
	at org.openpnp.machine.reference.driver.SerialPortCommunications.read(SerialPortCommunications.java:140)
	at org.openpnp.machine.reference.driver.ReferenceDriverCommunications.readUntil(ReferenceDriverCommunications.java:92)
	at org.openpnp.machine.reference.driver.ReferenceDriverCommunications.readLine(ReferenceDriverCommunications.java:72)
	at org.openpnp.machine.reference.driver.GcodeDriver$ReaderThread.run(GcodeDriver.java:1274)
2022-02-03 13:41:56.588 GcodeAsyncDriver$WriterThread TRACE: [serial://ttyUSB0] disconnectRequested, bye-bye.
2022-02-03 13:41:56.589 GcodeDriver$ReaderThread TRACE: Read error while disconnecting: java.io.IOException: Read error.
	at org.openpnp.machine.reference.driver.SerialPortCommunications.read(SerialPortCommunications.java:140)
	at org.openpnp.machine.reference.driver.ReferenceDriverCommunications.readUntil(ReferenceDriverCommunications.java:92)
	at org.openpnp.machine.reference.driver.ReferenceDriverCommunications.readLine(ReferenceDriverCommunications.java:72)
	at org.openpnp.machine.reference.driver.GcodeDriver$ReaderThread.run(GcodeDriver.java:1274)
2022-02-03 13:41:56.689 GcodeAsyncDriver$WriterThread TRACE: [serial://ttyACM0] disconnectRequested, bye-bye.
2022-02-03 13:41:56.689 GcodeDriver$ReaderThread TRACE: Read error while disconnecting: java.io.IOException: Read error.
	at org.openpnp.machine.reference.driver.SerialPortCommunications.read(SerialPortCommunications.java:140)
	at org.openpnp.machine.reference.driver.ReferenceDriverCommunications.readUntil(ReferenceDriverCommunications.java:92)
	at org.openpnp.machine.reference.driver.ReferenceDriverCommunications.readLine(ReferenceDriverCommunications.java:72)
	at org.openpnp.machine.reference.driver.GcodeDriver$ReaderThread.run(GcodeDriver.java:1274)
2022-02-03 13:41:56.789 GcodeAsyncDriver$WriterThread TRACE: [serial://ttyACM1] disconnectRequested, bye-bye.
```

I guess that's expected, right?

_Mark

**Comment by ian-arkver** [comment]
I would expect an IOException to be thrown if the port is closed while in a read() call, yes. So long as this is handled cleanly then it's fine I think. We don't want it to propagate up to a user dialog popup.

**Comment by markmaker** [comment]
I guess it would be better if the _expected_ Exception was not logged in that case. 

Can you please find the "Read error while disconnecting" logger line and remove the `e`?

_Mark

**Comment by ian-arkver** [comment]
I've pushed another commit for this. I think the PR auto-updates to include that as well. At least for me it shows 3 commits now.

**Comment by ian-arkver** [comment]
Ah, ok, just read the last comment

**Comment by markmaker** [comment]
Thanks a lot!

**Pull request merged**
