### PR TITLE
Fix getPickLocation of ReferenceTrayFeeder

### PR DESCRIPTION
**Pull request by janm012012**
# Description
This PR fixes the getPickLocation method of the ReferenceTrayFeeder by always calculating it based on current UI values. In the previous implementation the location was static and only updated on feed operations. This is not ideal as there is no direct relation to the UI and its not obvious to the user.

# Justification
I tried to use a ReferenceTrayFeeder and failed because I was not able to verify its configuration prior use. Changing feedCount or offsets did not help to check the locations a part would be picked up from.

This is documentation for a user, not for a developer.

# Implementation Details
1. How did you test the change? Be descriptive. Untested code will not be accepted. **I used a simulation machine and verified that UI changes are immediately reflected as well as feed and pick operations work as before.**
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? **yes**
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing. **no**
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted. **yes**

### CODE REVIEW

**Comment by markmaker** [comment]
Hi @janm012012,

functionality looks good. 

As always, one small thing left :smile: 

Logging (2 x) in a getter like `getPickLocation()` is probably too chatty. Move the logging to  `setFeedCount()` (which is also called by `feed()` where logging was before), so changing the feed count from elsewhere (e.g. the UI) would _also_ generate a helpful debug log. Just eval `getPickLocation()` there to do it.

_Mark

**Comment by janm012012** [comment]
Changed! Thanks for reviewing!

**Comment by markmaker** [comment]
Hmmm... please read again, in detail. I hope this was understandable...

**Comment by janm012012** [comment]
Hi @markmaker!

I'm sorry for being not patient enough! Calling getPickLocation() from setFeedCount() requires to handle the exception, that getPickLocation can throw, which is "Tray empty".  I think its better to keep the exception in feed() (as it was initially) and do not generate it in getPickLocation. I've replaced it by a warning and limited feedCount to the tray size. What do you think?

Jan

**Comment by markmaker** [comment]
The exception change is a good one.

But please move the logging to `setFeedCount()` to avoid logging on each getter evaluation. By calling `getPickLocation()` in the log message expression, you'll get a fresh calculation.

**Comment by janm012012** [comment]
Do you mean like this?

**Comment by markmaker** [comment]
Yes!

I reviewed the whole again, and I think you should name the feeder and part id in the "Tray empty" exception. Otherwise the user might not know which tray it refers to. 

Sorry, I haven't seen this before :sweat_smile:, this should now be my last remark...

_Mark

**Comment by janm012012** [comment]
Changed!

While testing I found, that getName() for the part I used is null. Instead I now use getId() and changed the exception in takeBackPart() where I copied getName() from as well. What is getName() of parts used for? I don't see any reference in the UI explaining the difference between ID and Name.

If there is anything else you think should be changed, please let me know.

Jan

**Comment by markmaker** [comment]
The `getName()` is just an unwanted class inheritance artifact, I guess.

Thanks for the good work! :100:

**Pull request merged**
