### PR TITLE
Feature/BambooFeederAutoVision

### PR DESCRIPTION
**Pull request by prusk**
# Description
This PR adds a new feeder type named **`BambooFeederAutoVision`**. It combines the vision calibration initially implemented by the _ReferencePushPullFeeder_ with the standard 2 actuators in the _ReferenceAutoFeeder_.
This is extremely useful for auto feeders that have a larger pick window which exposes at least 2 tape holes, like the latest iterations of BambooFeeder AS1.

In addition:
* Creates a base abstract class `PandaplacerVisionFeeder` that implements the CV calibration and can be potentially reused in multiple feeders without code duplication. This is a stripped down version of the PushPull feeder.
* Creates the `TapeUtils` class dedicated to CV calibration of EIA Tape. It can be moved to `org.openpnp.util` to allow for more reuse. (this is the reworked inner class FindFeatures from the PushPull feeder)

# Justification
Multiple auto feeders expose a larger pick window where multiple tape holes are visible.
The new feeder type allows better calibration of the pick location.

# Instructions for Use
Create a new feeder of type `BambooFeederAutoVision` and configure as follows:
* Vision calibration parameters - same as `ReferencePushPullFeeder`
* Actuators - same as `ReferenceAutoFeeder`

# Implementation Details
1. How did you test the change? 
* Ran all the automated tests
* Tested the new feeder type on my personal hardware
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)?
* Yes
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing.
* No changes to `org.openpnp.spi` or `org.openpnp.model` packages
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted.
* All tests passed

### CODE REVIEW

**Comment by markmaker** [comment]
Hi @prusk,

looks good. Some comments:

- The GNU GPL copyright notice you compiled in `BambooFeederAutoVisionConfigurationWizard` should be in all the new files,
- The name `TapeUtils` does not describe very well what it does. Why not `FeederVisionHelper` or something similar? Then I guess it could be moved to `org.openpnp.util`. 
- Naming should be consistent in this file, so other "findFeature" names (from the original) should be renamed too. 
- While you're at it: there is a white-space inconsistency at the top.
- In OpenPnP (and I guess in English in general) the significant term usually comes at the end. I guess `BambooFeederAutoVision` should best be called `BambooVisionAutoFeeder` or maybe just `BambooFeeder` :grin: 
- You used the "Bamboo" term and the "Pandaplacer" term mixed i.e. `PandaplacerVisionFeeder`. Is this intentional? Also, to make it clearer to browse maybe prefix with "Abstract" 
- Are you sure you're not infringing on any registered trademarks with these brand names?

_Mark

**Comment by prusk** [comment]
Hi @markmaker ,

Thank you for the review.
I think I addressed all the concerns:

* > The GNU GPL copyright notice you compiled in `BambooFeederAutoVisionConfigurationWizard` should be in all the new files
    * Fixed
* > The name `TapeUtils` does not describe very well what it does. Why not `FeederVisionHelper` or something similar? Then I guess it could be moved to `org.openpnp.util`.
    * Renamed as suggested and moved to `org.openpnp.util`. In a follow-up PR maybe we consolidate this by updating the PushPullFeeder to use this same util class so tape features detection is in only one place. What do you think?
* > Naming should be consistent in this file, so other "findFeature" names (from the original) should be renamed too.
    * The only other occurrence was for the `FindFeaturesMode` which is an enum therefore correctly starting with capital F
* > While you're at it: there is a white-space inconsistency at the top.
     * Fixed? I think it was in the imports section...
* > In OpenPnP (and I guess in English in general) the significant term usually comes at the end. I guess `BambooFeederAutoVision` should best be called `BambooVisionAutoFeeder` or maybe just `BambooFeeder` 😁
     * This is intentional as the official name of the feeder product is "BambooFeeder" with models AS1, etc. Had to keep that consistent.
* > You used the "Bamboo" term and the "Pandaplacer" term mixed i.e. `PandaplacerVisionFeeder`. Is this intentional? Also, to make it clearer to browse maybe prefix with "Abstract"
     * BambooFeeder is the official name of the product while PandaplacerVisionFeeder is more generic and may accommodate other feeder products in this space that might not be named "BambooFeeder". If we take  it a step further, this is actually a generic "ReferenceVisionFeeder" that was rejected in the previous PR.
* > Are you sure you're not infringing on any registered trademarks with these brand names?
    * As of right now, **Yes**. We currently own intellectual property beyond the pandaplacer .com & .ca domains.

**Comment by markmaker** [comment]
Thanks @prusk,

> Fixed? I think it was in the imports section...

Still see white-space inconsistency in `FeederVisionHelper` around the `enum` (likely tabs, we want all spaces).

> The only other occurrence was for the FindFeaturesMode which is an enum therefore correctly starting with capital F

I meant the term "find features" per se, not lower/upper case. There are still `findFeatures` methods, I would name these `performVision` or something more befitting the new class name. Likewise the enum could be called `FeederVisionMode` or similar. This is just a suggestion for clarity in future reuse. I am aware that the same could be said for the `ReferencePushPullFeeder` `FindFeatures` class, but this class has evolved from much humbler origins, hence the name. :sweat_smile: 

I wrote:
> In OpenPnP (and I guess in English in general) the significant term usually comes at the end. I guess BambooFeederAutoVision should best be called BambooVisionAutoFeeder or maybe just BambooFeeder 😁

You answered:
> This is intentional as the official name of the feeder product is "BambooFeeder" with models AS1, etc. Had to keep that consistent.

I think there was an misunderstanding. 

In English the last noun of a compound noun is the most important. A "garden flower" is a **flower** which grows in a garden. But a "flower garden" is a **garden** full of flowers. 

Following this rule, a "BambooFeederAutoVision" describes a "Vision" object, not a "Feeder" object, as it should. 

https://englishfornoobs.com/wp-content/uploads/2018/11/Compound-nouns-rules-in-English.pdf (don't take that link's domain name personal, it's just the only source I found where it is described clearly, I'm also not a native speaker).

_Mark

**Comment by prusk** [comment]
Hi @markmaker ,

> Still see white-space inconsistency in FeederVisionHelper around the enum (likely tabs, we want all spaces).

I fixed it and replaced tabs with spaces everywhere.

> `findFeatures` thing

I think it is actually a good name and the only other one I could come up with that is more descriptive is "findTapeHolesAndCalculatePartPocketLocation" which I find too long.
I added a clear description comment above the method definition to clarify what it does. This should be sufficient for future reuse of the class and its main method.

> `BambooFeederAutoVision` and English language thing

The name is fine. Ideally it should be `BambooFeeder-AutoVision` which describes the type AutoVision for the BambooFeeder product, common approach for products with multiple variants. (yes, English is correct in this case at least in Canada)
It is much easier for the customers to find the same terminology (BambooFeeder) in both the Pandaplacer documentation and in OpenPnP when configuring one of these feeders.
However, I haven't seen any class name with dashes anywhere in this repo and I don't feel like being a pioneer for new naming conventions.
re language: I understand where you're coming from but more often than not in technical terminology English is quite flexible combining nouns and adjectives in improper order. Let's call it "poetic license".

**Comment by markmaker** [comment]
Thanks.

**Pull request merged**
