### PR TITLE
Retry on configuration loading failed

### PR DESCRIPTION
**Pull request by JulienDevillers**
Hello Jason,

I was fed up of re-launching openpnp each time there was an error in configuration file
so I did this small update. It allows the user to choose whether he wants to retry or exit.

best regards
Julien

### CODE REVIEW

**Comment by markmaker** [comment]
Hi Julien

So you would leave the dialog standing, edit the `machine.xml` using an editor, save and then retry?

_Mark

**Comment by JulienDevillers** [comment]
Hello Mark

Exactly.

Julien

**Comment by markmaker** [comment]
I'm just asking because it would be super-duper-cool to somehow coerce the XML parser into being tolerant i.e. into ignoring unknown elements and continuing reading the rest of the XML. But that seems much harder to achieve. 

_Mark

**Comment by JulienDevillers** [comment]
That's right.

As I don't know well the structure of the project, I tend to be cautious
when doing modifications.
Generally, when I do some modifications, I'm in a hurry of producing
boards... :D

And I must say that I'm always afraid by the fact that my pull request
might be rejected and the work done for nothing...
Stupid developer's ego... :D

Btw. I love your new feeders ! Clever and well engineered !

Julien

**Comment by vonnieda** [comment]
Looks good @JulienDevillers - thanks!

**Pull request merged**
