### PR TITLE
Add support for tcp connections to hardware controller

### PR DESCRIPTION
**Pull request by PeeJay**
Signed-off-by: Paul Jones <paul@pauljones.id.au>

### CODE REVIEW

**Comment by vonnieda** [comment]
Hey @PeeJay, thanks for the PR. This looks like really solid work! Can you tell me what your confidence level is that this doesn't cause any problems for existing serial connections? Would existing users expect any surprises?

**Comment by vonnieda** [comment]
Looks like this might still need some work. I started OpenPnP with a fresh config, changed the driver to GcodeDriver and restarted, went to the GcodeDriver configuration wizard and got this:

```
2018-07-11 20:41:04 SystemLogger ERROR: Exception in thread "AWT-EventQueue-0" java.lang.UnsupportedOperationException: Unreadable
2018-07-11 20:41:04 SystemLogger ERROR: 	at org.jdesktop.beansbinding.BeanProperty.getValue(BeanProperty.java:543)
2018-07-11 20:41:04 SystemLogger ERROR: 	at org.openpnp.gui.support.JBindings$WrappedBinding.<init>(JBindings.java:88)
2018-07-11 20:41:04 SystemLogger ERROR: 	at org.openpnp.gui.support.JBindings.bind(JBindings.java:48)
2018-07-11 20:41:04 SystemLogger ERROR: 	at org.openpnp.gui.support.AbstractConfigurationWizard.addWrappedBinding(AbstractConfigurationWizard.java:132)
2018-07-11 20:41:04 SystemLogger ERROR: 	at org.openpnp.machine.reference.driver.wizards.AbstractCommunicationsConfigurationWizard.createBindings(AbstractCommunicationsConfigurationWizard.java:302)
2018-07-11 20:41:04 SystemLogger ERROR: 	at org.openpnp.gui.support.AbstractConfigurationWizard.setWizardContainer(AbstractConfigurationWizard.java:157)
2018-07-11 20:41:04 SystemLogger ERROR: 	at org.openpnp.gui.support.PropertySheetWizardAdapter.<init>(PropertySheetWizardAdapter.java:19)
2018-07-11 20:41:04 SystemLogger ERROR: 	at org.openpnp.machine.reference.driver.GcodeDriver.getPropertySheets(GcodeDriver.java:1022)
2018-07-11 20:41:04 SystemLogger ERROR: 	at org.openpnp.gui.MachineSetupPanel$4.valueChanged(MachineSetupPanel.java:171)
2018-07-11 20:41:04 SystemLogger ERROR: 	at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)
2018-07-11 20:41:04 SystemLogger ERROR: 	at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1093)
2018-07-11 20:41:04 SystemLogger ERROR: 	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:294)
2018-07-11 20:41:04 SystemLogger ERROR: 	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPath(DefaultTreeSelectionModel.java:188)
2018-07-11 20:41:04 SystemLogger ERROR: 	at javax.swing.JTree.setSelectionPath(JTree.java:1634)
2018-07-11 20:41:04 SystemLogger ERROR: 	at javax.swing.plaf.basic.BasicTreeUI.selectPathForEvent(BasicTreeUI.java:2393)
2018-07-11 20:41:04 SystemLogger ERROR: 	at javax.swing.plaf.basic.BasicTreeUI$Handler.handleSelection(BasicTreeUI.java:3609)
2018-07-11 20:41:04 SystemLogger ERROR: 	at javax.swing.plaf.basic.BasicTreeUI$Handler.mousePressed(BasicTreeUI.java:3548)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.Component.processMouseEvent(Component.java:6530)
2018-07-11 20:41:04 SystemLogger ERROR: 	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.Component.processEvent(Component.java:6298)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.Container.processEvent(Container.java:2237)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.Component.dispatchEventImpl(Component.java:4889)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.Container.dispatchEventImpl(Container.java:2295)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.Component.dispatchEvent(Component.java:4711)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4523)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.Container.dispatchEventImpl(Container.java:2281)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.Window.dispatchEventImpl(Window.java:2746)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.Component.dispatchEvent(Component.java:4711)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.EventQueue.access$500(EventQueue.java:97)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.EventQueue$3.run(EventQueue.java:709)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.EventQueue$3.run(EventQueue.java:703)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.security.AccessController.doPrivileged(Native Method)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.EventQueue$4.run(EventQueue.java:733)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.EventQueue$4.run(EventQueue.java:731)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.security.AccessController.doPrivileged(Native Method)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
2018-07-11 20:41:04 SystemLogger ERROR: 	at org.openpnp.gui.MainFrame$16.dispatchEvent(MainFrame.java:401)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
2018-07-11 20:41:04 SystemLogger ERROR: 	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by PeeJay** [comment]
Ahh shoot. I had originally renamed RTS and CTS, but changed them back at the last minute and only compile tested. IntelliJ must have got confused.
Change line 302 in AbstractCommunicationsConfigurationWizard to
```
addWrappedBinding(driver, "setDtr", setDtrCheckbox, "selected");
addWrappedBinding(driver, "setRts", setRtsCheckbox, "selected");
```

I haven't extensively tested this yet so I don't know how well it works. I thought you might pick up something I missed so I submitted the PR anyway. It would be good to get a few testers before merging.

**Comment by KarlZeilhofer** [comment]
Nice, I thought this feature was implemented already. We are on our way to migrate our machine from TinyG to Smoothie Board, which we wanted to use via Ethernet anyway. Still could take some weeks, until we can test this PR.

**Comment by vonnieda** [comment]
Sounds good, thanks @PeeJay. I'll give this a run through this weekend.

**Comment by vonnieda** [comment]
Thanks @PeeJay! This is a really nice improvement. I've merged it, along with some small changes. Primarily I made sure that user's existing settings are migrated automatically, and fix the RTS and DTR issues from above.

**Comment by Phara0h** [comment]
@KarlZeilhofer If your upgrading just for the ethernet port, I was thinking of writing a quite mini server that can be run on your current machine to act as if your serial device was connected via ethernet.

**Comment by KarlZeilhofer** [comment]
@Phara0h Thanks, but we want to use Ethernet, because we are tired of mixing up the different /dev/ttyUSBx devices. So we want to get rid of USB as far as possible. Now we have 2 USB cameras (any suggestions for affordable ethernet cameras?), 1 motor driver and 2 arduino nano. We have to switch on everything in a very special order, otherwise something doesn't work.

**Comment by PeeJay** [comment]
Looks good to me. 
The reason I changed referenceDriver to communications is because I thought it was getting a bit confusing having gcodeDriver, serialDriver, TcpDriver etc. where gcode is a software interface and the other two are hardware interfaces, and conceivably someone could write a binaryDriver for a machine that doesn't speak gcode. But no big deal really.

**Comment by vonnieda** [comment]
Hey Paul, I left the serial and tcp classes with the communications suffix,
for exactly that reason. I just changed AbstractCommunications to driver
because it’s the base class for the drivers.

I've got some further changes queued up that will allow us to swap in the
communications classes by class name so that we don't have the switch on
the communications type. This will be a big benefit because I will finally
be able to write a testable version of the communications and start adding
test cases for GcodeDriver.

It's something I've wanted to do for a while, so that we can prove
GcodeDriver works after changes, but it's been impossible until your
modifications - so thank you!

Jason

**Comment by Phara0h** [comment]
> @Phara0h Thanks, but we want to use Ethernet, because we are tired of mixing up the different /dev/ttyUSBx devices. So we want to get rid of USB as far as possible. Now we have 2 USB cameras (any suggestions for affordable ethernet cameras?), 1 motor driver and 2 arduino nano. We have to switch on everything in a very special order, otherwise something doesn't work.

If that is the only reason why you want to switch over to Ethernet and not because you want to use a remote computer (like the Idea I had) then you can simply update the USB code to attach to the UUID USB property + the comport so you can 100% guarantee even if they comport changes then the code can be smart about it and update the device to the correct com port based on UUID.

**Pull request merged**
