### PR TITLE
Updating to JUnit 5

### PR DESCRIPTION
**Pull request by Jnesselr**
# Description
Update from JUnit 4 to JUnit 5

# Justification
Because JUnit 5 is one better than JUnit 4. I was going to upgrade to JUnit 4.13 and then decided to upgrade to JUnit 5. There's some differences here and there between the two, but JUnit 5 has more useful functionality.

# Instructions for Use
Dev only feature.

# Implementation Details
1. How did you test the change? Be descriptive. Untested code will not be accepted.
Unit Testing ++
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)?
Yes
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing.
No, only in tests.
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted.
I ran the unit tests.

### CODE REVIEW

**Comment by markmaker** [comment]
Hi @Jnesselr 

How can I switch on unit test output again?

It runs silently now:

terse

Thanks,
_Mark

**Comment by Jnesselr** [comment]
I added the option to redirect test output to files. Writing to system out isn't always consistent when running tests I've found, but writing to files always is. We can remove that option if you and @vonnieda want.

The path for the GcodeDriverTest, for example, would be in `target/surefire-reports/GcodeDriverTest-output.txt`

**Comment by markmaker** [comment]
Thanks, @Jnesselr 

I think it would be better, if the output was visible again. I never observed any inconsistencies. 

Furthermore, I guess the GitHub Actions that run the tests as well would be hard to diagnose otherwise. 

@vonnieda, what do you think?

_Mark

**Comment by vonnieda** [comment]
Agreed - it should work the way it did before.

Jason

**Comment by Jnesselr** [comment]
Done!

**Pull request merged**
