### PR TITLE
Mjpg camera feature

### PR DESCRIPTION
**Pull request by desertgreg**
# Description
This pull request adds MjpgCaptureCamera and MjpgCaptureCameraWizard to OpenPNP.  This class allows you to use IP cameras which output Mjpg streams.

# Justification
My pick and place machine is using an Mjpg camera for its up camera and this feature should be generally useful for anyone who wants to use one of these cameras.  

# Instructions for Use
In the machine configuration GUI you can add an MjpgCaptureCamera anywhere that you are able to use any other type of camera (e.g. OpenPnpCaptureCamera, OpenCvCamera, etc)
UsingMJPGCaptureCamera

There is currently only one setting which is the IP address and port number to pull the MJPG stream from:
MjpgCaptureCameraSettings

mjpg_camera2

# Implementation Details
1. I have tested the code on my pick and place machine which uses a this type of camera.  I tested editing pipelines on this camera type as well as simply viewing the stream in the OpenPnP gui
2. I used the code formatter and tried to follow the style as closely as possible.
3. No changes to the `org.openpnp.spi` or `org.openpnp.model` packages
4. `mvn test` succeeded without errors.

### CODE REVIEW

**Comment by vonnieda** [comment]
Looks good to me! Could you mention what kind of camera it is so that others can consider the same?

**Comment by desertgreg** [comment]
I am using this kind of camera.  Full disclosure, this is a "smart" camera that my son and I made for robotics competitions.  It has the ability to run OpenCV pipelines but right now I'm just using it as an IP camera.  
https://limelightvision.io/

**Comment by vonnieda** [comment]
Great, thanks @desertgreg!

**Comment by markmaker** [comment]
Hi @desertgreg 

Just wanted to tell you this is great! 

I wanted to test it for #1095 I entered more or less the first online MJPG cam I found, and it worked:

MJPEG Cam

Cool stuff!! 

I changed quite some things, you can follow #1095 to see what and why.

_Mark

**Pull request merged**
