### PR TITLE
Update Rotate.java

### PR DESCRIPTION
**Pull request by cri-s**
# Description
Describe the change in detail. Explain how it works. The better you describe the change the more likely it is to be accepted.

# Justification
because pipeline.getValue was not accepted 

# Instructions for Use
insert prerotate into degrees

This is documentation for a user, not for a developer.

### CODE REVIEW

**Comment by vonnieda** [comment]
You didn't explain the change. What does it do? How does it work? What are the magic numbers?

**Comment by cri-s** [comment]
The magic number is just the text prerotate converted to numeric and
it is for supporting
vision pipelines on openpnp that uses prerotate settings.

2017-06-28 4:45 GMT+02:00, Jason von Nieda <notifications@github.com>:

**Comment by vonnieda** [comment]
@cri-s Quick note for you: I've just merged in the ability to set properties on a pipeline. This can be used to put arbitrary pieces of data on the pipeline for use by stages. You can use this for the function you were using setValue/getValue for. More info here: https://github.com/openpnp/openpnp/blob/develop/CHANGES.md#2017-06-28

**Comment by cri-s** [comment]
You have made impossible to merge closed loop feature and removed for
the user the
possibility to visually check the quality of alignment because you
have not accepted the
single variable, and now you introduce a hash table , ...  that
probably get used to pass
images without deallocating it.

I'm not intend to resubmit code that you alread have declined for
merging just because
you have introducend this hash table.

2017-06-29 5:39 GMT+02:00, Jason von Nieda <notifications@github.com>:

**Comment by vonnieda** [comment]
Suit yourself. I didn't decline your code. I asked a couple questions about it. You then decided to remove the feature entirely.

Code coming in to this project is going to get reviewed, and if there are parts that need explanation I am going to ask questions. If you are not able to handle basic feedback and questions about your code, I suggest you you save us both the trouble and stop submitting it.

**Comment by cri-s** [comment]
Sorry for the maybe harsch comment, i'm still a bit tired for the
story of the pipeline code where you changed mind and we both , at
least i have loose some time for preparing that.

I have give feedback, without having code for a stage ready to submit.
>"It should be removed. If it is required, please commit code that actually uses it"
The PR was for prerotate and with the rounding added, there is very
little difference
to closed loop and without ImageCapture capable of handling bigger
compoennts it is limited to 14mm square devices where closed loop is
unnecessary,
This assuming 22x38mm FOV .


2017-06-29 15:36 GMT+02:00, Jason von Nieda <notifications@github.com>:

**Pull request closed without merging**
