### PR TITLE
Fix/Round-up of Bug-Fixes and some Missing Utility Features

### PR DESCRIPTION
**Pull request by markmaker**
# Description
This is a round-up of bug-fixes and conceptually missing utility features. These have popped up while working on #1164 (which will likely be re-submitted as a new one later). 

## Bug-fixes
* Bug-fix for #1143 (null pointer exception when part is missing in feeder)
* Parts table does not update on part property changes.
* Inconsistent FIRMWARE detection in `GcodeDriverSolutions`.
* Edit Pipeline does not wait for machine in `ReferencePushPullFeederConfigurationWizard`, resulting in the lighting actuator failing.
* Test Alignment in `ReferenceBottomVisionPartConfigurationWizard` did not conserve rotation of selected nozzle.
* Nozzle tip calibration failed the homing cycle if enabled on homing, creating a chicken egg situation during machine setup. Added an option to switch off. Improved error messages. This required  `UiUtils.messageBoxOnExceptionLater()` for deferred GUI tasks (in this case deferred throws/error messages).
* `null` check missing in `AbstractHeadMountable.toHeadLocation()`, refactored/extracted `AbstractHeadMountable.applyConfiguration()` for future use.
* Pipeline stages that throw exceptions are logged for easier diagnostics. The underlying issue that some exceptions should fail the pipeline immediately is still open.
* In the Pipeline Editor: custom `Object` type property sheet handlers need resetting when switching stages.

## Missing conceptual/utility features
* Missing `NozzleTip.home()` for Machine Setup tree topological homing.
* Missing `Length.compareTo()` 
* Missing `Location.getXyzLengthTo()` i.e. length including Z coordinate.
* Added `Location.origin` constant as the (0, 0, 0, 0) coordinate, for easy use in the form `vector.getXyzLengthTo(Location.origin)` to measure vector length.
* Missing `Location.multiply()` similar to the other operations.
* Missing `Head.permutateNozzle()` same as for cameras, Also fixed parameter name in `permutateCamera()`
* Missing `ImageUtils.clone()` to deep copy a `BufferedImage`.

# Justification
This is the first break-out of #1164 trying to implement [this input by @vonnieda](https://github.com/openpnp/openpnp/pull/1164#issuecomment-813675599).

I found it acceptable to put these in one PR as these are almost entirely **one class = one fix** and small (counting class+Wizards as one). 

# Instructions for Use
The only visible change is the new option **Fail Homing?** on the nozzle tip calibration.

Fail Homing

# Implementation Details
1. The bug-fixes were tested in #1164. After extraction just `mvn test`. 
2. Did follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style).
3. Changes in the `org.openpnp.spi` or `org.openpnp.model` packages:  `Head.permutateNozzle()` and `NozzleTip.home()` and `Length` and `Location` additions as documented.
4. Successful `mvn test` before submitting the Pull Request.

### CODE REVIEW

**Comment by vonnieda** [comment]
Nice PR @markmaker - and thank you for taking the time to split it up. It makes it so much easier to review one or two before bed :)

**Comment by vonnieda** [comment]
I'm going to revert this for now because merging it caused conflicts. I'll finish reviewing all of the PRs tomorrow and then merge them in the correct order to avoid conflicts.

**Comment by my-3d-cnc-pnp** [comment]
Hello.  

After loading releases that contain PR#1169 the part test alignment button is behaving differently.
The first time the button is pressed it positions/rotates the part properly centered and squared. 
If I press the button again it adds the original correction angle again and now the part is rotated and no longer squared
Every time the button is pressed it adds the correction angle again and the part rotates more and more.

I reverted the changes of the two lines of code in ReferenceBottomVisionPartConfigurationWizard(see below) and then it works as before.

From the comment in the description of bug fixes in PR#1169:
"* Test Alignment in ReferenceBottomVisionPartConfigurationWizard did not conserve rotation of selected nozzle."
It looks like it is now conserving the rotation properly but also conserves the angular correctional offset

Perhaps there is a problem with my setup of the shared C or something else in my configuration that did not show up before this PR
If a Debug Log or machine.xml file is needed let me know


       public class ReferenceBottomVisionPartConfigurationWizard extends AbstractConfigurationWizard {
          private final ReferenceBottomVision bottomVision;
       @@ -159,7 +156,7 @@ private void testAlignment() throws Exception {

        // perform the alignment
        PartAlignment.PartAlignmentOffset alignmentOffset =     VisionUtils.findPartAlignmentOffsets(bottomVision, part,
-----> Pre  PR#1169       null, new Location(LengthUnit.Millimeters), nozzle);
-----> Post PR#1169       null, new Location(LengthUnit.Millimeters, 0, 0, 0, nozzle.getLocation().getRotation()), nozzle);
        Location offsets = alignmentOffset.getLocation();

        if (!chckbxCenterAfterTest.isSelected()) {
        @@ -168,7 +165,7 @@ private void testAlignment() throws Exception {

        // position the part over camera center
        Location cameraLocation = bottomVision.getCameraLocationAtPartHeight(part, VisionUtils.getBottomVisionCamera(),
------> Pre  PR#1169      nozzle, 0.);
------> Post PR#1169      nozzle, nozzle.getLocation().getRotation());

        if (alignmentOffset.getPreRotated()) {
            // See https://github.com/openpnp/openpnp/pull/590 for explanations of the magic

`

**Comment by markmaker** [comment]
Hi @my-3d-cnc-pnp,

That change was intentional to allow alignment testing at the chosen _nominal_ nozzle angle. Otherwise, you could not actually test alignment at non-zero angles and especially not effectively test the pre-rotate option (i.e. what it does differently). 

The idea is to set the wanted _nominal_ angle with the Jog `C` buttons, then press **Test Alignment**. If you want 0°, just press the `P` button before **Test Alignment**. If you want to test a specific angle, set it using the Jog buttons. 

Jog C

The ability to test Alignment (especially pre-rotate) at various angles is useful both for developers and for users, I was missing it many times in both situations. 

Furthermore, when a part height is unknown, the auto-focus (see #1171) can now sense it in Alignment, and it is important that no unnecessary rotation takes place when doing so, therefore it was again useful for testing. 

Do you think this is very confusing? I could instead add a "Test angle" field to the GUI. 

Just to point out: the change was documented, see the Description of both the original PR #1164 ...
> * Test Alignment GUI action now uses the current nozzle rotation angle (to test pre-rotate + Auto-focus).
... and #1169 (this one):
>* Test Alignment in ReferenceBottomVisionPartConfigurationWizard did not conserve rotation of selected nozzle.

_Mark

**Comment by markmaker** [comment]
Improved it here:
#1203
_Mark

**Comment by markmaker** [comment]
@my-3d-cnc-pnp, 
a new version was deployed. Please upgrade and test. 
Much appreciated, thanks.
_Mark

**Comment by my-3d-cnc-pnp** [comment]
Upgraded and tested.  Now works as expected. Perfect!

The addition of the "Test Angle" field makes the new feature obvious and the "angle" variable in the code fixed the error accumulation that confused me.
What software do you use/recommend to make the video captures like the one in the description of  the new PR#1203?
My explanation would have been much clearer if I had included one.

Thank you as always
Peter

**Comment by markmaker** [comment]
> What software do you use/recommend to make the video captures like the one in the description of the new PR#1203?

I'm using a very old Camtasia version to record from screen. I'm sure there are better/free solutions available nowadays. It just creates a video of what happens on the screen. 

Then I use a special [ffmpeg](https://ffmpeg.org/) command line to convert to `.gif`, so I get a small file that I can upload easily and that embeds as animation.

On Windows I put the following in `convert_gif.cmd`. 

```
ffmpeg -i %1 -filter_complex "[0:v] split [a][b];[a] palettegen [p];[b][p] paletteuse"  %1.gif
pause
```

So I can drop files to convert on it. Obviously, `ffmpeg` must be in the path _or_ in the same directory as the `.cmd`.

_Mark

**Pull request merged**
