### PR TITLE
Icons

### PR DESCRIPTION
**Pull request by dzach**
Branch with ongoing work in icons. See src/main/resources/icons/. See #421 . Should be deleted as soon as icons become final.

### CODE REVIEW

**Comment by vonnieda** [comment]
Looking very good @dzach. If I understand correctly, this is still in progress and you do not want me to merge anything right now, right?

**Comment by dzach** [comment]
Right. I pushed this so that you can try the icons, if you want.

**Comment by vonnieda** [comment]
I pulled in the icons and tried them in the program. I think they make things MUCH more clear:

screen shot 2017-01-25 at 9 28 39 am

screen shot 2017-01-25 at 9 28 53 am

It really jumps out to me now what each one does. I think this is a great improvement!

**Comment by dzach** [comment]
I've finished refining the icons. I'm closing this pull request and will open a new one with the finished icons.

**Pull request closed without merging**
