### PR TITLE
Feature / Advanced Motion Control - Update 7

### PR DESCRIPTION
**Pull request by markmaker**
# Description
This is Update 7 of the [`advanced-motion-control`](https://github.com/openpnp/openpnp/issues?q=label%3Aadvanced-motion-control) series.

This is intended to be the last PR in the `testing` branch.

## Features

- Bug-fix: Rotation coordinates (angles) must not be length unit converted to/from driver units in the GcodeDriver. 
- The homing command for TinyG must name the axes to be homed (Gcode suggested by Issues & Solutions).
- Cosmetic color change in Issues & Solutions. "Fundamental" issues are now blue rather than scary red. They are _important_ and _fundamental_ but they should not be _alarming_ in any way. 

# Justification
See also:
https://groups.google.com/g/openpnp/c/ObzQGzK5HW0/m/NgM3ahU0AwAJ

# Instructions for Use
- [General Advanced Motion Control documentation keeps getting linked here](https://makr.zone/openpnp-advanced-motion-control/553/)

# Implementation Details
1. Testing with the mixed three controller test rig. The driver unit conversion bug-fix cannot reliably be tested, I hope [Florian](https://groups.google.com/g/openpnp/c/ObzQGzK5HW0/m/NgM3ahU0AwAJ) will do that ASAP. 
2. Did follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style).
3. No changes in the `org.openpnp.spi` or `org.openpnp.model` packages.
4. Successful `mvn test` before submitting the Pull Request.

### CODE REVIEW

**Comment by vonnieda** [comment]
Hi @markmaker - do you have plans to update the Setup and Calibration pages for the advanced motion control changes? If not, mind if I work on it?

Thanks,
Jason

**Comment by markmaker** [comment]
Hi @vonnieda 

Well, I was aware that I needed to somehow weave the separate Wiki bloc into the existing documentation. I actually wanted to ask you how...

1. whether the "old" OpenPnP 2.0 documentation can simply be overwritten or ...
2. whether we want to create separate sections on the pages like for OpenPnP 1.0, perhaps renaming the new version into OpenPnP 2.1 for easy distinction.

... but I wanted to wait until the new version has proven itself a while (so we could still go back in the worst case, without losing any Wiki doc). 

I certainly don't mind if you go ahead and lead the way! 

And please feel completely free to restructure and change my stuff and especially the language. It is still very much a "forceps delivery" for me to formulate all this in English, and I'm sure it shows.

_Mark

**Comment by markmaker** [comment]
Hi @vonnieda 

I inserted the [Machine Axes chapter](https://github.com/openpnp/openpnp/wiki/Machine-Axes) into the [Setup and Calibration](https://github.com/openpnp/openpnp/wiki/Setup-and-Calibration) flow. Plus I added some links from the most important topics in the existing Wiki. 

Examples:
https://github.com/openpnp/openpnp/wiki/GcodeDriver%3A-Axis-Mapping#defining-axes
https://github.com/openpnp/openpnp/wiki/GcodeDriver#backlash-compensation
https://github.com/openpnp/openpnp/wiki/GcodeDriver#visual-homing

This should prevent users from getting stuck in old version instructions ([like in this example](https://groups.google.com/g/openpnp/c/yRFRv25pflU/m/vDxIYs6gBgAJ)).  

> mind if I work on it?

Are you working on an offline copy in parallel? 

If yes: my changes are mostly superficial/provisional, so you can just ignore them in case of revision conflicts. 

In order to make this more user-friendly and less of a "versioning mess", the [questions I asked above](https://github.com/openpnp/openpnp/pull/1082#issuecomment-747600753) remain, though. 

_Mark

**Comment by vonnieda** [comment]
>     1. whether the "old" OpenPnP 2.0 documentation can simply be overwritten or ...

Yea, this is tricky. Had the same problem with 1.0. I wish Github Wikis supported branches!

>     2. whether we want to create separate sections on the pages like for OpenPnP 1.0, perhaps renaming the new version into OpenPnP 2.1 for easy distinction.
> 

I think we should just go ahead and update the docs to reflect the current code. The Wikis are all versioned, so if someone really needs to go back in time they can. I will work on exporting a PDF of the Wiki as of 1.0 and 2.0 prior to Advanced Motion Control.

> ... but I wanted to wait until the new version has proven itself a while (so we could still go back in the worst case, without losing any Wiki doc).

I think we can go ahead. I don't see any way we're reverting your changes. They are too good :) 

> Are you working on an offline copy in parallel?

I never got around to it. I've been working on some retry changes. So please feel free if you have more to do.

Thanks,
Jason

**Comment by markmaker** [comment]
> I wish Github Wikis supported branches!

Hmmm... but I guess it could at least be forked?

grafik

So you could perhaps add a new repo "openpnp_stable_wiki" etc. and then push a clone into this one:

https://stackoverflow.com/a/56480628

So it could remain editable, which I guess would make sense at least as long as the stable version remains at OpenPnP 1.0.

> I will work on exporting a PDF of the Wiki as of 1.0 and 2.0 prior to Advanced Motion Control.

Yes PDFs are a very good idea too!

> I think we should just go ahead and update the docs to reflect the current code. The Wikis are all versioned, so if someone really needs to go back in time they can.

Just to be very clear: Do you mean to remove/overwrite any OpenPnP 1.0 specific documentation too? 

It would be the most user-friendly option, obviously.

_Mark

**Comment by vonnieda** [comment]
On Wed, Dec 30, 2020 at 4:53 AM markmaker <notifications@github.com> wrote:

> I wish Github Wikis supported branches!
>
> Hmmm... but I guess it could at least be forked?
>
> [image: grafik]
> <https://user-images.githubusercontent.com/9963310/103346514-7d231b00-4a94-11eb-8408-894ef59aca41.png>
>
> So you could perhaps add a new repo "openpnp_stable_wiki" etc. and then
> push a clone into this one:
>
> https://stackoverflow.com/a/56480628
>
> So it could remain editable, which I guess would make sense at least as
> long as the stable version remains at OpenPnP 1.0.
>
> I will work on exporting a PDF of the Wiki as of 1.0 and 2.0 prior to
> Advanced Motion Control.
>
> Yes PDFs are a very good idea too!
>
> I think we should just go ahead and update the docs to reflect the current
> code. The Wikis are all versioned, so if someone really needs to go back in
> time they can.
>
> Just to be very clear: Do you mean to remove/overwrite any OpenPnP 1.0
> specific documentation too?
>

Yep, I think it's time. Now that retry is fixed I'm going to be pushing
people to get off 1.0. For legacy users I'll export PDFs or a static copy
of the docs at a previous revision.

Jason

It would be the most user-friendly option, obviously.

**Pull request merged**
