### PR TITLE
Fix/Part-Off detection: Read vacuum level before valve closes.

### PR DESCRIPTION
**Pull request by markmaker**
# Description
Fixes my own #991 for Advanced Part-On/Part-Off Detection.

During Part-Off checks this re-establishes the possibility to read the vacuum level _before_ the valve closes again. The behavior was mistakenly changed when the Probing close-time was added to compensate for signal delays. 

# Justification
For machines with slow connections and/or fast-changing vacuum signals, this breaks the previous behavior. 

grafik
(Screenshot by @doppelgrau)

On my machine this was invisible during testing due to fast connection/sluggish vacuum signal.

See also:
https://github.com/openpnp/openpnp/pull/991#issuecomment-627239863

# Instructions for Use
Set the Probing close-time to 0 (see screenshot). Check if Last Reading corresponds to a curve point, where the level is not yet decaying again.

# Implementation Details
1. I hope @doppelgrau can test this.
2. Did follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style).
3. No changes in the `org.openpnp.spi` or `org.openpnp.model` packages.
4. Successful `mvn test` before submitting the Pull Request.

### CODE REVIEW

**Comment by markmaker** [comment]
@doppelgrau 

I hope you can test this.

You can checkout my branch. In case you're not familiar (I wasn't until recently) see the "command line instructions" link above and do **Step 1** only:

grafik

Hope you see the same thing at your end. Otherwise just use these commands (after having committed/stashed whatever you are working on):

```
git checkout -b markmaker-fix/absolute-part-detect-read-before-off develop
git pull https://github.com/markmaker/openpnp.git fix/absolute-part-detect-read-before-off

```

_Mark

**Comment by doppelgrau** [comment]
git remote add markmaker git@github.com:markmaker/openpnp.git
git pull markmaker fix/absolute-part-detect-read-before-off

Build it, seems fine. Vacuum now read back as expected. Thanks for fixing it.

**Comment by vonnieda** [comment]
@markmaker This looks good to me, but I'm not sure if you are ready to merge or not. If you are, go ahead.

**Comment by markmaker** [comment]
Hi @vonnieda 

Thanks. 

As @doppelgrau has tested it, I'll merge it. 

_Mark

**Pull request merged**
