### PR TITLE
Script Example using Python/Jython engine of OpenPnp

### PR DESCRIPTION
**Pull request by ldpgh**
# Description
This PR adds small examples using the Python/Jython script engine in OpenPnP to control the machine respective the OpenPnP GUI.
The files are placed in a directory called Python.

# Justification
There are just examples for Javascript. Some Python files seem to be a good idea.

# Instructions for Use
All files can be called from the GUI pulldown-menu (Scripts/ ... comments were added to the Script files.
It's recommended to look into the RUN_* files before the script gets executed.
* The CMD_* files are intended to become familiar with the script engine and interact with the Log-TAB.
* The RUN_* files are moving the PnP machine.

This is documentation for a user, not for a developer.

# Implementation Details
1. How did you test the change?
- Manual testing ... running on my PnP-machine.
- Starting the script and check the output to the Log-TAB respective the behavior of the PnP .machine.
2. Did you add automated tests?
- No
- Just manual testing ... see 1.
3. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)?
It's Python with it's own constraints
- 2 chars (spaces) indent used
- no TAB's
- Real functions are camelCase
- Local variables/functions use underline separation
4. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing.
- No changes

### CODE REVIEW

**Comment by vonnieda** [comment]
Hi @ldpgh,

Thanks for the contribution, but a few changes are needed to merge:

1. Please put the scripts in the Examples directory: https://github.com/openpnp/openpnp/tree/develop/src/main/resources/scripts/Examples
2. Please update the example scripts code so that they are installed automatically on new installations: https://github.com/openpnp/openpnp/blob/develop/src/main/java/org/openpnp/Scripting.java#L78
3. Please rename the files more similarly to how the existing Example scripts are named, and be descriptive in the names. For instance, CMD_clear_log_tab.py can be Clear_Log_Tab.py, RUN_unload_nozzle.py can be Unload_Current_Nozzle.py, etc. The names should indicate what will happen and use proper capitalization so that they look nice in the menu.

**Comment by ldpgh** [comment]
Unfortunately an additional PR for issue #379 has been placed by Github into this PR  (example files).

**Comment by ldpgh** [comment]
Unfortunately an additional PR for issue #379 has been placed by Github into this PR  (example files).

**Comment by vonnieda** [comment]
Thanks @ldpgh, I am working on merging this. Note, you should update your code. It looks like you wrote the example scripts using an older codebase, and the log clear one doesn't work anymore. I'm fixing that and will merge once it's all fixed. Please don't push any new commits to this branch for now.

**Comment by vonnieda** [comment]
Hi @ldpgh, thank you for the PR. These are two very nice additions. 

I had to remove some of the script examples temporarily due to some problems, but if you fix them up and submit a new PR I will include them. The issues were:
* Clear_Log_Tab.py: Does not work with current code because the log elements are in a JList, not a JTextPane.
* Tool_Changer_All_Nozzle_Tips.py: Any script that moves the machine should use the submitUiMachineTask interface. See https://github.com/openpnp/openpnp/blob/develop/src/main/resources/scripts/Examples/JavaScript/Utility.js for how this is done from JavaScript scripts. Python ones will need to do something similar. This keeps machine operations from happening out of order, or when the machine is not enabled and also helps report errors to the user.
* Unload_Nozzle.py: Same as above, must use submitUiMachineTask.

**Pull request merged**
