### PR TITLE
Fixed a number of bugs, including the second side importing not placing pads correctly

### PR DESCRIPTION
**Pull request by DouglasPearless**
rewrote some of the code and fixed the mirroring onto the second side.

If you modify you machine.xml cameras tags to be:

            <cameras>
               <camera class="org.openpnp.machine.reference.camera.ImageCamera" id="d66faf53-05e1-4629-baae-b614c5ed8320" name="C1" looking="Down" rotation="0.0" flip-x="false" flip-y="false" fps="24" width="640" height="480">
                  <units-per-pixel units="Millimeters" x="0.04233" y="0.04233" z="0.0" rotation="0.0"/>
                  <vision-provider class="org.openpnp.machine.reference.vision.OpenCvVisionProvider"/>
                  <head-offsets units="Millimeters" x="0.0" y="0.0" z="0.0" rotation="0.0"/>
                  <source-uri>classpath://samples/EAT001/EAT001.png</source-uri>
               </camera>
               <camera class="org.openpnp.machine.reference.camera.ImageCamera" id="d66faf53-05e1-4629-baae-b614c5ed8320" name="C2" looking="Up" rotation="0.0" flip-x="false" flip-y="true" fps="24" width="640" height="480">
                  <units-per-pixel units="Millimeters" x="0.04233" y="0.04233" z="0.0" rotation="0.0"/>
                  <vision-provider class="org.openpnp.machine.reference.vision.OpenCvVisionProvider"/>
                  <head-offsets units="Millimeters" x="0.0" y="0.0" z="0.0" rotation="0.0"/>
                  <source-uri>classpath://samples/EAT001/EAT002.png</source-uri>
               </camera>
            </cameras>

and in Eagle:
(1) File->Export->Image the top side as (turn off the bottom copper layer) EAT001.png and then 
(2) File->Export->Image the bottom side as EAT002.png, (turing off the top copper layer) then you can swap between the camera to view the top and bottom of the boards as if you have loaded these into the FPD.

Note, you be able to simulate the pick and paste of the bottom layer, while you can select the second camera, you have to manually change the layer from bottom to top in the solder paste tab as the logic to automatically handle this has not yet been written.

Subject to any other bugs being discovered, we only now need polygons to be written to complete the Eagle importer.

Cheers
Douglas Pearless.

### CODE REVIEW

**Comment by DouglasPearless** [comment]
Slight change in instructions; do NOT flip the image in the machine.xml file:          

  <cameras>
               <camera class="org.openpnp.machine.reference.camera.ImageCamera" id="d66faf53-05e1-4629-baae-b614c5ed8320" name="EagleTop" looking="Down" rotation="0.0" flip-x="false" flip-y="false" fps="24" width="640" height="480">
                  <units-per-pixel units="Millimeters" x="0.04233" y="0.04233" z="0.0" rotation="0.0"/>
                  <vision-provider class="org.openpnp.machine.reference.vision.OpenCvVisionProvider"/>
                  <head-offsets units="Millimeters" x="0.0" y="0.0" z="0.0" rotation="0.0"/>
                  <source-uri>classpath://samples/EAT001/EAT001.png</source-uri>
               </camera>
               <camera class="org.openpnp.machine.reference.camera.ImageCamera" id="d66faf53-05e1-4629-baae-b614c5ed8320" name="EagleBottom" looking="Down" rotation="0.0" flip-x="false" flip-y="false" fps="24" width="640" height="480">
                  <units-per-pixel units="Millimeters" x="0.04233" y="0.04233" z="0.0" rotation="0.0"/>
                  <vision-provider class="org.openpnp.machine.reference.vision.OpenCvVisionProvider"/>
                  <head-offsets units="Millimeters" x="0.0" y="0.0" z="0.0" rotation="0.0"/>
                  <source-uri>classpath://samples/EAT001/EAT002.png</source-uri>
               </camera>
            </cameras>

and in Eagle:
(1) File->Export->Image the top side as (turn off the bottom copper layer) EAT001.png and then 
(2) File->Export->Image the bottom side as EAT002.png, (turing off the top copper layer) *AND THEN USE YOU FAVOURITE IMAGE EDITOR TO FLIP THE IMAGE LEFT_TO_RIGHT (that is horizontally) then you can swap between the camera to view the top and bottom of the boards as if you have loaded these into the FPD.

Note, you be able to simulate the pick and paste of the bottom layer, while you can select the second camera, you have to manually change the layer from bottom to top in the solder paste tab as the logic to automatically handle this has not yet been written.

Subject to any other bugs being discovered, we only now need polygons to be written to complete the Eagle importer.

Cheers
Douglas Pearless.

**Comment by DouglasPearless** [comment]
Hmm, it says there is a conflict with my b4c9ffd merge but I cannot see what the conflict is to fix.

**Comment by vonnieda** [comment]
Looks like the conflict is just in the imports. Easiest way to test for this before submitting a pull request is to merge/pull OpenPnP develop into your branch. This makes sure that you are up to date before submitting the request and will also highlight any conflicts so you can fix them before requesting.

Just do a `git pull https://github.com/openpnp/openpnp.git develop` and it should come up.

**Comment by cri-s** [comment]
Can you submit the pull request to cri-s/openpnp too. Don't worry if there is no solderpaste processor. I update the branch today and it have support for Panel and bottom side assembly, but different job file format.

**Comment by vonnieda** [comment]
@DouglasPearless Hi Douglas, what is the status of this pull request? Last comment was there was a conflict but that seems to be resolved. Do you want this merged in, or is this code unfinished?

**Comment by DouglasPearless** [comment]
Ah sorry,

I believe I fixed the conflict and was all done :-)

**Pull request merged**
