### PR TITLE
Introducing a Signaler interface and a SoundSignaler Implementation releated to #244

### PR DESCRIPTION
**Pull request by pfried**
This is a first idea of a Signaling interface. A `Signaler` should signal certain States of the Machine or the JobProcessor like errors or job finish.

Note: The is no machine error yet. The implementation does signal a job finish and a job error only right now. Befor i do the grunt work and implementing an `ActuatorSignaler` i wanted to first show a first draft of the Signaler interface.

Signaler has two  methods : `signalMachineState`, `signalJobProcessorState`

Added a State in the `AbstractJobProcessor` and in the `AbstractMachine` to signal states to the Signalers

One Problem here: The machine property is not available in the `AbstractJobProcessor`, so we need to call it from the Implementations with the signalers.

`SoundSignaler` plays .wav files (Files from https://www.freesound.org under Creative Commons, https://creativecommons.org/licenses/by/3.0/)

Note: Plays sound on Tests (how to disable this)?

### CODE REVIEW

**Comment by pfried** [comment]
related #244

**Comment by vonnieda** [comment]
@pfried I think this looks really good. A few small notes:

* WRT your comment "The machine property is not available in the AbstractJobProcessor, so we need to call it from the Implementations with the signalers.": You can always get the machine from Configuration.get().getMachine(), but the way you've done this is fine too.
* Can you create a short Wiki page explaining how to use and configure this feature? It doesn't need to be in depth. Basically just something I can link to people who ask about the feature. I suspect the two biggest questions will be "How do I disable the sounds?" and "How do I change the sounds that get played?". Page can go here: https://github.com/openpnp/openpnp/wiki/Signalers

Thanks!

**Comment by pfried** [comment]
I actually tried to make the path configurable, but i kind of failed since accessing a path seems not be as easy as accessing a resource file across different OS. Do you know an easy way to do this? In the installation (packaged installation) there is no more resource folder, so it cannot be replaced there.

I also thought about removing the sound files completly to avoid licensing / attribution issues.

I created the Wiki Article altough there is not much to it.

**Comment by tracklogic** [comment]
I like this... i need to enable this functionality with the feeder slot interface (other pull request), so can trigger an alert when a feeder needs changing - although as this is a feeder exception, it will probably all be magically caught and triggered

I've fancied putting one of those fancy traffic lights on my pnp like the bigger machines have, these normally have a built in buzzer, so having a signal interface that can trigger an output would be cool - probably via a gcode command that would enable a FET/relay to driver the buzzer.

**Comment by vonnieda** [comment]
Take a look at ImageCamera.initialize and ImageCamera.sourceUri:
https://github.com/openpnp/openpnp/blob/develop/src/main/java/org/openpnp/machine/reference/camera/ImageCamera.java#L151

These show how to allow the user to set a classpath resource, Internet URI
or local File as a loadable resource. Should be able to use the same idea
here.

Jason

**Comment by vonnieda** [comment]
@pfried Thanks for creating the Wiki! Please consider making the audio file paths configurable as I mentioned in the comment above, but for now this looks great and I will go ahead and merge it. Thanks for the contribution!

**Comment by pfried** [comment]
I will, when i find some time i will make them configurable and i will also provide a ActuatorSignaler, so we can have the initial idea with external lights and horns

**Pull request merged**
