### PR TITLE
JDK17 and MacOS Support

### PR DESCRIPTION
**Pull request by vonnieda**
This finishes up JDK17 support #1493 by @lags.

In addition to @lags work on https://github.com/openpnp/openpnp/issues/1361 and https://github.com/openpnp/openpnp/issues/1363, this fixes MacOS support for x86 and Apple Silicon, and fixes Github Actions for all platforms.

### CODE REVIEW

**Comment by markmaker** [comment]
Awesome progress! 

This Java+Native stuff was always the "scary" part for me, so I'm so glad you took it back under your wing 😁

_Mark

**Review by markmaker — APPROVED** [review]

**Comment by ian-arkver** [comment]
Thanks @vonnieda for this work. Nice to see the "All checks have passed" green tick and no more Java 8.

Also, I enjoy your "poke-CI-to-make-it-rebuild" commit messages. :-)

**Comment by ian-arkver** [comment]
Hi Jason @vonnieda ,

It seems the OpenPnP script built by Install4J doesn't include the "opens" JVM flags to make it work with newer JRE/JDK.

See: https://groups.google.com/g/openpnp/c/RXTHbraZ53g

All the best,
Ian

**Comment by vonnieda** [comment]
Thanks @ian-arkver - looking into this today.

**Comment by vonnieda** [comment]
Okay, those changes are in test but not yet develop. I think the user in that post was using develop.

Here are the flags: https://github.com/openpnp/openpnp/blob/test/OpenPnP.install4j#L63

Jason

**Comment by ian-arkver** [comment]
I can confirm that the Install4j built test version works out of the box. Good job!

CU
Ian

**Comment by gxurma** [comment]
Hi!
Fresh clone of openpnp does not survive the tests. it gives error.
Gives again  the not able to write machine.xml failure.
even with fixing it with the --add-opens stuff.

Any suggestions?

Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)
Maven home: d:\Programs\apache-maven-3.9.4
Java version: 18, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-18
Default locale: de_AT, platform encoding: UTF-8
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Pull request merged**
