### PR TITLE
Optimize / Cleanup ReferenceHeadMountable

### PR DESCRIPTION
**Pull request by prusk**
# Description
Ran into the ReferenceHeadMountable by accident and noticed how it doesn't make sense to exist:
* Reference machine area only has classes except this interface
* ReferenceHeadMountable is used in AbstractHeadMountable in spi and no Abstract class in spi should make use of any Reference classes
* the HeadOffsets should actually belong to HeadMountable in `org.openpnp.spi`, not to a Reference class

# Justification
Cleanup / optimization

# Instructions for Use
n/a

# Implementation Details
1. How did you test the change? Be descriptive. Untested code will not be accepted.
Tested with simulation machine and on my own Pandaplacer
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)?
Yes
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing.
HeadMountable was extended to include the methods in ReferenceHeadMountable - I'm actually wondering why they were missing
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted.
Done

### CODE REVIEW

**Comment by prusk** [comment]
@markmaker what do you think?

**Comment by markmaker** [comment]
Hi @prusk, 

I agree with the design rationale. @vonnieda, any objections?

However, there are now some search&replace artifacts. You are testing `instanceof` and casting to `HeadMountable`, where the object already _is_ a `HeadMountable`. This should be cleaned up.

_Mark

**Comment by prusk** [comment]
> However, there are now some search&replace artifacts. You are testing `instanceof` and casting to `HeadMountable`, where the object already _is_ a `HeadMountable`. This should be cleaned up.

Please point it out and I'll clean it up. Nothing sticks out for me at the moment.

**Comment by markmaker** [comment]
Just search for `(HeadMountable)` and then for `instanceof HeadMountable`.

Two examples:

https://github.com/openpnp/openpnp/blob/4b6c1fae09f093b1f1f839e01c5e4da84955990b/src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java#L269

https://github.com/openpnp/openpnp/blob/4b6c1fae09f093b1f1f839e01c5e4da84955990b/src/main/java/org/openpnp/machine/reference/ReferenceNozzle.java#L271

These are unnecessary, as `hm` is always already of type `HeadMountable` due to where it came from. Also in this case no need for the extra variable `otherHeadMountable`.

And there are more like that.

_Mark

**Comment by prusk** [comment]
Only found stuff that needed cleanup in ReferenceNozzle and AbstractMotionPlanner.
I searched for `instance HeadMountable`, `(HeadMountable)` and `HeadMountable`.

There is a conversion in ReferenceNozzle from Camera to HeadMountable and it makes sense to me...

**Comment by vonnieda** [comment]
> Hi @prusk,
> 
> I agree with the design rationale. @vonnieda, any objections?
> 
> However, there are now some search&replace artifacts. You are testing `instanceof` and casting to `HeadMountable`, where the object already _is_ a `HeadMountable`. This should be cleaned up.
> 
> _Mark

Looks good to me. I think ReferenceHeadMountable is an old artifact. I took a look at it's history and it didn't really have a reason for being. 

Thanks,
Jason

**Comment by markmaker** [comment]
Thanks, @vonnieda , @prusk,

looks good to me. Ready to merge?

_Mark

**Comment by prusk** [comment]
Ready to merge.

**Comment by markmaker** [comment]
Thank you @prusk :rocket:

**Pull request merged**
