### PR TITLE
added dwell on drivers for timing on gcode executor (microcontroller) instead of PC, 

### PR DESCRIPTION
**Pull request by cri-s**
I have not touched the driver behavior , it's still uses the "new" driver
model where the move must complete before call returns from moveTo .
I have only added code that if removing that, other timing code works.

Introduced driver dwell for not "old" driver model where commands
are asyncron and . 
The advantage is, that timing is not depend on PC, but are timed by microcontroller and this allow faster execution and less poblems with camera timing.
Further GCode interface and Msg interface was added. The intended purpose
beside switching coordinates on some JobPlanner is for test and setup purposes.
As example, automatic test sequences that move machine and test accuracy
increasing feed rate or acceleration automatically.
For drivers, as example the Firepick driver, the support is missing,
there have the own tests. For other drivers, it should work.
In the case you discover driver wait seconds instead of milliseconds,
the code inside dwell need to be changed. I have checked several driver docs,
but not double checked.

### CODE REVIEW

**Comment by vonnieda** [comment]
There are a number of problems with this pull request:

1. I will not accept the GCode() API. I explained to you that if you want an API like this we can add something generic such as sendCustomCommand(Object) but I'm not adding a GCode specific command.
2. The Msg() API is not documented and does not follow the code style.
3. There are changes to many other unrelated files. Location and Part are examples.
4. I have explained repeatedly that the driver model as it is designed requires blocking commands. I understand that you want to change this but you have not provided good justification for doing so and you have not presented readable, documented code that shows why the change is useful.

As I said in our original discussion, I do not feel this is a useful change. You have not shown me what it is used for. You said "As example, automatic test sequences that move machine and test accuracy
increasing feed rate or acceleration automatically." but that is something that is easily done in your own driver class. It does not require an API change that changes how the entire driver model works.

**Comment by vonnieda** [comment]
This pull request is in relation to the discussion on #189

**Comment by cri-s** [comment]
As GCode is Industry standard, and basically all drivers that drive
carteisan machines
    can process it, some more , some less, but there is definitive
commune standard with
    exception of the dwell gcode parameter (seconds or milliseconds).
    If you prefer name it sendCustomCommand(String Object) for me it's same.

Msg() API , is not documented, right. On the other side, it should be
undocumented, as
    it returns the output of gcode controller, and it's output is
valid only if no other commands
    is given. Probably the only real usage could be a terminal window
to the controller for
    setting it up or diagnosting problems, or for loading and saving
configuration of the controller. Further it could be useful to display
the result lines of the gcode controller on the
   status bar. If Softlimit or Hardlimit happen, or if the controller
have some Alarm actually
   OpenPnP ignores that and it would by handy if the error or ok
status is displayed on status bar, at least for moves limited to n
Chars.

3) This is right, Part and location is from JobPlanner experiments,
location to for  get() i think. I remove it.

4) To clearify, Gcode could run without blocking on every command. I
don't want change
    the driver to non blocking for now , that can be done on custom
version, but if one want to
    drive it without blocking on every comand,
    then timing must be done on gcode microcontroller and not on PC.
    As the software grows, more timing are introduced, and i just want
ensure, that if one want
    run the driver where it's not blocking,  then
    it should work, and not need changing all drivers and changing all
code that is timing
    sensible, beacaus it's not small changes. This adds to the changes
need for camera,
    illumination, and other things.
    The reason i want run it without blocking on every command is
principally faster assembly. The most impact is when using uplooking
camera without closing loop.
    The head moves over camera, wait the time need for aquiring image,
about 35ms,
    then moves to intermediary destination, and during that the pc
calc the offsets and emit
    the final coordinates. If doing timing on PC, then ok, image calc
needs 350ms, aquisistion
    needs 350ms, just the image processing adds 0.8 second delay, not
calculated the delay
    for usb rs232 transmitter, delay on the gcode interpreter , pc
rs232 buffer, pc task switching.
    The problem is, if you develop control code without using dwell()
and using Thread.sleep()
    then one have to change all that code for changing to non blocking driver.
    On non blocking driver, pick and place are blocking, the rest
returns immediatly.

I have considered not submitting GCode and Msg , but the missing
status line, and
the usefullness of separate setup program have convinced me to tray to
submit it.

As alternative could you consider using the code inside MovingUtils
for dwell instead of
ThreadSleep inside timing code. On custom versions, one could do
  Configuration.get().getMachine.get()Driver.dwell(); if that is not a
problem with static  .



2016-01-15 16:53 GMT, Jason von Nieda <notifications@github.com>:

**Comment by la3pna** [comment]
The problem as I see it is that you want to move from the "block untill complete" to a "checking for completion" sounds like its a major task, requiring a rewrite of quite a major part of the code. This has the posibility to break quite a lot of function and would require a large effort, for little gain. 

The code GCode("G4 P"+double); will return different number depending on locale, here it would be "G4 P1,0" instead of the intended "G4 P1.0". There is a lack of rigidity in the code that is going to be neccessary in order for this to be useable for more than a single person.

**Comment by cri-s** [comment]
good catch. For such applications i prefer settings locale on main and
not use local locale.
Principally i need that timing is made by gcode microcontroller and not by pc.
That don't break a lot of code. Because of this, i have feelt it's
simpler to have
camera.dwell() too as everywhere call driver or annother internal
function, but as said , that
can be one alternative.



2016-01-15 19:41 GMT, Thomas S. Knutsen <notifications@github.com>:

**Comment by vonnieda** [comment]
Hi @cri-s, I've given this some thought. I think the advanced functionality we can get by adding asynchronous moves is valuable, but I don't like the API being so Gcode specific. In addition, I want to have a better way to delineate when a move is complete. Let me think on this a few more days and I will let you know.

**Pull request closed without merging**
