### PR TITLE
Added "placed" checkbox in pick and place job panel

### PR DESCRIPTION
**Pull request by sp-apertus**
# Description
Added a new checkbox to each component to be placed in the "Pick and Place" Tab of a board. 

# Justification
If a component is miss picked or skipped there is currently no way to see these is the component list. Now with the "placed" checkbox its easy to see which parts have been placed and which not. Also components that have successfully been placed will not be placed anymore in the next run.

I know the job processor is currently undergoing a major rewrite so things might already be diffferent behind the scenes - still I consider this is a small addition that would be extremely useful in operation.

# Implementation Details
1. How did you test the change? 
Tested with nulldriver simulated machine.

mvn test completed successfully

Real world test would be appreciated, I will get to our machine on Monday to test it.

openpnp-placed

### CODE REVIEW

**Comment by KarlZeilhofer** [comment]
Thank you for your contribution, seems to be a very useful feature. 
Is the checkbox automatically set on a placement?
Is the state saved in the job xml?
How would you normally use this checkbox?

**Comment by sp-apertus** [comment]
> Is the checkbox automatically set on a placement?
yes:  line 731 in src/main/java/org/openpnp/machine/reference/ReferencePnpJobProcessor.java

> Is the state saved in the job xml?
yes

> How would you normally use this checkbox?
Please elaborate further.... 

I will add being able to reset all "placed" checkboxes through the right click menu when you start populating a new board tomorrow.

**Comment by KarlZeilhofer** [comment]
this seems to be very, very useful! Thumbs up for a merge!

**Comment by sp-apertus** [comment]
Thanks :)

**Comment by sp-apertus** [comment]
Right click menu to change "placed" status of multiple lines done.

**Comment by cri-s** [comment]
As I have similar thing for years using drop down instead of checkboxes ,  and it seems    to me that you don't store it inside job.XML but inside board.XML, same as me, to tell you that this is incompatible with Panelization. The reason is that for Panelization, it refers to the same board file and dataset and doing panelisation, I need to copy the board file for each sub-pcb in order to decouple that status field from different PCB inside one panel.
There exist other possibility to do it, of course

**Comment by vonnieda** [comment]
I won't be able to look at this till Monday, but if it is being set on
Board it will not work in a job where multiple copies of the same board are
used. The object is shared, so setting it on one will set it for all.

**Comment by sp-apertus** [comment]
> As I have similar thing for years using drop down instead of checkboxes

Interesting, why didn't you commit it?

> store it inside job.XML but inside board.XML
Right, indeed.

Any suggestions how to fix that?

**Comment by vonnieda** [comment]
Sebastian, I'd ask that you don't spend anymore time on this till I am back
on Monday. This is a big part of the job processor rewrite I've been
working on for months and I've put a lot of thought into how I want to
store placement status. I'm more than happy to collaborate on it, but I am
on vacation right now and can't do that till I get back.

**Comment by sp-apertus** [comment]
Great, lets chat on Monday!

**Comment by cri-s** [comment]
It have send to @vonnieda and discussed with him using email about
more then one time.
The orginal  implementation was from @Ami .and @vonnieda helped to
update the status of placing during job inside table and not only
after have paused/stopped the job.
There was a table update/display issue where i was not able to
understand  the reason
at that time.








2017-08-25 14:42 GMT+02:00, Sebastian Pichelhofer <notifications@github.com>:

**Comment by vonnieda** [comment]
Closing this as it will not be merged in the form it's in now. Discussed with @sp-apertus on IRC.

**Pull request closed without merging**
