### PR TITLE
UI translation improvements (continued)

### PR DESCRIPTION
**Pull request by VSSavin**
Hi all!

This PR is a continuation of the PR #1496. All changes have been merged with the 'test' branch. All conflicts have been resolved.

# Description
* The 'Translations' class has been changed. Added and used `static class UTF8Control extends ResourceBundle.Control` to use UTF8 encoding directly in editors for .properties files.
* Everywhere if necessary was used the method 'Translations.getString' in the code for UI translations. For example, the code `new JLabel("Search");` has been changed to `new JLabel(Translations.getStringt("FeedersPanel.SearchLabel.text"));`
* Also, after using the 'UTF8Control' class we can't use https://github.com/jcbvm/i18n-editor to read/write translation files properly because it  doesn't support UTF-8 directly. To solve this problem I forked sources to https://github.com/VSSavin/i18n-editor and made some fixes (you can now choose the encoding in the 'Settings' menu). Now we have to use it. 

# Justification
This change improves UI translations.

# Instructions for Use
No change.

# Implementation Details
1. Manual UI testing.
2. Did follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)
3. There are some changes in `org.openpnp.spi` and `org.openpnp.model` packages. All changes  affect only 'name' and 'short description' of Actions (like 'deleteAction', 'permutateUpAction' etc.). For example `putValue(SHORT_DESCRIPTION, Translations.getString("AbstractAxis.Action.Delete.Description"));`
4. Successful mvn test before submitting the Pull Request.

### CODE REVIEW

**Comment by markmaker** [comment]
Hi @VSSavin,

this looks good! Again huge work. 👍 

Do you know why the first two commits by myself show up?

Just to be sure, I understand correctly: you just mentioned https://github.com/jcbvm/i18n-editor in the sense of _instructions_ for translators wanting to use this tool, right? If yes, we should then incorporate these instructions in the Wiki.

Will you submit a PR to @jcbvm? And/or do you plan to maintain it? 

_Mark

**Comment by VSSavin** [comment]
I don't know why the first two commits show up...

I saw a link to this tool (https://github.com/jcbvm/i18n-editor) in the file [TRANSLATIONS.md](https://github.com/openpnp/openpnp/blob/develop/TRANSLATIONS.md) at the project root. And I'm not sure if this tool is currently maintained by the authors

**Comment by VSSavin** [comment]
Perhaps the two commits because of this. And I started working on 'develop' branch
test

**Comment by ian-arkver** [comment]
Your UI branch now has the develop branch merged in with some commits still based on the develop source and some after you merged. I think you need to create a clean set of commits based only on the test branch, preferably the latest upstream test rather than yours which is a little out of date already. I don't think your commits accurately reflect the differences between test and develop code.

A solution might be to start a new ui_translations_test branch from upstream test and cherry-pick ranges of commits over from your old branch. Once your feature branch is based on (and tracks) the correct upstream branch and is one clean chain of commits, then it can be merged by upstream maintainers.

I tried to rebase your branch onto test, but immediately hit lots of conflicts.

**Comment by markmaker** [comment]
Replaced by #1499

**Pull request closed without merging**
