### PR TITLE
	modified:   src/main/java/org/openpnp/gui/importer/EagleBoardImporte…

### PR DESCRIPTION
**Pull request by DouglasPearless**
…r.java

	modified:   src/main/java/org/openpnp/model/eagle/EagleLoader.java

### CODE REVIEW

**Comment by DouglasPearless** [comment]
Hopefully fixed an issue with the unmarshaller, and added the ability to select which side to import

**Comment by cri-s** [comment]
Using mirrored part is wrong, part could be mirrored for
other reason, the layer should be used.
It should be noted, that the centeroid value could be different as produced
by mountsmt.ulp , and actually there is no check for smd parts only.
Annother thing to note, if there is no rotation and part is on top,  the
rotation attribute is missing. I don't know if the code handle this correct
or exception/null is generated instead of value 0.



2015-09-06 9:24 GMT+00:00 Jason von Nieda <notifications@github.com>:

**Comment by DouglasPearless** [comment]
OK,

in the XML there is no Part (aka element) to layer relationship that I can find.

All the parts (element) that are on the bottom prefix the rotation with ‘M’

i.e. part rotation 180 on top is “R180” and part on bottom rotated 180 is “MR180”

That is the only change in the XML file I could find that differentiates whether a part is on the top or bottom, and I note when using Eagle PCB it is the Mirror command that is used to shift a part to the bottom layer.

If there is another way to interpret the XML, I am more than happy to change the code to suit (Note I have also asked the on the Eagle PCB support forum to clarify my understanding).

Where there is no rotation, it defaults to 0 on the top layer (I have tested this and it works, but happy if someone can send me a board file that fails and I will fix as required); not that a part of the bottom with no rotation is shown as MR0.

Examples:

<element name="FID1" library="SparkFun-Aesthetics" package="FIDUCIAL-1X2" value="FIDUCIAL1X2" x="23.6" y="15.2"/>
<element name="FID6" library="SparkFun-Aesthetics" package="FIDUCIAL-1X2" value="FIDUCIAL1X2" x="1.6" y="31.4" rot="MR0"/>

In these cases “FID1” is on the top and not rotated, and “FID6” is on the bottom and not rotated.

I have test these and they work :-)

Could you please expand on the centroid issue and perhaps provide an example as I am not clear on what this is? :-)

Cheers
Douglas

**Comment by cri-s** [comment]
Il 06/set/2015 12:40 "Douglas Pearless" <notifications@github.com> ha
scritto:
>
> OK,
>
> in the XML there is no Part (aka element) to layer relationship that I
can find.

I have checked. Eagle 6.2 and 6.3 had it. The latest don't have it anymore.

>
> All the parts (element) that are on the bottom prefix the rotation with
‘M’
Pinheader as example is seen often mirrored.

>
> I have test these and they work :-)
>
> Could you please expand on the centroid issue and perhaps provide an
example as I am not clear on what this is? :-)
>
Mountsmd ulp calc the extends of package or pins, I don't remember and calc
the center of the package. This could be different of user selected
coordinate center 0 on designing the part. Because there was such enorms
problems with center position on eagle some ulp ignores the center
coordinates and calc this based on the package/pins as this have proven to
give better results and minor work in adjusting the centeroid on PNP
machine.

> Cheers
>

**Comment by cri-s** [comment]
Here are examples of two footprint with slight different PnP centeroids.

Line from MPHS.brd
<element name="U2" library="ChipsParts" package="SOT-89" value="MCP1701"
x="16.51" y="10.795"/>
simplified to:
 U2 ChipsParts SOT-89 MCP1701 16.51 10.795

Line from MPHS.mnt
U2 16.51 10.58   0 MCP1701 SOT-89

Altium TXT format:
Designator Footprint               Mid X         Mid Y         Ref X
  Ref Y         Pad X         Pad Y TB      Rotation Comment
         SOT-89               16.510mm      10.583mm      16.510mm
 10.795mm      15.010mm       9.020mm  T          0.00 MCP1701

Same exist as example from DPACK:
 IC1 v-reg D2PACK LM317BD2T 98.974528125 12.009078125 R90
 IC2 v-reg D2PACK LM317BD2T 12.648575 79.752246875
 IC3 v-reg D2PACK LM317BD2T 179.18335 109.8165125
 IC4 v-reg D2PACK LM317BD2T 12.63133125 109.185478125
 IC5 v-reg D2PACK LM317BD2T 94.622209375 181.255075 R90

And from .mnt
IC1 102.15 12.01  90 LM317BD2T D2PACK
IC2 12.65 76.58   0 LM317BD2T D2PACK
IC3 179.18 106.64   0 LM317BD2T D2PACK
IC4 12.63 106.01   0 LM317BD2T D2PACK
IC5 97.80 181.26  90 LM317BD2T D2PACK

Altium TXT format:
Designator Footprint               Mid X         Mid Y         Ref X
  Ref Y         Pad X         Pad Y TB      Rotation Comment
IC1        D2PACK              102.150mm      12.009mm      98.975mm
 12.009mm     107.865mm       9.469mm  T         90.00 LM317BD2T
IC2        D2PACK               12.649mm      76.577mm      12.649mm
 79.752mm      10.109mm      70.862mm  T          0.00 LM317BD2T
IC3        D2PACK              179.183mm     106.642mm     179.183mm
109.817mm     176.643mm     100.927mm  T          0.00 LM317BD2T
IC4        D2PACK               12.631mm     106.010mm      12.631mm
109.185mm      10.091mm     100.295mm  T          0.00 LM317BD2T
IC5        D2PACK               97.797mm     181.255mm      94.622mm
181.255mm     103.512mm     178.715mm  T         90.00 LM317BD2T



2015-09-06 10:40 GMT+00:00 Douglas Pearless <notifications@github.com>:

> OK,
>
> in the XML there is no Part (aka element) to layer relationship that I can
> find.
>
> All the parts (element) that are on the bottom prefix the rotation with ‘M’
>
> i.e. part rotation 180 on top is “R180” and part on bottom rotated 180 is
> “MR180”
>
> That is the only change in the XML file I could find that differentiates
> whether a part is on the top or bottom, and I note when using Eagle PCB it
> is the Mirror command that is used to shift a part to the bottom layer.
>
> If there is another way to interpret the XML, I am more than happy to
> change the code to suit (Note I have also asked the on the Eagle PCB
> support forum to clarify my understanding).
>
> Where there is no rotation, it defaults to 0 on the top layer (I have
> tested this and it works, but happy if someone can send me a board file
> that fails and I will fix as required); not that a part of the bottom with
> no rotation is shown as MR0.
>
> Examples:
>
> <element name="FID1" library="SparkFun-Aesthetics" package="FIDUCIAL-1X2"
> value="FIDUCIAL1X2" x="23.6" y="15.2"/>
> <element name="FID6" library="SparkFun-Aesthetics" package="FIDUCIAL-1X2"
> value="FIDUCIAL1X2" x="1.6" y="31.4" rot="MR0"/>
>
> In these cases “FID1” is on the top and not rotated, and “FID6” is on the
> bottom and not rotated.
>
> I have test these and they work :-)
>
> Could you please expand on the centroid issue and perhaps provide an
> example as I am not clear on what this is? :-)
>
> Cheers
> Douglas

**Comment by DouglasPearless** [comment]
Interesting, 

I will run some tests comparing the .mnt / .mnb output from the mountsnt.ulp and my code and see how mountsmt.ulp calculates things.

It is an area I do not well understand and will help me set up my FirePick machine for solder paste dispensing (I am waiting for Jason to check in his code, I cannot wait!)

Cheers
Douglas

**Comment by DouglasPearless** [comment]
OK, I will look at this and compare my code with mountsmd.ulp.

I am trying to determine the logic for my program, is this correct:

(1) the .brd file has the centre for the part placement on the board, BUT
(2) the part library may have the centre for the part anywhere in the part definition (i.e. at one corner), SO
(3) I need to examine each part and if the centre is not in the centre of the part, then adjust the x and y that my code returns to be the actual centre of the part itself

Is the above correct?

Cheers
Douglas

**Comment by cri-s** [comment]
Il 07/set/2015 00:28 "Douglas Pearless" <notifications@github.com> ha
scritto:
>
> Interesting,
>
> I will run some tests comparing the .mnt / .mnb output from the
mountsnt.ulp and my code and see how mountsmt.ulp calculates things.

This is unnecessary. As you have noticed I have included altium output
format from eagle. Mountsmt is the same as mid x and the brd is the same as
ref x.
Ref x is the user supplied center, mid x is the calculated center of the
part. I'm not telling it's bad, but you must know that reading mnt and brd
is not the same and probably for most users this is surprising.

> It is an area I do not well understand and will help me set up my
FirePick machine for solder paste dispensing (I am waiting for Jason to
check in his code, I cannot wait!)
>
> Cheers
> Douglas
>
> > On 7/09/2015, at 2:19 am, cri-s <notifications@github.com> wrote:
> >
> > Here are examples of two footprint with slight different PnP centeroids.
> >
> > Line from MPHS.brd
> > <element name="U2" library="ChipsParts" package="SOT-89" value="MCP1701"
> > x="16.51" y="10.795"/>
> > simplified to:
> > U2 ChipsParts SOT-89 MCP1701 16.51 10.795
> >
> > Line from MPHS.mnt
> > U2 16.51 10.58 0 MCP1701 SOT-89
> >
> > Altium TXT format:
> > Designator Footprint Mid X Mid Y Ref X
> > Ref Y Pad X Pad Y TB Rotation Comment
> > SOT-89 16.510mm 10.583mm 16.510mm
> > 10.795mm 15.010mm 9.020mm T 0.00 MCP1701
> >
> > Same exist as example from DPACK:
> > IC1 v-reg D2PACK LM317BD2T 98.974528125 12.009078125 R90
> > IC2 v-reg D2PACK LM317BD2T 12.648575 79.752246875
> > IC3 v-reg D2PACK LM317BD2T 179.18335 109.8165125
> > IC4 v-reg D2PACK LM317BD2T 12.63133125 109.185478125
> > IC5 v-reg D2PACK LM317BD2T 94.622209375 181.255075 R90
> >
> > And from .mnt
> > IC1 102.15 12.01 90 LM317BD2T D2PACK
> > IC2 12.65 76.58 0 LM317BD2T D2PACK
> > IC3 179.18 106.64 0 LM317BD2T D2PACK
> > IC4 12.63 106.01 0 LM317BD2T D2PACK
> > IC5 97.80 181.26 90 LM317BD2T D2PACK
> >
> > Altium TXT format:
> > Designator Footprint Mid X Mid Y Ref X
> > Ref Y Pad X Pad Y TB Rotation Comment
> > IC1 D2PACK 102.150mm 12.009mm 98.975mm
> > 12.009mm 107.865mm 9.469mm T 90.00 LM317BD2T
> > IC2 D2PACK 12.649mm 76.577mm 12.649mm
> > 79.752mm 10.109mm 70.862mm T 0.00 LM317BD2T
> > IC3 D2PACK 179.183mm 106.642mm 179.183mm
> > 109.817mm 176.643mm 100.927mm T 0.00 LM317BD2T
> > IC4 D2PACK 12.631mm 106.010mm 12.631mm
> > 109.185mm 10.091mm 100.295mm T 0.00 LM317BD2T
> > IC5 D2PACK 97.797mm 181.255mm 94.622mm
> > 181.255mm 103.512mm 178.715mm T 90.00 LM317BD2T
> >
> >
> >
> > 2015-09-06 10:40 GMT+00:00 Douglas Pearless <notifications@github.com>:
> >
> > > OK,
> > >
> > > in the XML there is no Part (aka element) to layer relationship that
I can
> > > find.
> > >
> > > All the parts (element) that are on the bottom prefix the rotation
with ‘M’
> > >
> > > i.e. part rotation 180 on top is “R180” and part on bottom rotated
180 is
> > > “MR180”
> > >
> > > That is the only change in the XML file I could find that
differentiates
> > > whether a part is on the top or bottom, and I note when using Eagle
PCB it
> > > is the Mirror command that is used to shift a part to the bottom
layer.
> > >
> > > If there is another way to interpret the XML, I am more than happy to
> > > change the code to suit (Note I have also asked the on the Eagle PCB
> > > support forum to clarify my understanding).
> > >
> > > Where there is no rotation, it defaults to 0 on the top layer (I have
> > > tested this and it works, but happy if someone can send me a board
file
> > > that fails and I will fix as required); not that a part of the bottom
with
> > > no rotation is shown as MR0.
> > >
> > > Examples:
> > >
> > > <element name="FID1" library="SparkFun-Aesthetics"
package="FIDUCIAL-1X2"
> > > value="FIDUCIAL1X2" x="23.6" y="15.2"/>
> > > <element name="FID6" library="SparkFun-Aesthetics"
package="FIDUCIAL-1X2"
> > > value="FIDUCIAL1X2" x="1.6" y="31.4" rot="MR0"/>
> > >
> > > In these cases “FID1” is on the top and not rotated, and “FID6” is on
the
> > > bottom and not rotated.
> > >
> > > I have test these and they work :-)
> > >
> > > Could you please expand on the centroid issue and perhaps provide an
> > > example as I am not clear on what this is? :-)
> > >
> > > Cheers
> > > Douglas
> > > > On 6/09/2015, at 10:07 pm, cri-s <notifications@github.com> wrote:
> > > >
> > > > Using mirrored part is wrong, part could be mirrored for
> > > > other reason, the layer should be used.
> > > > It should be noted, that the centeroid value could be different as
> > > produced
> > > > by mountsmt.ulp , and actually there is no check for smd parts only.
> > > > Annother thing to note, if there is no rotation and part is on top,
the
> > > > rotation attribute is missing. I don't know if the code handle this
> > > correct
> > > > or exception/null is generated instead of value 0.
> > > >
> > > >
> > > >
> > > > 2015-09-06 9:24 GMT+00:00 Jason von Nieda <notifications@github.com
>:
> > > >
> > > > > Merged #146 <https://github.com/openpnp/openpnp/pull/146>.
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <https://github.com/openpnp/openpnp/pull/146#event-402115497>.
>
> > > > >
> > > > —
> > > > Reply to this email directly or view it on GitHub <
> > > https://github.com/openpnp/openpnp/pull/146#issuecomment-138062083>.
>
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/openpnp/openpnp/pull/146#issuecomment-138066207>.
> > >
> > —
> > Reply to this email directly or view it on GitHub <
https://github.com/openpnp/openpnp/pull/146#issuecomment-138089395>.

**Comment by DouglasPearless** [comment]
I think I am beginning to better understand it.  

Should I check to see if the .brd x/y is the same as the actual centre for the part, or is that un-necessary?

Cheers
Douglas

**Comment by cri-s** [comment]
> I am trying to determine the logic for my program, is this correct:
>
> (1) the .brd file has the centre for the part placement on the board, BUT
> (2) the part library may have the centre for the part anywhere in the
part definition (i.e. at one corner), SO
> (3) I need to examine each part and if the centre is not in the centre of
the part, then adjust the x and y that my code returns to be the actual
centre of the part itself
>
> Is the above correct?

Basically yes. For some parts, example vregs, MOSFETs if you don't use mid
x normally there exists additionally offsets. Further there exist customer
specifics offsets. You know customer xy have done wrong designing libs, and
if you have customer specific offset then you don't loose time adjusting
this the next times. The same is for shape (package) mapping.
Another check is correct rotation of part, specifically pin 1.
All assembler love the now called altium output file,
Because it have mid, ref, and 1.st pin defined for each component. This
simplified or speed up a lot with the right tool.

There exist different workflows, but for offline programming, you need
either scan of PCB or gerber files. If Gerber don't use flashes then scan
of PCB is needed. The sw overlap PCB image and component using centeroid
file and indicate 1.st pin if supplied and possibly checks if it is out or
not. This after package/shape mapping and customer and global offsets
applying.

>
> Cheers
> Douglas
>
> > On 6/09/2015, at 11:17 pm, cri-s <notifications@github.com> wrote:
> >
> > Mountsmd ulp calc the extends of package or pins, I don't remember and
calc
> > the center of the package. This could be different of user selected
> > coordinate center 0 on designing the part. Because there was such enorms
> > problems with center position on eagle some ulp ignores the center
> > coordinates and calc this based on the package/pins as this have proven
to

**Comment by cri-s** [comment]
This is unnecessary, as I have already checked it with altium ulp output.
It is the same.
Il 07/set/2015 01:42 "Douglas Pearless" <notifications@github.com> ha
scritto:

> I think I am beginning to better understand it.
>
> Should I check to see if the .brd x/y is the same as the actual centre for
> the part, or is that un-necessary?
>
> Cheers
> Douglas

**Pull request merged**
