### PR TITLE
Fix minor typo in Issue Template and use markdown https link. Also ignore .vscode settings dir.

### PR DESCRIPTION
**Pull request by ian-arkver**
# Description
As subject

### CODE REVIEW

**Comment by ian-arkver** [comment]
Interesting, the PR checks fail with...
```
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.117 s <<< FAILURE! - in CvStageTest
Error:  testPipelinePropertyOverrides  Time elapsed: 0.055 s  <<< ERROR!
java.lang.Error: Configuration instance not yet initialized.
	at CvStageTest.testPipelinePropertyOverrides(CvStageTest.java:54)
```
The code in this branch is identical to upstream develop. Is this a known bug? Some kind of race?

**Comment by markmaker** [comment]
The Github Actions builds must have changed, a bug was exposed, see #1375. I already fixed that earlier in `test`.
_Mark

**Comment by markmaker** [comment]
Thanks!

**Comment by ian-arkver** [comment]
Ah, excellent. Thanks Mark.

**Pull request merged**
