### PR TITLE
Add Camera to Nav Combobox and then show selected item coords in DRO

### PR DESCRIPTION
**Pull request by BendRocks**
This is continuation of #504....This is to check if on the right path (not a lot of changes were needed). There was CameraItem and NozzleItem already. Looks like these are used to give a nice output string. I created a headmountableitem and derived cameraitem and nozzleitem from that, and then used the headmountable item in the combo box. Combobox populates as expected (with nozzle and head camera) and DRO reads as expected based on which is selected in the listbox. 

One bug I might have found that is unrelated to these changes: If you have two nozzles, one offset of -10,-10 and another of -5, -5, and you XY park, your absolute park location seems to depend on which nozzle was selected when you parked. That seems not right to me as the docs say park should park the head at its park location. If you confirm that is incorrect, I'll fix that in this pr.

### CODE REVIEW

**Comment by cri-s** [comment]
Is this then in camera coords or machine coords?
Park location is a location where the nozzles park, depending on last used and last head used.

**Comment by vonnieda** [comment]
@BendRocks Looks perfect. As to the park problem, see https://github.com/openpnp/openpnp/issues/279. I fear that might actually be a big change, but I haven't fully thought it through. If it's more than a couple lines I'd prefer if it's done as two PRs.

**Comment by vonnieda** [comment]
@BendRocks Is this ready to go?

**Comment by BendRocks** [comment]
>Is this ready to go?

Almost! @vonnieda, could you take a look around line 382 in MachineControlsPanel and explain what is going on there? This looks listener code looks like code that will run when a nozzle gets added (the IF part) OR if a first nozzle is added (the ELSE part). 

Is that right?

The reason I'm confused is I'm not sure I need to extend to look for camera because if I add a camera to the head, it somehow ends up in the list box. But I don't understand how.  Any insight?

**Comment by vonnieda** [comment]
The if adds a newly arrived nozzle, when a user adds one in Machine Setup, and the else removes one, when a user deletes it from Machine Setup. These are for handling dynamic updates during runtime. Everything gets loaded during startup at 359, so this is probably where you are seeing cameras added, after a restart. If cameras are showing up without a restart then I am not sure why.

I would expect you to need to update both parts for camera.

**Comment by BendRocks** [comment]
OK, this should handle the runtime changes.  Unless you see something in review, I think done on my side.

I didn't try to fix anything mentioned above about #279.

**Comment by vonnieda** [comment]
Great work @BendRocks, this is a nice improvement and a really nice PR!

**Pull request merged**
