### PR TITLE
Adding new icons and suggesting some visual clues

### PR DESCRIPTION
**Pull request by dzach**
Adds new icons to keep visual consistency, as per discussion in #421.
Not all new icons have currently a use in OpenPnP.

### CODE REVIEW

**Comment by vonnieda** [comment]
Thanks @dzach! I have merged this, plus a few minor changes of my own. I made changes to use the new icons you created as well as renaming and clarifying a few. 

I do have one thought on the new nozzle tip add and remove icons. These put the + and x in a different position than the other icons where we do this. Was it intentional, or should we standardize on a location? See:

screen shot 2017-01-24 at 11 16 32 am

Reference: #421

**Comment by vonnieda** [comment]
WRT to the above, I like your positioning better ,so if we standardize I think we should move the + and x on the nozzle icons (right most) to the bottom like your icons have it.

**Comment by dzach** [comment]
That was intentional. I was trying to apply the principle laid out above, i.e. provide a non-color clue together with a color one. So, close to the (grayed) tip, means 'tip' while close to the head means 'nozzle'. Hopefully, it makes sense.

**Comment by vonnieda** [comment]
@dzach Okay, that makes sense now. I personally find it visually a bit glaring, but I think it's functionally better. In the future it may be better to have a completely different icon for nozzle and nozzle tip so that we can standardize on the position of the + and x.

**Pull request merged**
