### PR TITLE
Feature post feed

### PR DESCRIPTION
**Pull request by tracklogic**

### CODE REVIEW

**Comment by vonnieda** [comment]
I'm good with this feature, but I think the name of the method should be changed to postPick. If I understand how the feature works then this more accurately reflects when it will be called.

**Comment by tracklogic** [comment]
Hi Jason

No problem, i'll rename it your right postPick makes more sense

Matt

**Comment by cri-s** [comment]
The convenience to have feed and preFeed , postFeed is that feed can invoke either pre- or postFeed presenting the operator one unique interface, feed . As ReferenceFeeder preFeed calls feed the old feeder interfaces are still valid.

**Comment by vonnieda** [comment]
@tracklogic Fixed this up as discussed and merged it.

**Pull request merged**
