### PR TITLE
Chinese UI translation improvements (to be continued）

### PR DESCRIPTION
**Pull request by QUTAOJUN**
# Description
_update at 2023-03-03_
This PR is based on the “Commits on Feb 26, 2023” from test branch about the file of “translations.properties” .

Chinese UI has been completed for all 1550 valid entries .
On March 1,  the newest _Commits_ was submitted , i provided a good method for the translation work and how to get feedback from users.[https://github.com/openpnp/openpnp/pull/1525#issuecomment-1449459811](https://github.com/openpnp/openpnp/pull/1525#issuecomment-1449459811)

# Justification
Improves the Chinese language translation.

# Instructions for Use
关心和关注OpenPnP以及UI汉化的朋友，你们好!
我已经将测试方法和使用说明放在开源项目中，只适用于test分支。[QUTAOJUN/Chinese-Test-UI-for-OpenPnP](https://github.com/QUTAOJUN/Chinese-Test-UI-for-OpenPnP)
有任何修改意见或建议，请在谷歌在线表格中以_添加注释_的方式向我反馈。我会第一时间关注。[Google Spread Sheets](https://docs.google.com/spreadsheets/d/1R2Iexl7OM_PMKlmTlxV-NgCgscmP0trcLvYTa9Ft7s8/edit?usp=sharing)
或者您也可以使用官方推荐的Eclipse或I18n工具参与到汉化中来。

# Implementation Details
Manual UI testing.
Did follow the coding style.
No changes in the org.openpnp.spi or org.openpnp.model packages.
Successful mvn test before submitting the Pull Request.

Code screenshot
OpenPnP-CN-01
Mvn package success
OpenPnP-CN-02
UI testing
OpenPnP-CN-03
i18n-editor
OpenPnP-CN-04

### CODE REVIEW

**Comment by vonnieda** [comment]
Looks good to me - thanks @QUTAOJUN, and congratulations on your first PR!

**Comment by QUTAOJUN** [comment]
> Looks good to me - thanks @QUTAOJUN, and congratulations on your first PR!
Very very happy, in the first time, receive your response!
It is my first time to contact GitHub,  I need to get familiar with it in a very short time.
If any problem, please forgive me and feel free to contact me.  
The follow-up Chinese translation will be continued...as soon as possible!!

**Comment by Alan-0131** [comment]
Well done, brother! Thank you for your work on the Chinese translation of openpnp. As per my public promise in China, I will prepare to launch a bonus plan. I also hope that more friends will join us to improve the Chinese translation of openpnp together, benefiting every user who uses openpnp.

**Comment by xzbaijj** [comment]
I hope not to adopt this person's translation. After reading it roughly, many translations violate the original intention of the author. For example, Set DTR has been translated into 设置DRT高电平, which means Set DTR High Level in English, while the Chinese translation of DTR is 数据终端准备好, and can only be translated into enable DRT at most. This kind of translation is everywhere and violates the meaning of the original.

**Comment by QUTAOJUN** [comment]
> 

感谢您的回复和指正，希望我能在这里为这次提交做一些补充说明。这次提交的文件中，关于中文汉化的部分，确实有很多词条不合理，我已经处理了大概接近一半的词条

**Comment by QUTAOJUN** [comment]
@xzbaijj 

- 感谢您的关注和指正。希望您也能参与进来。
   您看过官方正式版本和测试版本中的汉化内容和词条了吗，是不是很不合理，特别是董事会？

- 希望您能体谅我的友善，这份文件并不是最终版本。任何一个软件的UI翻译都需要多人参与，反复指正和修改。

- 希望在这里让我对这次的PR提交做一些说明。

- 这只是第一版汉化，并不完善，还不是最终的版本，是一次尝试，中文叫“抛砖引玉”。

- 所有1550条词条的处理工作是很大的，包括词条定位，词条的真实功能含义，汉化风格以及汉语用词的处理，这些我独自一个人是无法做到100%的完美。

- 我这次要做的目的是，打通UI汉化的整个过程。
- 后续我会在[discussion group](http://groups.google.com/group/openpnp),或其他更适合的渠道发布汉化教程（文字或视频）：包括汉化过程涉及到相应软件的安装和使用，整理和总结汉化过程中遇到的问题，搭建错误反馈和修正机制等，以方便更多人能够更有效地参与其中。

下面是我目前对于词条处理的过程：
①词条提取，通过百度，谷歌，有道等一系列翻译软件，进行了机翻。
虽然粗暴原始，几乎都是错误的翻译，但是特别有意义的是，它能让我通过错误的词条，很快的定位到这个词条在软件中的位置。
②针对已找到位置的词条，进行重新翻译，整理词汇进行表达以及合理布局，特别是<html>部分。
目前我已经手动整理了大概800条，我手头有原始的进度文件，其余汉化部分，依然保留了原始的机翻内容。其中<html>部分带中文的是我已经操作过的，几乎所有保留英文内容的，是我没开始处理的，或者是选择保留的，例如Rotation.
希望您能尝试理解我和我想表达的内容。也抱着最大的热情聆听大家的意见和建议。
----------------------------------------------------------------------
Translation above↑ from Google Translator directly . I amnot good in speaking English.
----------------------------------------------------------------------
-Thank you for your attention and correction. Have you seen the official version of the official version and test version of the Chinese content and entries? Is it unreasonable, especially the board of directors?

-I hope you can understand my friendliness, this file is not the final version. Any UI translation of any software requires multiple people to participate, repeatedly correct and modify.

-I want to let me make some instructions on this PR submission here.

-This is just the first version of Sinicization and is not perfect. It is not the final version. It is an attempt.

-The handling of all 1550 entries is very large, including the positioning of the entry, the real functional meaning of the entry, the Chinese style, and the processing of Chinese words. These can not be 100%perfection.

-The purpose of this time is to open up the whole process of UI Chinese.
-This I will publish a Chinese tutorial (text or videos) in [discussion group] (http://groups.google.com/group/openpnp), or other more suitable channels: including the installation and installation of the corresponding software and the Chineseization process involving the Chineseization process involving the corresponding software installation and the installation of the corresponding software. Use, organize, summarize the problems encountered in the process of Chineseization, build error feedback and amendments, etc., so that more people can participate more effectively.

The following is my current process of handling of entry:
① Extraction of the entry, through a series of translation software such as Baidu, Google, Youdao, and other translations.
Although rough and original, almost all of them are wrong translations, it is particularly meaningful that it allows me to quickly position the position of this entry in the software through the wrong entry.
② Re -translation for the entry that has been found, sort out vocabulary for expression and reasonable layout, especially the <HTML> section.
At present, I have manually compiled about 800 pieces. I have the original progress file at hand, and the rest of the Chinese part still retains the original machine reversal content. Among them, the <HTML> part of the Chinese I have already operated, almost all those who retain English content are not started to deal with it, or choose to retain, such as rotation.
I hope you can try to understand what I want to express. He also listened to everyone's opinions and suggestions with the greatest enthusiasm.

**Comment by QUTAOJUN** [comment]
@Alan-0131 
感谢来自您的回复和肯定，我是从这里开始决定做UI翻译的，↓来自Markmaker的回复：[https://github.com/openpnp/openpnp/pull/1499#issuecomment-1338969635](url)
同时了解到您的主张和处境。感谢您为大家做的努力。
其实，我是通过您的bilibili视频才知道OpenPnP的，谢谢您，把我领进了OpenPnP的大门。
[https://www.bilibili.com/video/BV1R54y1B7Hr/?spm_id_from=333.999.0.0&vd_source=ef4e28d0665be5ca53808092756f01bb](url)
希望我也能为大家做点有价值的东西。
--------------Translation above----------------
Thank you for your reply and affirmation. From here, ↓ I decided to do UI translation.  The reply from Markmaker: [https://github.com/openpnpnpnpnp/pull/1499 #IssueComment-1338969635](url)
At the same time and other Issue , I got your attitude and situation . Thank you for doing hard for us.
Actually, I learned about OpenPNP through your Bilibili video. Thank you, bring me into the door of OpenPNP.
[https://www.bilibili.com/video/BV1R54y1B7Hr/?spm_id_from=333.999.0.0&vd_source=ef4e28d0665be5ca53808092756f01bb](url)
I hope I can also do something valuable for users.

**Comment by xzbaijj** [comment]
What we hope is to keep the original author's intention, rather than add some of your own things at random. Your translation adds too much subjective meaning

**Comment by Alan-0131** [comment]
Hello everyone, for software language translation, I think, first of all, we must respect the hard work and dedication of the submitter. Second, as far as language translation is concerned, a word has multiple interpretations. For example, ok can be translated into "好的、是的、可以、完成、同意、不错", etc., but when used in software, it must accurately describe the purpose of the software function. These problems can only be solved by the cooperation of users and developers, so it is recommended that the author open a discussion group to let everyone participate and improve the Chinese translation work together. Only in this way can it bring real convenience to openpnp users.

**Comment by QUTAOJUN** [comment]
@xzbaijj You are right，i research the Set DTR on line，and now i  know the true meaning of it，100%，thank you for telling me the error ，i will fix it.
Set DTR

**Comment by xzbaijj** [comment]
Almost all of your translations have problems. Please do not add personal meaning at will. This is too bad.

**Comment by xzbaijj** [comment]
几乎所有的翻译，都是不通的。

**Comment by xzbaijj** [comment]
比如，Enable to get an extra Wizard tab to configure an Axis Interlocking Actuator，is mean，启用一个额外的向导标签页用于配置轴连锁触发器，而不是“启用后，将为该功能新增一个配置选项卡”，后者的意思是：enabled to  new a configuration tab that will be added for this function，两者意思完全不一样

**Comment by xzbaijj** [comment]
Please don't translate randomly. This will make the language system of openpnp very bad. Other translators also need to correct your translation, which will bring great burden of second language.Machine translation looks very violent, but it does not violate the original meaning of the author, but your translation seriously violates it.

**Comment by xzbaijj** [comment]
> Looks good to me - thanks @QUTAOJUN, and congratulations on your first PR!

太多这种翻译问题了，没有的东西硬要添加上去，比如触发器就是触发器，为什么要加上其他触发器呢？其他两个字在原文中哪里出现的？

**Comment by xzbaijj** [comment]
太多这种翻译问题了，没有的东西硬要添加上去，比如触发器就是触发器，为什么要加上其他触发器呢？其他两个字在原文中哪里出现的？

**Comment by xzbaijj** [comment]
> Looks good to me - thanks @QUTAOJUN, and congratulations on your first PR!

Please don't adopt this person's translation. There are too many places that violate the meaning of the original text, and many personal intentions are added to it, which will make openpnp very bad.

**Comment by vonnieda** [comment]
> > Looks good to me - thanks @QUTAOJUN, and congratulations on your first PR!
> 
> Please don't adopt this person's translation. There are too many places that violate the meaning of the original text, and many personal intentions are added to it, which will make openpnp very bad.

I understand, and this will not be merged until there is some consensus. I do not speak Chinese, so I leave it to the Chinese OpenPnP community to decide how to proceed. Your concerns seem valid and should be addressed.

**Comment by QUTAOJUN** [comment]
> 太多这种翻译问题了，没有的东西硬要添加上去，比如触发器就是触发器，为什么要加上其他触发器呢？其他两个字在原文中哪里出现的？

＂其他＂这两个字，确实是我加进去，原英文也的确没有extra这个前缀，我只是想要区别于贴片头里的触发器，想帮助新手用户，为他们指明，界面里安排有两个触发器位置。有何不可呢，我也在创作过程中，体会翻译应该遵循各种规则，进展越深越会怀疑自己。谢谢和理解您的关注和劝解。我在discussion group里开设了一个区域，我会在那里搭建反馈机制，发布教程，一齐讨论评定规则，畅所欲言。还有就是。我正在回滚我的进度文件，让机翻部分，还原成英文，只保留我实际汉化的词条，我不能为自己为他人制造和提供我不确定的内容。预计明天会上传新的进展。

**Comment by QUTAOJUN** [comment]
> Your concerns seem valid and should

It really needs a lot of help to get Chinese friends involved to reach a consensus and plan the rules. After all, there are really too many words translated. If 100 friends feed back questions almost at the same time, what should I do? :) I will stick to my work all the time. I will publish Chinese tutorials (text, pictures, videos, etc.) in the discussion group, which can be applied and borrowed to other languages include Chinese, to help everyone work more effectively. I'm rolling back my progress file, removing some ambiguous entries, and making this file as a real starting point for me and others. Hope for the best!!

**Comment by QUTAOJUN** [comment]
@xzbaijj 
I am thinking about your suggestion. If any problem, let`s discuss ovre here.[https://groups.google.com/g/openpnp/c/7mTCr-PFkso/m/7eTyMY9CAgAJ](url)

**Comment by QUTAOJUN** [comment]
@vonnieda 
Good afternoon, 
i`m sorry to keep you waiting.
I revised the Chinese description in the document, and completed the previously untranslated part, 
did my best to restore the original meaning of the English, almost all of it was modified.  :)
I will share the content of the file in Google Sheets, and hope to invite more friends who use OpenPnP.
Also hope that everyone will participate in reviewing and making changes.

---already “Build Success” througt “mvn package”mvn package test.
Waiting for your message~~~~

MVN BUILD SUCCESS

界面01

Eclipse 界面

**Comment by vonnieda** [comment]
Hi @QUTAOJUN,

Thank you for your patience and apologies for the long response time. Thank you, too, for the work you've put in to this PR.

I want to make sure I understand the current status of this PR, and then move forward with making a decision to merge it. Can you verify I have this correct?

1. You have finished your translations and are ready for these to be merged in.
2. You posit that even if there are some problems in the translations, it will be better and/or faster for Chinese users to identify them by using the software.
3. The Google Sheets link is intended to be used for translation editing suggestions from users.
4. You have suggested a method to quickly identify message keys in the program by including a numeric tag like [1]. 

And from that, a few questions:

1. @xzbaijj Could you please review the latest changes and let us know if you feel these are acceptable, and that they are an improvement over what we currently have?
2. @QUTAOJUN How do you propose to let users test/use/download the version with the [1] tags included?

Thanks,
Jason

**Comment by jjkk1314T** [comment]
It's great news that Openpnp finally has Chinese. It can be seen that the author is still very careful, the translation is very accurate, easy to understand, and the degree of completion is also very high. Just don't know how to install and use it? And how to use that number?

**Comment by QUTAOJUN** [comment]
Hi @vonnieda 
It's a great honor to receive your reply.
Here is my reply：

> Can you verify I have this correct?
> 
> 1. You have finished your translations and are ready for these to be merged in.

>  ****Yes！** I am ready:) [Commits](https://github.com/openpnp/openpnp/pull/1525/commits/6e8df494e28b021f15509433e305ce2c397bf52c)
Now all Chinese values are already Finished and Ready. 
In this time I added 150 new values from #1528 in advance.
Total Keys number is 1700.**

> 2. You posit that even if there are some problems in the translations, it will be better and/or faster for Chinese users to identify them by using the software.

> ****Yes！** I had tested it with a small group of Chinese users, under the released installation files of TEST, 
Until now, I am still getting good feedback from users . I will continue to follow the localization progress of UI and stick to it.
Try to prove that I am a trustworthy participant.**

> 3. The Google Sheets link is intended to be used for translation editing suggestions from users.

> ****Yes！** This is most important. It is necessary to build a most direct feedback channel for a wide audience of users. 
After all, the total number of missing keys and values will continue to increase over time.**

> 4. You have suggested a method to quickly identify message keys in the program by including a numeric tag like [1].

> ****Yes！** This method is similar to making an index catalog.Help translators solve a puzzle about "Find",to find where is the key or value of _translations.properties_file inside of the UI.
I think it will be a very effective method that I have summed up after such a long time of translation work.** 
> 
> -  **it can be used as a reference for other languages;**
> 
> - **it can help translators easily find the specific correspondence between UI and .properties file in sequence, reduce the threshold for translators to be familiar with the logic of the code, and allow translators to only engage in language translation.**
> 
> - **it can help to get or build a feedback channel for users.** 
> 
> **This tags forms a _closed loop_. Translators and users can easily participate in the translation work, even if the key is added/deleted in the future, only the translator needs to add/delete the existing [1…] tag according to the changes in Diff. 
> The example is shown in the figure below - extract the changes in #1528 and add new tags to it.**

New tags

> 
> And from that, a few questions:
> 
> 2. @QUTAOJUN How do you propose to let users test/use/download the version with the [1] tags included?

> **Can I apply to add a new option to the list of language settings, such as "Chinese (China)-Tags"?** 
such as below：
TAGS

**Each time I update and push a new translation file to the test branch, I make two files:**
- > one _**without**_ [1…] for daily test use (**translations_zh_CN.properties**) 

- > another one _**with**_ [1…] for feedback (**translations_zh_CN-Tags.properties**).

   _These two files are ready in my GitHub:[https://github.com/QUTAOJUN/Chinese-Test-UI-for-OpenPnP/tree/main/translations_zh_CN-Tags.properties](https://github.com/QUTAOJUN/Chinese-Test-UI-for-OpenPnP/tree/main/translations_zh_CN-Tags.properties)_
> 
> By this way, users can easily select and switch language modes in the **_same_** program interface: 
English⇄Chinese⇄Chinese (tags).

> The reason for thinking like this:
> 1. As a translator, only manipulating and submitting translated documents, any unofficial  packaging "openpnp-gui-0.0.1-alpha-SNAPSHOT.jar" file may lead to some unexpected consequences.
> 2. At the current stage, Chinese (China)-Tags only needs to exist in the TEST version. After a period of time, if there is a better way or another feedback channel, the Chinese (China)-Tags can be cancelled at any time.
> 3. Linking UI, translated files and Google Sheet by using the tag [1…] can achieve a closed loop,  translators and users at any level can participate and give effective feedback.

**Comment by vonnieda** [comment]
Incredible work @QUTAOJUN! Thank you for all your effort on this. I appreciate your willingness to work with everyone who had questions and to come up with ultimately a great work. Thank you!

I'll merge this now, and yes, I think your idea of having a second language in the menu with "tags" would work well. Please submit another PR for that.

Thank you, also, to everyone who helped with this issue!

Jason

**Comment by QUTAOJUN** [comment]
> Incredible work @QUTAOJUN! Thank you for all your effort on this. I appreciate your willingness to work with everyone who had questions and to come up with ultimately a great work. Thank you!
> 
> I'll merge this now, and yes, I think your idea of having a second language in the menu with "tags" would work well. Please submit another PR for that.
> 
> Thank you, also, to everyone who helped with this issue!
> 
> Jason

It seems that our actions are consistent, albeit in different parts of the planet. I've just been writing a post to post on Google Forum.
Thank you very much for your recognition.
I will stick to that all the time. :)

**Pull request merged**
