### PR TITLE
Configuration tabs within "Machine Setup" panel now with titles (partly #172)

### PR DESCRIPTION
**Pull request by dave-prosee**
Changed for available camera objects but with some remarks:

- ImageCamera, IPCamera, OpenCVCamera, SimulatedUpCamera and Webcams
work fine

- Webcams give however a warning in the log file
  log4j:WARN No appenders could be found for logger
  (com.github.sarxos.webcam.Webcam).
   log4j:WARN Please initialize the log4j system properly.
   log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for
   more info.

- Lticivil cam give, when trying to add on the cameras panel:
Caused by: com.lti.civil.CaptureException:
java.lang.UnsatisfiedLinkError: no civil in java.library.path

- Vfw cam gives, when selecting in the machine setup tree and also after
returning to Cameras panel and selecting it:
The vonnieda.org Java video capture kit is unable to load it's native
layer.
Please make sure you have org_vonnieda_vfw_CaptureDevice.dll in
yourPATH, Windows directory or current directory.
If you do not have this file, you should be able to find the latest
version at http://www.vonnieda.org/software.html.
Load failed due to:
java.lang.UnsatisfiedLinkError: no org_vonnieda_vfw_CaptureDevice in
java.library.path
camera’s are not updated to the machine setup tree, you have to reload
and crashes the app.

The remarks however, I cannot relate to the changes made. Hence still a
commit and PR.

A second commit covers the feeders. I found no problems there.

### CODE REVIEW

**Comment by vonnieda** [comment]
@dave-prosee This looks great, and I will be happy to accept it as is, but I want to mention a possible improvement and see what you think. On all the cameras, this code is duplicated. Since it's all the same I think we could push it into the base class ReferenceCamera and eliminate all the duplicate code. Any class down the road that has specific requirements can just override the method. What do you think?

Again, if you'd like me to just merge it as is for now I'd be happy to. This is already a great improvement over what we have.

**Comment by dave-prosee** [comment]
Thanks for asking, but I am the novice ;-)

I tend to say that better is the enemy of good. Sometimes we postpone to create something better while in the meantime little happens. #172 e.g. is open for almost a year now. You are right wanting things to go up base classes and I am open to assist but really a novice, ...meaning that going for base class will most certainly require, at the moment, some more support from you to me. 

Further more, this specific solution has been copied from the Drivers and so in line with what you were thinking yourself, some time ago.

On the other hand again, this issue is not on its own. The feeders (I used "Configuration" to be compliant with the feeders panel) and remaining objects could do with just "Configuration" so another solution would be to leave Drivers and Cameras as is and like above and for the rest rely on "if title = null then title = "Configuration".

It is your pick I'm afraid ;-) but I make one last statement like you did. Choosing one option does not have to mean you might not do the other, some day.

**Comment by dave-prosee** [comment]
Gave it another thought. If you accept these I will look into changing the base class. It's a nice exercise for me. OK?

**Comment by dave-prosee** [comment]
Couldn't sit still,.. was easier than I thought. Shouldn't be that cautious. 
For Cameras: will referencecamera do? That is one class higher. My feeling says that AbstractCamera should remain abstract and that specific titles do not have a place there.
For feeders we could go to AbstractFeeder (two classes up) because "Configuration" is quite abstract.
Your @vonnieda opinion please.

**Comment by vonnieda** [comment]
@dave-prosee Very nice work. This looks really good. Sorry for the long response time, was out and about. I agree with your choices of classes, and will merge this now.

**Comment by dave-prosee** [comment]
Took the decision to move the generic code for feeders to the AbstractFeeder class.
I think all you wanted regarding the code in the first two commits has been done.
Please giver your view on the tab names for the remaining objects.
By the way, the drivers have to be checked too

**Comment by dave-prosee** [comment]
Ah, messages crossed. Thanks! You're very welcome. Glad to do something in return for this nice piece of software.
Cheers!

**Pull request merged**
