### PR TITLE
#444 Fixed NamedCSV importer for Altium R14 

### PR DESCRIPTION
**Pull request by Misfittech**
I have added in a fix for importing Altium R14 files, currently only supports mm output from altium

### CODE REVIEW

**Comment by vonnieda** [comment]
Hi @Misfittech, it appears you have reformatted the entire file so I can't tell what the changes you made are. Can you please re-submit with just the changes? I suspect that your editor may have replaced spaces with tabs or something like that. You can see the diff at https://github.com/openpnp/openpnp/pull/461/files.

**Comment by cri-s** [comment]
I'm against allowing 1000 lines for the format line.

**Comment by Misfittech** [comment]
I am trying to figure out how to fix that problem...

I often do a "ctrl-a" followed by "ctrl-I" to clean up indents, I guess
eclipse has this set wrong for the project.

**Comment by Misfittech** [comment]
Sorry about that I downloaded the eclipse formatter and applied to the file
and recommitted.

**Comment by Misfittech** [comment]
Cri-s,

why was there a 10 in there?  I figured it was some sort of time out, but
not sure why....

Thanks
Trampas

**Comment by cri-s** [comment]
The 10 was to look for the format specification on the first 10 lines of the file.
Maybe 10 is a bit less, i agree that someone want more comment on the file and that the number could
be increased, 1000 seems too permissive. 

It's for the line "Designator","Footprint","Mid X","Mid Y" ...
that define the csv contents, As this should be on the file header, if it's not found on the first 10 lines,
it is not a file thats can be read with this importer. Think further that it's possible to open binary files where
one line is several tens of Megabytes. If you increase it to 40 lines, 80, 100, ... it search then the first
N lines of file for the format specifier.

**Comment by Misfittech** [comment]
Since in AD14, the column headers are on line 13, I have updated the code
to stop at row 50, instead of 1000.

I have also added optional part height processing, and option check box to
GUI to update part height if part is already in OpenPnP.

The dialog box form is not spaced the best, row spacing seems large for
check boxes, but I am not sure how to fix. I will read up on it some more.

I have pushed the latest version, again I am just learning so I hope it is
all good, if not please let me know.

Thanks
Trampas

**Comment by vonnieda** [comment]
@Misfittech Sorry for the delay in reviewing this. Been a busy couple days. I have not forgotten it and will get it done as soon as I can.

**Comment by Misfittech** [comment]
No worries... I certainly am not in a hurry.

**Comment by vonnieda** [comment]
Thanks @Misfittech!

**Pull request merged**
