### PR TITLE
workaround for  #462

### PR DESCRIPTION
**Pull request by cri-s**
This is a workaround for  #462 until the bug is resolved .

### CODE REVIEW

**Comment by vonnieda** [comment]
Hi @cri-s, I think this can be fixed much more simply like this:

[patch.diff.txt](https://github.com/openpnp/openpnp/files/882951/patch.diff.txt)

This small patch fixes it for me. Can you try it?

**Comment by vonnieda** [comment]
@cri-s Thoughts on my comment above? I think we can fix this with a much smaller change. See the diff.

**Comment by cri-s** [comment]
I test it out today, i wanted it test yesterday but it was not possible.
I want test it out, not that it uses stricter java rules and then
limits the scriptings a lot,
not allowing easy access to private variables.

2017-04-02 3:51 GMT+02:00, Jason von Nieda <notifications@github.com>:

**Comment by cri-s** [comment]
Unfortunatly is not the same, i don't have tested private variable access.
running a simple script with you'r mods, the strict java mode is enforced.
It produced only the error message:
2017-04-02 23:04:00 MessageBoxes DEBUG: Error: javax.script.ScriptException: Sourced file: eval stream : Attempt to resolve method: size() on undefined variable or class name: locs : at Line: 24 : in file: eval stream : locs .size ( ) 
 in eval stream at line number 24

 I post the code, line 24 begins with i=

	locs = machine.getProperty("bsh-locations");
	if(locs==null) locs=new ArrayList();
	i=locs.size();


Running bsh in strict java mode is useless as there are other engines when using java mode that can
handle arrays and other java language features better.

**Comment by cri-s** [comment]
PS: as scripting class is visible in script interpreter, it should be modified in order to allow access to 
the file item that are used to call the script in order to know the own filename, the base directory.
Example file as variable of type File inside class declared as public or if protected/private works as such.

**Comment by vonnieda** [comment]
@cri-s I think you just have a script error. This works fine for me:

```
print("BSH is working");
locs = machine.getFeeders();
if(locs==null) locs=new ArrayList();
i=locs.size();
print(i);
```

Output is:
```
BSH is working
8
```

**Comment by cri-s** [comment]
Yes, your patch works.

**Comment by vonnieda** [comment]
Fixed in https://github.com/openpnp/openpnp/commit/06b337d282124db35689f7d7b668658ef98431a4

**Pull request closed without merging**
