### PR TITLE
Refactor / Abstract Camera Classes Unified, Camera Settling

### PR DESCRIPTION
**Pull request by markmaker**
# Description
This is a pure refactoring of the abstract Camera classes

- Breaks out all camera settling into the `AbstractSettlingCamera` class between `AbstractCamera` and `ReferenceCamera`.
- Moves `ReferenceCamera` from `reference` to` reference.camera` package.
- Moves `AbstractBroadcastingCamera` from `reference` to `reference.camera` package.

The refactoring remains neutral to `machine.xml` persistence. Luckily the `org.simpleframework.xml.Serializer` does not use fully qualified identifiers in attributes, elements or `enum` constants. As these are all base classes, they also do not affect the instantiated camera classes.

No functional changes were made, yet. 

Note, the bug-fix mistakenly mentioned in the commit message was removed prior to push. It will be included in upcoming changes.

# Justification
This is preparation for adding new features to camera settling. Camera settling was already badly intertwined with the basic functionality of the `AbstractCamera`, it is now properly separated. It always bothered me that `ReferenceCamera` is not in the  `reference.camera` package, and the inconsistency was duplicated when I made the `AbstractBroadcastingCamera`, I did not want to triplicate it. 

Furthermore, I wanted to separate the upcoming functional upgrades from this refactoring, so the changes become trackable.

Admittedly, the code changes are large, through the necessary adjustment of references and imports, but these are just artifacts done by Eclipse refactoring.

# Instructions for Use
No changes.

# Implementation Details
1. Tested camera settling in simulation. 
2. Did follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style).
3. Removed settling from the `org.openpnp.spi.base.AbstractCamera`.
4. Successful `mvn test` before submitting the Pull Request.

### CODE REVIEW

**Comment by ian-arkver** [comment]
Hi Mark.

You've removed the import of ReferenceCamera from each camera type, each of which extends ReferenceCamera. I guess the import is resolved with a chain back through the ConfigurationWizard now. It might be cleaner to keep an import of reference.camera.ReferenceCamera just for readability? It's a minor thing though.

Regards,
Ian

**Comment by markmaker** [comment]
Hi Ian,

I'm a spoiled child when it comes to imports. I let Eclipse figure it out, and frankly never learned Java import rules. 

I noticed the missing `ReferenceCamera` import too, and assumed it is not required, due to being in the same package now(?) 

_Mark

**Comment by ian-arkver** [comment]
Hmm, dunno. I'm no Java import expert either. Since it passes mvn test it must be finding it somehow.

**Comment by ian-arkver** [comment]
I think you're right. Looking at checkstyle docs for [RedundantImport](https://checkstyle.sourceforge.io/config_imports.html#RedundantImport), one of the triggers for the warning is:
"The class non-statically imported is from the same package as the current package."
So indeed removing the import is the right thing to do.

**Comment by ian-arkver** [comment]
fwiw: I rebased my test branch onto your latest test branch, cherry picked the above commit from your repo, then rebased my GstreamerCamera addition on top of that. Once I removed the offending import of the old ReferenceCamera, everything fired up OK and my machine did its Visual Homing OK.

Some time I must try another PR for GstreamerCamera, see if maven central has caught up and it no longer breaks stuff.

**Review by vonnieda — APPROVED** [review]
Looks good to me! Makes sense and cleans things up.

**Comment by markmaker** [comment]
Thanks, @vonnieda!

**Pull request merged**
