### PR TITLE
New OpenCV pipeline stage: MaskModel

### PR DESCRIPTION
**Pull request by dzach**
# Description
A new OpenCV pileline stage is proposed, named `MaskModel`, which offers masking of image based on models derived from previous stages.

## Isolating detected features

`MaskModel` operates with shapes (Circles and RotatedRects) from models created by other stages earlier in the pipeline. Here, the outline of a TQFP-32-8 part is used to completely isolate it from the rest of the image content:

rotatedrect

The result:

rotatedrectcropped

### Using isolated features

Isolated features may be easier to work with, since most of the side effects of image processing on the rest of the image can be masked out. Here, circle detection has been used to isolate features on the previously isolated TQFP-32-8 part:

isolated

# Justification
Isolating parts of an image can help in extracting useful features. Users of OpenPnP's vision system will be able to utilize the new `MaskModel` stage to add flexibility and advanced masking capabilities to their part detection OpenCV pipelines.

# Instructions for Use

screenshot-1
- Use the `modelStageName` parameter to enter the name of a pipeline stage that contains the model(s) to use as a mask
- Use the `inverted` parameter checkbox to change operation from masking to filtering.
- Use the `color` parameter to visualize the shape of the mask, or experiment with tinting the colors of the image. `Black` is the default color for masking.

# Implementation Details
1. How did you test the change?

Visually.

2. Did you add automated tests?

No.

3. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)?

I think so.

4. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing.

No such changes were made.

NOTE: This is part of a more complex pipeline stage that was split to simpler stages. See #539 .

### CODE REVIEW

**Comment by dzach** [comment]
Question:
There are two more new pipeline stages ready for a PR. Should I wait for this to be reviewed/merged and then submit the others in the same manner or should I add the rest of the files here? The new stage files are all new and different and the `CvPipelineEditor.java` only differs by the lines adding the new stages.

**Comment by vonnieda** [comment]
Let's do them one at a time. I'll get this merged tonight.

**Comment by vonnieda** [comment]
Looks good, thank you @dzach!

**Comment by dzach** [comment]
Thanks @vonnieda !

**Pull request merged**
