### PR TITLE
Feature/Advanced Motion Control

### PR DESCRIPTION
**Pull request by markmaker**
# Description
This PR adds the actual Advanced Motion Control on top of the groundwork in #1035 (plus #1038, #1042, #1047) while further refining and completing this basis. 

## Basic Features

- Strongly committed to migrate existing machine setups practically unchanged, users can then adopt advanced Motion Control features step-by-step in a graded approach. 
- Uses sub-classing to add advanced (and sometime still experimental) features only if you want them. Keeps the GUI (mostly) unburdened, if you don't use the features. 

   Motion Planner Choice

- Many individual features are automatically enabled/disabled and compatibility with various types of controllers provided, based on the Motion Control Type you select:
  
   MotionControlType

- Add the Advanced Motion Planner that can optimize a whole path of moves into a jerk controlled, blended, smooth trajectory. 

  AdvancedMotionAnimation

- Add motion path interpolation, that can generate advanced motion into small segments of classic Constant Acceleration Motion understood by many controllers (but see later). 
- Introduces waiting for motion completion, only when needed, i.e. the controller and OpenPnP can fully work in parallel, with command queuing and elimination of some communications delays. 
- Add the GcodeAsyncDriver sub-class that can drive the controller asynchronously, with a writer thread, using asynchronous confirmation flow control (optional) and robust motion completion hand-shaking. 
- A new Axis centric Safe Zone automatically provides the Safe Z for all the HeadMountables that map the axis. No "Safe Z fighting" between shared Axes anymore. 
- Also available on the other linear axes (X, Y), it can (optionally) provide the Safe Zone for uncoordinated a.k.a. "overshooting" motion. But even if you don't use that feature, it allows for optimized Safe Z handling with multi-nozzle machines, i.e. axes don't need to be retracted all the way to the balance-point, saving time on machines with large Z headroom (a HeadMountable already anywhere in the Safe Zone will not be moved on `moveToSafeZ()`). 
- Adds cool graphical Motion Control Diagnostics, showing both the planned and the interpolated ("simulated") motion and the artifacts the interpolation creates:

Diagnostics

## Limitation of Scope / Experimental Features

Not all the features of this PR have been fully proven in practical application yet. The fully smoothed motion interpolation has turned out too complex for Smoothieware both in demands for RAM and for processing power (it can be demonstrated to work in principle, at reduced speed). A much more powerful [Duet3D 3 controller](https://www.duet3d.com/Duet3Mainboard6HC) has been [kindly donated by the manufacturer](https://groups.google.com/g/openpnp/c/fNBor2oFn6c/m/9e0_PaZyBwAJ) to explore these advanced features. Thank you dc42!

However, many very useful features, including interpolation for jerk control alone (without the curved path smoothing), have been proven useful and feasible on Smoothieware and it is assumed to work on other similar 32bit controllers.  

Therefore, it is now my desire to **draw a line and get this work tested, finished and accepted into develop**, separated from any ongoing work with more powerful controllers. There is considerable confidence that the framework for the advanced features is sound and won't require dramatic changes later. 

By making the experimental features available in the testing version, I hope to attract some testers that have rolled their own new powerful controllers in the last months, as discussed in the group. ;-)

# Justification
The justification has been discussed in-depth in the user group.
https://groups.google.com/g/openpnp/c/bEVZvYoXO98/m/hl14FcspBwAJ

# Instructions for Use
I will start writing the Wiki in unlinked pages, starting with the groundwork in #1035 (plus #1038, #1042, #1047) and eventually covering this PR. 

# Implementation Details
1. This work has been tested in various ways, in simulation with the GcodeServer, with a lab controller/stepper contraption and on the machine. Furthermore, various unit tests haven been written and improved. Some existing OpenPnP tests had to be expanded to test the new "Safe Z Zone".  
2. Did follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style).
3. Various changes in the `org.openpnp.spi` or `org.openpnp.model` packages have been done, most are refinements of the changes already done in the groundwork PRs.
4. Did of course run `mvn test` successfully before submitting the Pull Request.

### CODE REVIEW

**Comment by markmaker** [comment]
This comment is used as a repository for images used in the upcoming Wiki page. Do not delete.
____

Axis Coordinate System
Axis Type
Linear Axis Setup
Backlash Compensation

**Comment by CircuitSetup** [comment]
Amazing work @markmaker !!

**Comment by vonnieda** [comment]
Absolutely incredible work @markmaker. It's very exciting to see this go from concept to prototype to working code with all the bells and whistles. Great work on this, and thank you for your continued dedication to outstanding code quality and documentation!

**Comment by markmaker** [comment]
Thanks ¦-)

**Comment by markmaker** [comment]
This comment is used as a repository for images used in the **second round** of editing the Wiki pages. Do not delete.
Wiki pages so far:

-     https://github.com/openpnp/openpnp/wiki/Advanced-Motion-Control
-     https://github.com/openpnp/openpnp/wiki/GcodeAsyncDriver **(new)**
-     https://github.com/openpnp/openpnp/wiki/Motion-Planner
-     https://github.com/openpnp/openpnp/wiki/Machine-Axes
-     https://github.com/openpnp/openpnp/wiki/Backlash-Compensation
-     https://github.com/openpnp/openpnp/wiki/Transformed-Axes
-     https://github.com/openpnp/openpnp/wiki/Linear-Transformed-Axes
-     https://github.com/openpnp/openpnp/wiki/Mapping-Axes

__

Home on enable off

**Pull request merged**
