### PR TITLE
Changed to synchronized methods rather than using a semaphore

### PR DESCRIPTION
**Pull request by tonyluken**
# Description
Just cleans-up [PR#1364](https://github.com/openpnp/openpnp/pull/1364#:~:text=advanced%20calibration%20debug-,%231364,-Merged)

# Justification
This is a better and standard way of doing things.

# Instructions for Use
No special instructions required.

# Implementation Details
1. How did you test the change? **Verified the logs didn't contain any unexpected exceptions after forcing the undistortion mappings and virtual camera matrix to be recomputed many times.**
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? **Yes.**
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing.  **No changes were made to these packages.**
4. Be sure to run `mvn test` before submitting the Pull Request. If the tests do not pass the Pull Request will not be accepted. **Maven tests were run and all passed.**

### CODE REVIEW

**Comment by markmaker** [comment]
Thanks!

**Comment by markmaker** [comment]
Hi @tonyluken,

As this is IMHO getting closer to being ready to be merged into `develop`, could you please write a [CHANGES.md](https://github.com/openpnp/openpnp/blob/test/CHANGES.md) entry for Advanced Camera Calibration?

Make a PR, or just send a fragment to me via email, I will add some stuff too. 

Thanks!
_Mark

**Comment by tonyluken** [comment]
Hi @markmaker,

I'll start a PR for that.  One other thing I noticed is shouldn't the Calibrate Camera Position and Rotation buttons on the Nozzle Tip Calibration tab be disabled when Advanced Calibration is active? I think it might be a mess if folks start mixing the two.

Tony

**Comment by markmaker** [comment]
>  One other thing I noticed is shouldn't the Calibrate Camera Position and Rotation buttons on the Nozzle Tip Calibration tab be disabled when Advanced Calibration is active? I think it might be a mess if folks start mixing the two.

You're right, completely forgot that one. Thanks for fixing it.

_Mark

**Comment by tonyluken** [comment]
Oh! I didn't mean to give the impression that I fixed it - I didn't, I was just pointing it out.

**Comment by markmaker** [comment]
Yes, I saw. I'll fix it.

**Comment by markmaker** [comment]
> One other thing I noticed is shouldn't the Calibrate Camera Position and Rotation buttons on the Nozzle Tip Calibration tab be disabled when Advanced Calibration is active? I think it might be a mess if folks start mixing the two.

See #1367.

**Pull request merged**
