### PR TITLE
Charmhigh  CHM-T48VB Integration

### PR DESCRIPTION
**Pull request by c-riegel**
# Description
These changes primarily add support for the features of the Charmhigh CHM-T48VB based on the firmware developed by Matt Baker.  Other tweaks were made along the way of implementing these features that should help with speed and safety. 

I'm new to git, so I apologize that these are all bundled together.  I thought git would let me make multiple pull requests based on my different commits and there were several issues that would come up as I was doing the integration testing.  My commits to git are more atomic if you can see them individually as part of the pull request.  However, I'm not sure how to break them up on my side.

# Justification
The changes were made so that the machine does not have to  be a T48VB.  Other machines with similar sensors can benefit.  Those without the specific sensors (photo-interrupters for the drag pin and Z-axis) will be unaffected.

# Instructions for Use
The part check was changed in ReferencePnpJobProcessor.
- This is worthy of review.  My tests have shown that the vacuum does not need to be turned back on in order to check for a part still being on the nozzle after placement.  In my experience if the part is still attached to the nozzle it is because the air line is pressurized and the reading indicates this without needing to turn the vacuum back on.

Buttons for turning the vacuum on and off were added to the Feeders tab.
- This is worthy of review.  This feature was only implemented for the Gcode driver.  As I was adding many feeder definitions it was helpful to have a quick button to control the vacuum.  The added icons attempt to reuse the openpnp color scheme.

Changes made to ReferenceDragFeeder:
 - Support was added to handle 0402 parts when not used with vision. Previously it would not get the second part that was feed from an 0402 feed when vision was not enabled.
 - The actuators section now has fields for identifying the drag pin actuator, the value the actuator will read when the pin is safely retracted, and the actuator for peeling off the film.  The feed process will try to confirm that the pin is safely retracted after backing off and if not it will try to back off again to release tension on the pin.  
 - Support was added so that the user can identify which well to pick the next part in the tape from.  This allows users to tell the machine which slots already have exposed parts (primarily useful for 0402 parts, but allows the user to not have to retract the drag feeder for parts).  The Locations section now contains a button labeled 'Set next part offset to:' that will identify which well to pick from.  Setting it to 0 will tell the machine to pick from the pick location without performing a drag operation.  Setting it to 1 will tell the machine to pick from the location in front of the pick location.  Setting it to negative values will tell it to perform a standard feed operation that would include a drag step.

Changes made to ReferenceHeadConfigurationWizard:
- The Z Probe section was implemented so that it will confirm that the Z Probe is reading an acceptable value before doing a move operation.  Fields were added to identify the actuator and the value that the actuator should read when things are safe.
- The Z Probe was also augmented with another actuator and safe value in case another, secondary check should be done to confirm things are safe for move operations.  I use this to confirm the drag pin is safely retracted prior to move operations for my machine.

Clarifications were made on some user interface elements:
 - The panelazition dialog text was modified to read "X Gap Spacing" from "X Spacing" since it was ambiguous if the distance needed was the gap between boards or the distance from a point on one board to the same point on an adjacent board.
- The software check to prevent the machine from going out of bounds was modified so the error message showed which limit was being violated.

# Implementation Details
1. Changes were tested on the CHM-T48B during a day of doing assembly on boards.
2. I told eclipse to use the format definition from the wiki, but maybe I did this wrong or it's not really being used by the group?  Many of the files submitted have whitespace modifications making them more difficult to parse and I wouldn't expect this if the code base actually used the code format definition.

### CODE REVIEW

**Comment by c-riegel** [comment]
I found the logs saying where the tests were causing errors, but I don't know how to resolve them or what the tests are actually trying to do :(

**Comment by vonnieda** [comment]
@c-riegel Is there any way you could re-submit this without the extensive reformatting? With all the reformatting and whitespace changes it's very hard to tell what was a functionality change and what was just a formatting change.

**Comment by c-riegel** [comment]
@vonnieda I think I can, but I was trying to use the Eclipse formatter referenced [here](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style).  Is the code base not really following the coding style, or did I not configure Eclipse properly?  Should this formatter be removed from the developers guide?  Eclipse seems to be formatting by code on every save.

**Comment by vonnieda** [comment]
Hi @c-riegel - yes, the formatter is correct, but not all of the codebase has been reformatted. Most of it was written before the formatter was being used.

For what it's worth, I do not have Eclipse auto-reformat on save. I do tend to format new code when I write it, but the problem with reformatting + changing is that it makes it very hard to pick out the changes from the formatting.

One way to solve this, if you want to reformat, is to reformat, commit, then make your changes and commit again. At least in that case I can look at the specific commits to see what changed.

In general, when looking at the diff / Files Changed tab, the smaller the number of changes, the easier it is to merge.

**Comment by markmaker** [comment]
Hi @c-riegel, @vonnieda 

Just wanted to point out that this partially covers the same ground as #859 with Z probing and the new "actuator everything" system (vacuum readback/Z probing/LEDs etc). 

Some discussion is also here:
https://github.com/openpnp/openpnp/pull/855#issuecomment-500890284

Also we agreed (there) to remove OpenBuildsDriver and LinuxCNC so this would avoid some of the work proposed here.

I agree that #859 is untested and some discussion left open i.e. it is not ready for merge but I hope it is not altogether abandoned and all effort lost.

However I'm completely open for @c-riegel to take this over and try to merge the two efforts, as I'm currently busy with work (and sorry for that).

_Mark

**Comment by c-riegel** [comment]
@vonnieda I'm happy to do whatever you want.  I was just trying to play ball by your guidelines and be a good team player.

I think the easiest thing, if you'll allow me a humble request, would be for you to run the formatter on the files you have that are in my commit and then compare those with my files.  This should let you easily identify my changes, get the code to match the project's developer guidelines, and you won't have concern about there being any other changes snuck it with the formatting changes.  

If you want me to do it on my side just let me know.  I'm not sure what the best way to do this in git is and worry that it will get messy.  Would you recommend me doing a new clone, running the formatter, doing a PR on that, then overwriting my working directory with my current changes and doing a second PR?  It seems git is just appending things on to my previous PR when I make new changes, and I worry that the flow will be confusing this way.  If we go this route should we update the guidelines to suggest a minimum number of edits instead of following the style template?  I'll turn off my auto-formatter.

**Comment by vonnieda** [comment]
Hey @c-riegel, I'm swamped for the next couple days before I can get back to this, but I wanted to mention: You can run the tests from the command line with `mvn test` or from Eclipse by selecting one of the classes, right clicking and selecting Run As... Junit. When you do this you will see the exceptions and errors that are happening during testing, and it should be possible to track them down to find what's going wrong. You can also Debug As... to dig in.

**Comment by c-riegel** [comment]
@vonnieda That's cool.  I am trying to fix it and make it more compatible with the efforts of @markmaker.  Maybe it's best if you wait for things to cool down; there might be less work for you.  It looks like my recent commits are just getting appended to this PR???  I'm trying to at least make my commits atomic by feature.

**Comment by vonnieda** [comment]
@c-riegel I just emailed you some tips on how to manage the PR(s), but regarding the above: Yes, think of a PR like a branch. Any commits in the same branch become part of the same PR. Ideally PRs (branches) should be broken up by feature, and you create one for each feature or bug fix.

**Comment by c-riegel** [comment]
@vonnieda Sorry, the lingo is a little different with git than the tools I'm used to.  Does this mean that I can start another "branch", as you call it above, while one PR is in review so as to not contaminate it with other changes?  If yes, what does git call that process so I can go read more about how to do it?  Is it called branching?

**Comment by vonnieda** [comment]
@c-riegel Yep! Branching in Git is very lightweight. So, you create a branch, write a feature, make one or commits to that branch, push the branch, and submit the PR against the branch. This makes the PR stand on it's own and it can be merged or discarded without affecting anything else. 

For reference, I create many feature branches a day to try out ideas. If I have an idea to fix a bug I'll create a new branch called feature/fix_some_bug, write some code, commit it, test it and if I'm happy with it I'll merge it back to my main branch (develop or master) or if it's no good I'll just discard it with no ill effects.

I'll repost my email here, in case it's helpful to you or others:

---

Hey @c-riegel , just wanted to drop a quick note in the hopes of making the PR process a little easier. It's a busy week for me so I'm having trouble finding the time to really review the PR, but I noticed more commits coming through so I wanted to mention a few tips:

When you want to submit a PR, it's best to work in a branch specifically for that PR. These are called feature branches. So, you create a new branch, (feature/my_great_feature), add some commits to it, test it, then submit a PR from that branch. Then you don't do anything else with that branch. If you continue to commit to and push from that branch it updates the PR, which means I have to re-review the whole thing.

There is more information about this workflow here: https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow

If you have multiple features you want to do, do multiple PRs. The idea is that the smaller the PR the easier it will be to merge. It's much easier to see that one small feature won't break the world than when having to reason about many interlinked features.

You can create a feature branch, send a PR, then create a new branch from that branch and you will have that feature included. This way you can continue to work without having to wait for each to be merged.

Regarding the formatting stuff: Yes, ideally the code should all be formatted, but the reality is that it's in various states. This is a decade old project at this point and there are warts. The goal should be to send the minimal PR possible. This is relatively easy to do by only formatting the code you write, or small blocks that you modify. Reformatting the whole file is never necessary.

There's some more info about this in the Wiki: https://github.com/openpnp/openpnp/wiki/Developers-Guide#granularity

The bottom line for all of this is that when I receive a PR, if I can take a quick look at it, maybe run it once or twice and determine it's not going to break people's machines or configurations, I just merge it. But when it's a big, complicated PR that changes dozens of files, base classes, existing functionality, etc. I need to find (based on experience) dozens of hours to review, test, and fix it before it can be merged. I *will* do this, but it takes much longer - weeks or months instead of hours.

So, there are two options:
1. If you can break this PR into smaller PRs that implement a single small feature or bug fix, I will be able to merge, or at least review them quickly.
2. You can leave it as is, and I will get to it as soon as I can, but that might be quite a long time and, based on previous experience, it might be impossible to merge because of problems it causes other users.

Hope this is helpful. I definitely want to work with you and get this code merged - I'm just trying to find a way to do it without it costing me a week of nights.

**Pull request closed without merging**
