### PR TITLE
Update Camera.java

### PR DESCRIPTION
**Pull request by cri-s**
Small changes to Camera SPI, for OpenCV
view = viewport for user
image = possibly rectified image
picture = for opencv, takes snapshoot and return image.

### CODE REVIEW

**Comment by vonnieda** [comment]
This change will need to pass the Travis CI build before it can be merged. A change to an SPI class will, at least, require changes to the base abstract classes. 

I'd also like some information as to the purpose of this change. What is it for and how is it used?

**Comment by cri-s** [comment]
Visual processing during automatic placement access the picture() image.
This ensure that it gets possibly undistorted image that are granted to be taken after the procedure call.
Otherwise it happens that the image is not usable because taken in motion, and without global shutter
this is really problematic.

**Comment by vonnieda** [comment]
This is the purpose of the capture() call. capture() is intended to take a
still frame using whatever method the camera driver prefers. This is why it
is used by the vision providers. Many of the existing drivers also use
capture to return a steam of images for video, but that is secondary to
it's real purpose.

Currently, if a vision operation requires a still frame it will pause
movement for a short period of time and then call capture() before moving
again. This is a bit scattered through the code. I would like for this to
eventually be part of the VisionProvider but that is going to require more
work.

**Comment by cri-s** [comment]
Yes, actually streaming works with capture, and it will continue to work.
view is for streaming in order to have the possibility to add image enhanchments to video streaming.
it is open if switching to that in the future, defining it is not bad.
image is proposed for taking rectified and maybe scaled images.
and photo is for be sure that the image is not old.
stopping can be bad solution because depending on configuration, the snapshoot can be made during moving.

**Pull request closed without merging**
