### PR TITLE
fixed bugs about tray feeder

### PR DESCRIPTION
**Pull request by cri-s**
on certain valid setup, the orginal feeder remained on the same pickup position without advancing.

### CODE REVIEW

**Comment by vonnieda** [comment]
@cri-s I'm not sure what bug this is intended to fix, but it breaks the tray feeder entirely. See https://www.youtube.com/watch?v=WN4Sit4vckU.

**Comment by cri-s** [comment]
really strange, it works here.  i can make video if you want.

output from log, first 6x2 feeder and second 1 stripe of 33 elements.
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 0, x 0, y 0, xPos 93.303000, yPos 4.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 4.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 1, x 0, y 1, xPos 93.303000, yPos 8.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 8.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 2, x 1, y 0, xPos 95.303000, yPos 4.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (95.303000, 4.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 3, x 1, y 1, xPos 95.303000, yPos 8.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (95.303000, 8.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 4, x 2, y 0, xPos 97.303000, yPos 4.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (97.303000, 4.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 5, x 2, y 1, xPos 97.303000, yPos 8.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (97.303000, 8.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 6, x 3, y 0, xPos 99.303000, yPos 4.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (99.303000, 4.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 7, x 3, y 1, xPos 99.303000, yPos 8.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (99.303000, 8.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 8, x 4, y 0, xPos 101.303000, yPos 4.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (101.303000, 4.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 9, x 4, y 1, xPos 101.303000, yPos 8.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (101.303000, 8.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 10, x 5, y 0, xPos 103.303000, yPos 4.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (103.303000, 4.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 11, x 5, y 1, xPos 103.303000, yPos 8.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (103.303000, 8.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feed Error: java.lang.Exception: Tray empty on feeder ReferenceTrayFeeder.
 ReferenceTrayFeeder.feed(N1)
 Feed Error: java.lang.Exception: Tray empty on feeder ReferenceTrayFeeder.
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 0, x 0, y 0, xPos 93.303000, yPos 4.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 4.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 1, x 0, y 1, xPos 93.303000, yPos 8.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 8.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 2, x 0, y 2, xPos 93.303000, yPos 12.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 12.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 3, x 0, y 3, xPos 93.303000, yPos 16.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 16.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 4, x 0, y 4, xPos 93.303000, yPos 20.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 20.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 5, x 0, y 5, xPos 93.303000, yPos 24.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 24.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 6, x 0, y 6, xPos 93.303000, yPos 28.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 28.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 7, x 0, y 7, xPos 93.303000, yPos 32.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 32.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 8, x 0, y 8, xPos 93.303000, yPos 36.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 36.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 9, x 0, y 9, xPos 93.303000, yPos 40.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 40.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 10, x 0, y 10, xPos 93.303000, yPos 44.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 44.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 11, x 0, y 11, xPos 93.303000, yPos 48.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 48.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 12, x 0, y 12, xPos 93.303000, yPos 52.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 52.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 13, x 0, y 13, xPos 93.303000, yPos 56.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 56.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 14, x 0, y 14, xPos 93.303000, yPos 60.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 60.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 15, x 0, y 15, xPos 93.303000, yPos 64.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 64.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 16, x 0, y 16, xPos 93.303000, yPos 68.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 68.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 17, x 0, y 17, xPos 93.303000, yPos 72.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 72.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 18, x 0, y 18, xPos 93.303000, yPos 76.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 76.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 19, x 0, y 19, xPos 93.303000, yPos 80.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 80.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 20, x 0, y 20, xPos 93.303000, yPos 84.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 84.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 21, x 0, y 21, xPos 93.303000, yPos 88.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 88.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 22, x 0, y 22, xPos 93.303000, yPos 92.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 92.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 23, x 0, y 23, xPos 93.303000, yPos 96.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 96.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 24, x 0, y 24, xPos 93.303000, yPos 100.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 100.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 25, x 0, y 25, xPos 93.303000, yPos 104.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 104.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 26, x 0, y 26, xPos 93.303000, yPos 108.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 108.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 27, x 0, y 27, xPos 93.303000, yPos 112.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 112.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 28, x 0, y 28, xPos 93.303000, yPos 116.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 116.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 29, x 0, y 29, xPos 93.303000, yPos 120.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 120.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 30, x 0, y 30, xPos 93.303000, yPos 124.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 124.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 31, x 0, y 31, xPos 93.303000, yPos 128.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 128.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feeding part # 32, x 0, y 32, xPos 93.303000, yPos 132.264000, rPos 0.000000
 ReferenceTrayFeeder.getPickLocation => (93.303000, 132.264000, 0.000000, 0.000000 mm)
 ReferenceTrayFeeder.feed(N1)
 Feed Error: java.lang.Exception: Tray empty on feeder ReferenceTrayFeeder.

**Comment by cri-s** [comment]
Sorry, please tray it again.

**Comment by vonnieda** [comment]
@cri-s Sorry, I don't know what this is intended to fix. Please read https://github.com/openpnp/openpnp/blob/develop/CONTRIBUTING.md and re-submit this.

* Describe the reason for the change and how this fixes it.
* Follow the coding style: Variables never start with a capital letter in Java.
* Why have you made these variables double? They are counts of parts in trays, they should never be a non-integer value.

**Pull request closed without merging**
