### PR TITLE
Fix/Issues and Solutions HOME_COMMAND

### PR DESCRIPTION
**Pull request by markmaker**
# Description
Issues & Solutions now proposes a `HOME_COMMAND`, even if one is already present. The proposed command is built and compared to the present one. If the present one does not _contain_ the proposed lines, the solution is presented. Users can still add custom lines before and after the command, without I&S wanting to undo them. 

As always, users can also Dismiss the proposed solution, if they know their present command is better.

As an aside, this PR also fixes a typo/text sequence in the `CameraSolutions`.

# Justification
Support cases related to `HOME_COMMAND`, the latest of which is the following:
https://groups.google.com/g/openpnp/c/2DKOxhBc6pg/m/2HgSqTmCCQAJ

# Instructions for Use
No change,

# Implementation Details
1. Tested with Issues & Solutions.
2. Did follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style).
3. No changes in the `org.openpnp.spi` or `org.openpnp.model` packages.
4. Successful `mvn test` before submitting the Pull Request.

### CODE REVIEW

**Comment by lags** [comment]
Hi @markmaker,
after update, I'll report what happens to me (with tinyg).
I&S suggest as you can see in gif the right HOME_COMMAND but when confirmed and refresh, it still appears but under driver section, HOME_COMMAND is present and correct. So seems as if I&S not mark as applied.

Still appears also if close openpnp and reopen

**Comment by markmaker** [comment]
@lags, thanks for the report!

Can you send the machine.xml?

_Mark

**Comment by lags** [comment]
Of course...
[machine.xml.zip](https://github.com/openpnp/openpnp/files/9550586/machine.xml.zip)

**Comment by markmaker** [comment]
Should be fixed in the testing version, see also #1486. 

@lags please test, thanks!

_Mark

**Comment by lags** [comment]
Good job @markmaker.
It works!

**Pull request merged**
