### PR TITLE
Feature/set color transform

### PR DESCRIPTION
**Pull request by codehero**
# Description
Extend SetColor pipeline stage to apply camera transform.

# Justification
The edges of a camera transform create a nuisance when developing vision algorithms.
This PR is one step in eliminating that nuisance by creating a transformed SetColor block.
Using this stage, one can do edge detection and create a perimeter of the image.
This perimeter can be used to mask out the edge data from an image, eliminating phantom edges.

# Instructions for Use
Just tick the transform box in SetColor

# Implementation Details
1. How did you test the change? I applied a rotation in Image Transform to a camera. I tested by ticking/unticking the transform box. Default behaviour was preserved, and expected behaviour was correct.
2. Did you follow the [coding style](https://github.com/openpnp/openpnp/wiki/Developers-Guide#coding-style)? Yes
3. If you made changes in the `org.openpnp.spi` or `org.openpnp.model` packages you will need to add additional justification for these changes. Changes to these packages require extensive review and testing.

I modified the .spi for this specific purpose, but the function transformImage() is generic in scope.
There was no interference in existing functionality, and modifying ReferenceCamera was sufficient to implement the interface change.

### CODE REVIEW

**Comment by markmaker** [comment]
Hi codehero

Have you tried using the crop settings in the camera Image Transform? 

Or masking your image in the pipeline using MaskCircle etc. to get rid of unwanted areas? 

Also some of the more semantic "smartness" needs to be left to the code calling into vision. Often, vision results closer to the center are actively favored: 

https://github.com/openpnp/openpnp/blob/d02251aaef96687e288c8c6510e39e58606bd035/src/main/java/org/openpnp/machine/reference/vision/ReferenceFiducialLocator.java#L100-L110

https://github.com/openpnp/openpnp/blob/3e245fdb89b53ee5691f6d22d60ff20d494f6017/src/main/java/org/openpnp/machine/reference/feeder/ReferenceStripFeeder.java#L298-L305

_Mark

**Comment by codehero** [comment]
Masking is not appropriate for what I am doing.
The border is a property of the capture source and is independent of any vision processing context.
What is the semantic issue here?

**Comment by codehero** [comment]
I corrected a scaling issue causing incorrect output.
I needed to correct the scaling issue by exposing the camera's capture width and height.

The purpose of these changes is to enable more rigorous verification of camera calibrations and reduce human technique necessary to calibrate the camera coordinate systems.

**Comment by markmaker** [comment]
You are not using the latest develop. Hence [the conflict](https://github.com/openpnp/openpnp/pull/887/conflicts). 

I already corrected some bugs there, that may explain some of your issues:

https://github.com/openpnp/openpnp/pull/825/files#diff-9251e7e42cb5389b246eabc2b6540996R360

Before my bugfix: If you changed the camera transform (e.g. rotate) then the width/height of the camera is not properly updated until you restart OpenPNP, resulting in wrong pixel to machine location transform and off-center camera-display. 

This might also explain some of your issues such as not the full image filled with color(?).

Please update your develop branch and try without your modifications. 

After that, if what you want to achieve is still broken, please explain more precisely. I'm afraid I don't understand your Description or Justification. 

_Mark

**Comment by codehero** [comment]
I see the issue. I have been patching against master, not develop.
I have my stuff working in the master branch.
Should new development go into master or develop?

I am working on a method to precisely register the camera coordinate systems without using the nozzle. It uses a rectangular bar of known precise dimensions that both camera systems can view simultaneously. Metrologically speaking, using the nozzle as the intermediary of registering the 2 coordinate system is bad news.

**Comment by codehero** [comment]
Succeeded by #890

**Pull request closed without merging**
